// Code generated by golem. DO NOT EDIT.
// Golem generation digest: 1d6b9a939a19378a22129fe33eb710e126765950d95fdbee40a7ba1661a30864
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v7

package social

import (
	context "context"
	golem "github.com/eleven-am/golem/go/golem"
)

type CommentFindOneRequest = golem.FindOneHookRequest[Comment]
type CommentFindOneResult = golem.FindOneHookResult[Comment]
type CommentFindFirstRequest = golem.FindFirstHookRequest[Comment]
type CommentFindFirstResult = golem.FindFirstHookResult[Comment]
type CommentFindManyRequest = golem.FindManyHookRequest[Comment]
type CommentFindManyResult = golem.FindManyHookResult[Comment]
type CommentCreateRequest = golem.CreateHookRequest[Comment]
type CommentCreateResult = golem.CreateHookResult[Comment]
type CommentUpdateRequest = golem.UpdateHookRequest[Comment]
type CommentUpdateResult = golem.UpdateHookResult[Comment]
type CommentDeleteRequest = golem.DeleteHookRequest[Comment]
type CommentDeleteResult = golem.DeleteHookResult[Comment]
type CommentUpdateManyRequest = golem.UpdateManyHookRequest[Comment]
type CommentUpdateManyResult = golem.UpdateManyHookResult[Comment]
type CommentDeleteManyRequest = golem.DeleteManyHookRequest[Comment]
type CommentDeleteManyResult = golem.DeleteManyHookResult[Comment]

type TagFindOneRequest = golem.FindOneHookRequest[Tag]
type TagFindOneResult = golem.FindOneHookResult[Tag]
type TagFindFirstRequest = golem.FindFirstHookRequest[Tag]
type TagFindFirstResult = golem.FindFirstHookResult[Tag]
type TagFindManyRequest = golem.FindManyHookRequest[Tag]
type TagFindManyResult = golem.FindManyHookResult[Tag]
type TagCreateRequest = golem.CreateHookRequest[Tag]
type TagCreateResult = golem.CreateHookResult[Tag]
type TagUpdateRequest = golem.UpdateHookRequest[Tag]
type TagUpdateResult = golem.UpdateHookResult[Tag]
type TagDeleteRequest = golem.DeleteHookRequest[Tag]
type TagDeleteResult = golem.DeleteHookResult[Tag]
type TagUpdateManyRequest = golem.UpdateManyHookRequest[Tag]
type TagUpdateManyResult = golem.UpdateManyHookResult[Tag]
type TagDeleteManyRequest = golem.DeleteManyHookRequest[Tag]
type TagDeleteManyResult = golem.DeleteManyHookResult[Tag]

type SessionFindOneRequest = golem.FindOneHookRequest[Session]
type SessionFindOneResult = golem.FindOneHookResult[Session]
type SessionFindFirstRequest = golem.FindFirstHookRequest[Session]
type SessionFindFirstResult = golem.FindFirstHookResult[Session]
type SessionFindManyRequest = golem.FindManyHookRequest[Session]
type SessionFindManyResult = golem.FindManyHookResult[Session]
type SessionCreateRequest = golem.CreateHookRequest[Session]
type SessionCreateResult = golem.CreateHookResult[Session]
type SessionUpdateRequest = golem.UpdateHookRequest[Session]
type SessionUpdateResult = golem.UpdateHookResult[Session]
type SessionDeleteRequest = golem.DeleteHookRequest[Session]
type SessionDeleteResult = golem.DeleteHookResult[Session]
type SessionUpdateManyRequest = golem.UpdateManyHookRequest[Session]
type SessionUpdateManyResult = golem.UpdateManyHookResult[Session]
type SessionDeleteManyRequest = golem.DeleteManyHookRequest[Session]
type SessionDeleteManyResult = golem.DeleteManyHookResult[Session]

type PostFindOneRequest = golem.FindOneHookRequest[Post]
type PostFindOneResult = golem.FindOneHookResult[Post]
type PostFindFirstRequest = golem.FindFirstHookRequest[Post]
type PostFindFirstResult = golem.FindFirstHookResult[Post]
type PostFindManyRequest = golem.FindManyHookRequest[Post]
type PostFindManyResult = golem.FindManyHookResult[Post]
type PostCreateRequest = golem.CreateHookRequest[Post]
type PostCreateResult = golem.CreateHookResult[Post]
type PostUpdateRequest = golem.UpdateHookRequest[Post]
type PostUpdateResult = golem.UpdateHookResult[Post]
type PostDeleteRequest = golem.DeleteHookRequest[Post]
type PostDeleteResult = golem.DeleteHookResult[Post]
type PostUpdateManyRequest = golem.UpdateManyHookRequest[Post]
type PostUpdateManyResult = golem.UpdateManyHookResult[Post]
type PostDeleteManyRequest = golem.DeleteManyHookRequest[Post]
type PostDeleteManyResult = golem.DeleteManyHookResult[Post]

type PostTagFindOneRequest = golem.FindOneHookRequest[PostTag]
type PostTagFindOneResult = golem.FindOneHookResult[PostTag]
type PostTagFindFirstRequest = golem.FindFirstHookRequest[PostTag]
type PostTagFindFirstResult = golem.FindFirstHookResult[PostTag]
type PostTagFindManyRequest = golem.FindManyHookRequest[PostTag]
type PostTagFindManyResult = golem.FindManyHookResult[PostTag]
type PostTagCreateRequest = golem.CreateHookRequest[PostTag]
type PostTagCreateResult = golem.CreateHookResult[PostTag]
type PostTagUpdateRequest = golem.UpdateHookRequest[PostTag]
type PostTagUpdateResult = golem.UpdateHookResult[PostTag]
type PostTagDeleteRequest = golem.DeleteHookRequest[PostTag]
type PostTagDeleteResult = golem.DeleteHookResult[PostTag]
type PostTagUpdateManyRequest = golem.UpdateManyHookRequest[PostTag]
type PostTagUpdateManyResult = golem.UpdateManyHookResult[PostTag]
type PostTagDeleteManyRequest = golem.DeleteManyHookRequest[PostTag]
type PostTagDeleteManyResult = golem.DeleteManyHookResult[PostTag]

type VersionedNoteFindOneRequest = golem.FindOneHookRequest[VersionedNote]
type VersionedNoteFindOneResult = golem.FindOneHookResult[VersionedNote]
type VersionedNoteFindFirstRequest = golem.FindFirstHookRequest[VersionedNote]
type VersionedNoteFindFirstResult = golem.FindFirstHookResult[VersionedNote]
type VersionedNoteFindManyRequest = golem.FindManyHookRequest[VersionedNote]
type VersionedNoteFindManyResult = golem.FindManyHookResult[VersionedNote]
type VersionedNoteCreateRequest = golem.CreateHookRequest[VersionedNote]
type VersionedNoteCreateResult = golem.CreateHookResult[VersionedNote]
type VersionedNoteUpdateRequest = golem.UpdateHookRequest[VersionedNote]
type VersionedNoteUpdateResult = golem.UpdateHookResult[VersionedNote]
type VersionedNoteDeleteRequest = golem.DeleteHookRequest[VersionedNote]
type VersionedNoteDeleteResult = golem.DeleteHookResult[VersionedNote]
type VersionedNoteUpdateManyRequest = golem.UpdateManyHookRequest[VersionedNote]
type VersionedNoteUpdateManyResult = golem.UpdateManyHookResult[VersionedNote]
type VersionedNoteDeleteManyRequest = golem.DeleteManyHookRequest[VersionedNote]
type VersionedNoteDeleteManyResult = golem.DeleteManyHookResult[VersionedNote]

type UserFindOneRequest = golem.FindOneHookRequest[User]
type UserFindOneResult = golem.FindOneHookResult[User]
type UserFindFirstRequest = golem.FindFirstHookRequest[User]
type UserFindFirstResult = golem.FindFirstHookResult[User]
type UserFindManyRequest = golem.FindManyHookRequest[User]
type UserFindManyResult = golem.FindManyHookResult[User]
type UserCreateRequest = golem.CreateHookRequest[User]
type UserCreateResult = golem.CreateHookResult[User]
type UserUpdateRequest = golem.UpdateHookRequest[User]
type UserUpdateResult = golem.UpdateHookResult[User]
type UserDeleteRequest = golem.DeleteHookRequest[User]
type UserDeleteResult = golem.DeleteHookResult[User]
type UserUpdateManyRequest = golem.UpdateManyHookRequest[User]
type UserUpdateManyResult = golem.UpdateManyHookResult[User]
type UserDeleteManyRequest = golem.DeleteManyHookRequest[User]
type UserDeleteManyResult = golem.DeleteManyHookResult[User]

func golemBuildCommentPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Comment]()
	Comment{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x36, 0x4a, 0x38, 0x61, 0xc2, 0xd3, 0x82, 0xec, 0x0f, 0x02, 0xe8, 0x39, 0x74, 0xf3, 0xb3, 0xc4})
}

func golemBuildTagPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Tag]()
	Tag{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x80, 0xfe, 0x9a, 0xaf, 0x21, 0x42, 0x6d, 0x79, 0x26, 0xca, 0x36, 0xad, 0x6e, 0x8a, 0x95, 0xdf})
}

func golemBuildSessionPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Session]()
	Session{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x9f, 0x0a, 0x32, 0xff, 0x74, 0xe8, 0x34, 0x03, 0x44, 0xdb, 0xde, 0x26, 0xa5, 0x8b, 0xa9, 0xb2})
}

func golemInvokePostBeforeFindMany(ctx context.Context, request *PostFindManyRequest) error {
	return Post{}.BeforeFindMany(ctx, request)
}

func golemInvokePostAfterFindMany(ctx context.Context, result PostFindManyResult) error {
	return Post{}.AfterFindMany(ctx, result)
}

func golemInvokePostBeforeCreate(ctx context.Context, request *PostCreateRequest) error {
	return Post{}.BeforeCreate(ctx, request)
}

func golemInvokePostAfterCreate(ctx context.Context, result PostCreateResult) error {
	return Post{}.AfterCreate(ctx, result)
}

func golemInvokePostAfterCommitCreate(ctx context.Context, result PostCreateResult) error {
	return Post{}.AfterCommitCreate(ctx, result)
}

func golemBuildPostPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Post]()
	Post{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18})
}

func golemBuildPostTagPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[PostTag]()
	PostTag{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0xb2, 0xa6, 0xfb, 0x28, 0x93, 0x65, 0xab, 0x32, 0x86, 0x9f, 0x1b, 0x28, 0x62, 0xcc, 0x6b, 0x5b})
}

func golemBuildVersionedNotePolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[VersionedNote]()
	VersionedNote{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0xc3, 0xe1, 0x21, 0x05, 0x86, 0xec, 0x19, 0xf9, 0xc5, 0x5a, 0x7b, 0x5f, 0x15, 0x72, 0x81, 0x64})
}

func golemBuildUserPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[User]()
	User{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0xd5, 0x23, 0x9e, 0xc6, 0x06, 0x5f, 0xeb, 0xe6, 0x1d, 0xad, 0x1b, 0x8d, 0x0b, 0x66, 0xbf, 0x07})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, Comment](golem.ModelID{0x36, 0x4a, 0x38, 0x61, 0xc2, 0xd3, 0x82, 0xec, 0x0f, 0x02, 0xe8, 0x39, 0x74, 0xf3, 0xb3, 0xc4}, golemBuildCommentPolicy),
		golem.GeneratedPolicyBinding[Actor, Tag](golem.ModelID{0x80, 0xfe, 0x9a, 0xaf, 0x21, 0x42, 0x6d, 0x79, 0x26, 0xca, 0x36, 0xad, 0x6e, 0x8a, 0x95, 0xdf}, golemBuildTagPolicy),
		golem.GeneratedPolicyBinding[Actor, Session](golem.ModelID{0x9f, 0x0a, 0x32, 0xff, 0x74, 0xe8, 0x34, 0x03, 0x44, 0xdb, 0xde, 0x26, 0xa5, 0x8b, 0xa9, 0xb2}, golemBuildSessionPolicy),
		golem.GeneratedPolicyBinding[Actor, Post](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golemBuildPostPolicy),
		golem.GeneratedPolicyBinding[Actor, PostTag](golem.ModelID{0xb2, 0xa6, 0xfb, 0x28, 0x93, 0x65, 0xab, 0x32, 0x86, 0x9f, 0x1b, 0x28, 0x62, 0xcc, 0x6b, 0x5b}, golemBuildPostTagPolicy),
		golem.GeneratedPolicyBinding[Actor, VersionedNote](golem.ModelID{0xc3, 0xe1, 0x21, 0x05, 0x86, 0xec, 0x19, 0xf9, 0xc5, 0x5a, 0x7b, 0x5f, 0x15, 0x72, 0x81, 0x64}, golemBuildVersionedNotePolicy),
		golem.GeneratedPolicyBinding[Actor, User](golem.ModelID{0xd5, 0x23, 0x9e, 0xc6, 0x06, 0x5f, 0xeb, 0xe6, 0x1d, 0xad, 0x1b, 0x8d, 0x0b, 0x66, 0xbf, 0x07}, golemBuildUserPolicy),
	}
	hooks := []golem.HookBinding[Actor]{
		golem.GeneratedBeforeHookBinding[Actor, Post, PostFindManyRequest](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golem.HookFindMany, golemInvokePostBeforeFindMany),
		golem.GeneratedAfterHookBinding[Actor, Post, PostFindManyResult](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golem.HookFindMany, golemInvokePostAfterFindMany),
		golem.GeneratedBeforeHookBinding[Actor, Post, PostCreateRequest](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golem.HookCreate, golemInvokePostBeforeCreate),
		golem.GeneratedAfterHookBinding[Actor, Post, PostCreateResult](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golem.HookCreate, golemInvokePostAfterCreate),
		golem.GeneratedAfterCommitHookBinding[Actor, Post, PostCreateResult](golem.ModelID{0xb1, 0x1b, 0x75, 0xf1, 0x16, 0x68, 0xa6, 0xf7, 0x01, 0x9d, 0x05, 0xb1, 0x74, 0x0d, 0x51, 0x18}, golem.HookCreate, golemInvokePostAfterCommitCreate),
	}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0x1d, 0x6b, 0x9a, 0x93, 0x9a, 0x19, 0x37, 0x8a, 0x22, 0x12, 0x9f, 0xe3, 0x3e, 0xb7, 0x10, 0xe1, 0x26, 0x76, 0x59, 0x50, 0xd9, 0x5f, 0xdb, 0xee, 0x40, 0xa7, 0xba, 0x16, 0x61, 0xa3, 0x08, 0x64}, policies, hooks)
}
