package runtime

import (
	"context"
	"fmt"
	"reflect"

	"github.com/eleven-am/golem/go/golem"
	"github.com/eleven-am/golem/go/internal/migration"
	"github.com/eleven-am/golem/go/internal/physical"
	providerhandle "github.com/eleven-am/golem/go/internal/provider/handle"
	postgresprovider "github.com/eleven-am/golem/go/internal/provider/postgresql"
	sqliteprovider "github.com/eleven-am/golem/go/internal/provider/sqlite"
	providerapi "github.com/eleven-am/golem/go/provider"
	"github.com/jmoiron/sqlx"
)

type reviewedMigrationStartup struct {
	manifest migration.Manifest
}

// prepareReviewedMigrationStartup performs every check that can be decided
// from generated bytes before issuing database work. The only bypass is an
// internal, explicitly unverified fixture handle that external applications
// cannot construct or classify.
func prepareReviewedMigrationStartup(database *providerapi.Database, bundle golem.SchemaBundle, provider golem.Provider, expected physical.PhysicalSchema) (*reviewedMigrationStartup, error) {
	if database != nil && (*providerhandle.Database)(database).IsUnverifiedForTest() {
		return nil, nil
	}
	manifestBytes, err := bundle.MigrationManifest(provider)
	if err != nil {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: provider %s reviewed migration manifest is missing or does not match the generated application", provider)
	}
	manifest, err := migration.ParseManifest(manifestBytes)
	if err != nil {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: decode reviewed migration manifest: %w", err)
	}
	if err := migration.VerifyEmbeddedManifest(manifest); err != nil {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: invalid reviewed migration manifest: %w", err)
	}
	if len(manifest.Entries) == 0 {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: reviewed migration manifest is empty")
	}
	if string(manifest.Provider.Provider) != string(provider) || !reflect.DeepEqual(manifest.Provider, expected.Provider) {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: reviewed migration provider does not match the generated physical schema")
	}
	head := manifest.Entries[len(manifest.Entries)-1]
	physicalFingerprint, err := physical.PhysicalFingerprint(expected)
	if err != nil {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: fingerprint generated physical schema: %w", err)
	}
	if head.AfterModel != migration.Digest(bundle.Model().Fingerprint().String()) || head.AfterPhysical != migration.Digest(physicalFingerprint.String()) {
		return nil, fmt.Errorf("P8_RUNTIME_MIGRATION: reviewed migration head does not match the generated schema")
	}
	return &reviewedMigrationStartup{manifest: manifest}, nil
}

func verifyReviewedMigrationLedger(ctx context.Context, database *sqlx.DB, provider golem.Provider, system physical.SystemSchema, startup *reviewedMigrationStartup) error {
	if startup == nil {
		return nil
	}
	var (
		ledger []migration.LedgerEntry
		err    error
	)
	switch provider {
	case golem.SQLite:
		ledger, err = sqliteprovider.New().ReadLedgerForSchema(ctx, database, system)
	case golem.PostgreSQL:
		ledger, err = postgresprovider.New().ReadLedgerForSchema(ctx, database, system)
	default:
		return fmt.Errorf("P8_RUNTIME_MIGRATION: unsupported provider %q", provider)
	}
	if err != nil {
		return fmt.Errorf("P8_RUNTIME_MIGRATION: read live migration ledger: %w", err)
	}
	if err := migration.VerifyLedger(startup.manifest, ledger); err != nil {
		return fmt.Errorf("P8_RUNTIME_MIGRATION: live migration ledger does not exactly match the reviewed manifest: %w", err)
	}
	return nil
}
