// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p8-graphql-abi-v4; generation fixture-generation; generator fixture-generator; template fixture-template.

package golemgqlgen

import (
	"fmt"
	"io"
	"strconv"
)

type GolemEventType string

const (
	GolemEventTypeCreated GolemEventType = "CREATED"
	GolemEventTypeUpdated GolemEventType = "UPDATED"
	GolemEventTypeDeleted GolemEventType = "DELETED"
)

var AllGolemEventType = []GolemEventType{
	GolemEventTypeCreated,
	GolemEventTypeUpdated,
	GolemEventTypeDeleted,
}

func (e GolemEventType) IsValid() bool {
	switch e {
	case GolemEventTypeCreated, GolemEventTypeUpdated, GolemEventTypeDeleted:
		return true
	}
	return false
}

func (e GolemEventType) String() string {
	return string(e)
}

func (e *GolemEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GolemEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GolemEventType", str)
	}
	return nil
}

func (e GolemEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
