// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p7-graphql-abi-v3; generation fixture-generation; generator fixture-generator; template fixture-template.
package golemgqlgen

// THIS CODE WILL BE UPDATED WITH SCHEMA CHANGES. PREVIOUS IMPLEMENTATION FOR SCHEMA CHANGES WILL BE KEPT IN THE COMMENT SECTION. IMPLEMENTATION FOR UNCHANGED SCHEMA WILL BE KEPT.

import (
	"context"

	graphql1 "github.com/eleven-am/golem/go/graphql"
)

type Resolver struct{}

func (r *queryResolver) Viewer(ctx context.Context) (int, error) {
	return graphql1.ResolvePreparedRoot[int](ctx)

}

func (r *subscriptionResolver) Ticks(ctx context.Context) (<-chan graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedSubscriptionRoot[graphql1.PreparedObject](ctx)

}

func (r *thingResolver) Value(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *tickEventResolver) EventID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *tickEventResolver) Type(ctx context.Context, obj graphql1.PreparedObject) (GolemEventType, error) {
	return graphql1.ResolvePreparedField[GolemEventType](ctx, obj)

}

func (r *tickEventResolver) Entity(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

func (r *Resolver) Thing() ThingResolver { return &thingResolver{r} }

func (r *Resolver) TickEvent() TickEventResolver { return &tickEventResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type thingResolver struct{ *Resolver }
type tickEventResolver struct{ *Resolver }
