// Package registry emits the generated application-level binding registry that
// composes every model package accessor in canonical import-path order.
package registry

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"go/format"
	"go/token"
	"path/filepath"
	"sort"
	"strings"

	modelcodegen "github.com/eleven-am/golem/go/internal/codegen/model"
	"github.com/eleven-am/golem/go/internal/compiler/ir"
	"github.com/eleven-am/golem/go/internal/physical"
)

const Filename = "zz_golem_registry.gen.go"

type Request struct {
	AppPackage         modelcodegen.PackageSpec
	ModelPackages      []modelcodegen.PackageSpec
	Actor              ir.GoNamedTypeIR
	GolemImportPath    string
	GenerationDigest   string
	GeneratorVersion   string
	TemplateABIVersion string
	Schema             SchemaInput
}

// SchemaInput remains generator-internal. Generated application code receives
// only opaque canonical byte blobs and public fixed-width digest values.
type SchemaInput struct {
	Model               ir.ModelIR
	Contract            ir.ContractIR
	ModelFingerprint    ir.Fingerprint
	ContractFingerprint ir.Fingerprint
	Providers           []ProviderInput
}

type ProviderInput struct {
	Schema            physical.PhysicalSchema
	Fingerprint       ir.Fingerprint
	SystemFingerprint ir.Fingerprint
}

type File struct {
	ImportPath, PackageName, Path string
	Source                        []byte
}

func Emit(request Request) (File, error) {
	if request.GolemImportPath == "" {
		request.GolemImportPath = modelcodegen.DefaultGolemImportPath
	}
	if request.AppPackage.ImportPath == "" || !token.IsIdentifier(request.AppPackage.PackageName) {
		return File{}, fmt.Errorf("registry codegen: invalid application package specification")
	}
	if request.Actor.PackagePath == "" || !token.IsIdentifier(request.Actor.Name) {
		return File{}, fmt.Errorf("registry codegen: invalid actor identity")
	}
	bundle, err := prepareSchemaBundle(request)
	if err != nil {
		return File{}, err
	}
	packages := append([]modelcodegen.PackageSpec(nil), request.ModelPackages...)
	sort.Slice(packages, func(i, j int) bool { return packages[i].ImportPath < packages[j].ImportPath })
	for index, spec := range packages {
		if spec.ImportPath == "" || !token.IsIdentifier(spec.PackageName) {
			return File{}, fmt.Errorf("registry codegen: invalid model package specification %#v", spec)
		}
		if index > 0 && packages[index-1].ImportPath == spec.ImportPath {
			return File{}, fmt.Errorf("registry codegen: duplicate model package %q", spec.ImportPath)
		}
	}
	imports := newImports(request.AppPackage.ImportPath)
	golem := imports.qualify(request.GolemImportPath, "golem")
	actorAlias := imports.qualify(request.Actor.PackagePath, "actorpkg")
	actorType := request.Actor.Name
	if actorAlias != "" {
		actorType = actorAlias + "." + request.Actor.Name
	}
	aliases := make([]string, len(packages))
	for index, spec := range packages {
		aliases[index] = imports.qualify(spec.ImportPath, "models")
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by golem. DO NOT EDIT.\n")
	if request.GenerationDigest != "" {
		fmt.Fprintf(&source, "// Golem generation digest: %s\n", request.GenerationDigest)
		if request.GeneratorVersion != "" {
			fmt.Fprintf(&source, "// Golem generator version: %s\n", request.GeneratorVersion)
		}
		if request.TemplateABIVersion != "" {
			fmt.Fprintf(&source, "// Golem template ABI version: %s\n", request.TemplateABIVersion)
		}
	}
	fmt.Fprintf(&source, "\npackage %s\n\n", request.AppPackage.PackageName)
	imports.write(&source)
	fmt.Fprintf(&source, "func golemGeneratedGenerationDigest() %s.SchemaDigest {\n", golem)
	fmt.Fprintf(&source, "\treturn %s\n}\n", digestLiteral(golem, bundle.generationDigest))
	fmt.Fprintf(&source, "\nfunc GolemGeneratedApplicationBindings() (%s.ApplicationBindings[%s], error) {\n", golem, actorType)
	fmt.Fprintf(&source, "\treturn %s.GeneratedApplicationBindings(golemGeneratedGenerationDigest(),\n", golem)
	for _, alias := range aliases {
		if alias == "" {
			source.WriteString("\t\tGolemGeneratedBindings(),\n")
		} else {
			fmt.Fprintf(&source, "\t\t%s.GolemGeneratedBindings(),\n", alias)
		}
	}
	source.WriteString("\t)\n}\n")
	fmt.Fprintf(&source, "\nfunc GolemGeneratedSchemaBundle() %s.SchemaBundle {\n", golem)
	fmt.Fprintf(&source, "\treturn %s.GeneratedSchemaBundle(\n", golem)
	source.WriteString("\t\tgolemGeneratedGenerationDigest(),\n")
	fmt.Fprintf(&source, "\t\t%q,\n\t\t%q,\n", request.GeneratorVersion, request.TemplateABIVersion)
	fmt.Fprintf(&source, "\t\t%s,\n", documentLiteral(golem, bundle.model))
	fmt.Fprintf(&source, "\t\t%s,\n", documentLiteral(golem, bundle.contract))
	for _, provider := range bundle.providers {
		fmt.Fprintf(&source, "\t\t%s.GeneratedProviderSchemaDocument(%s, %s, %s),\n", golem, providerLiteral(golem, provider.provider), digestLiteral(golem, provider.systemFingerprint), documentLiteral(golem, provider.document))
	}
	source.WriteString("\t)\n}\n")
	fmt.Fprintf(&source, "\nfunc GolemGeneratedApplicationDescriptors() (%s.ApplicationDescriptors, error) {\n", golem)
	fmt.Fprintf(&source, "\treturn %s.GeneratedApplicationDescriptors(golemGeneratedGenerationDigest(),\n", golem)
	for _, alias := range aliases {
		if alias == "" {
			source.WriteString("\t\tGolemGeneratedDescriptors(),\n")
		} else {
			fmt.Fprintf(&source, "\t\t%s.GolemGeneratedDescriptors(),\n", alias)
		}
	}
	source.WriteString("\t)\n}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return File{}, fmt.Errorf("registry codegen: format: %w\n%s", err, source.String())
	}
	path := Filename
	if request.AppPackage.Directory != "" {
		path = filepath.Join(request.AppPackage.Directory, Filename)
	}
	return File{ImportPath: request.AppPackage.ImportPath, PackageName: request.AppPackage.PackageName, Path: path, Source: formatted}, nil
}

type preparedDocument struct {
	formatVersion, canonicalVersion uint32
	fingerprint                     [32]byte
	payload                         []byte
}

type preparedProvider struct {
	provider          ir.Provider
	systemFingerprint [32]byte
	document          preparedDocument
}

type preparedBundle struct {
	generationDigest [32]byte
	model, contract  preparedDocument
	providers        []preparedProvider
}

func prepareSchemaBundle(request Request) (preparedBundle, error) {
	if request.GeneratorVersion == "" || request.TemplateABIVersion == "" {
		return preparedBundle{}, fmt.Errorf("registry codegen: schema bundle requires generator and template ABI versions")
	}
	generationDigest, err := parseDigest(request.GenerationDigest)
	if err != nil {
		return preparedBundle{}, fmt.Errorf("registry codegen: generation digest: %w", err)
	}
	modelBytes, err := ir.CanonicalModel(request.Schema.Model)
	if err != nil {
		return preparedBundle{}, fmt.Errorf("registry codegen: canonical model bundle: %w", err)
	}
	actualModelFingerprint, err := ir.ModelFingerprint(request.Schema.Model)
	if err != nil {
		return preparedBundle{}, err
	}
	if actualModelFingerprint != request.Schema.ModelFingerprint {
		return preparedBundle{}, fmt.Errorf("registry codegen: model blob/fingerprint mismatch")
	}
	modelFingerprint, err := parseDigest(string(request.Schema.ModelFingerprint))
	if err != nil {
		return preparedBundle{}, fmt.Errorf("registry codegen: model fingerprint: %w", err)
	}
	contractBytes, err := ir.CanonicalContract(request.Schema.Contract)
	if err != nil {
		return preparedBundle{}, fmt.Errorf("registry codegen: canonical contract bundle: %w", err)
	}
	actualContractFingerprint, err := ir.ContractFingerprint(request.Schema.Contract)
	if err != nil {
		return preparedBundle{}, err
	}
	if actualContractFingerprint != request.Schema.ContractFingerprint {
		return preparedBundle{}, fmt.Errorf("registry codegen: contract blob/fingerprint mismatch")
	}
	contractFingerprint, err := parseDigest(string(request.Schema.ContractFingerprint))
	if err != nil {
		return preparedBundle{}, fmt.Errorf("registry codegen: contract fingerprint: %w", err)
	}
	result := preparedBundle{
		generationDigest: generationDigest,
		model:            preparedDocument{formatVersion: uint32(request.Schema.Model.FormatVersion), canonicalVersion: uint32(ir.CanonicalFormatVersion), fingerprint: modelFingerprint, payload: modelBytes},
		contract:         preparedDocument{formatVersion: uint32(request.Schema.Contract.FormatVersion), canonicalVersion: uint32(ir.CanonicalFormatVersion), fingerprint: contractFingerprint, payload: contractBytes},
	}
	providers := append([]ProviderInput(nil), request.Schema.Providers...)
	sort.Slice(providers, func(i, j int) bool {
		return providers[i].Schema.Provider.Provider < providers[j].Schema.Provider.Provider
	})
	declared := make(map[ir.Provider]bool, len(request.Schema.Model.Providers))
	for _, provider := range request.Schema.Model.Providers {
		if declared[provider] {
			return preparedBundle{}, fmt.Errorf("registry codegen: model declares provider %s more than once", provider)
		}
		declared[provider] = true
	}
	seen := make(map[ir.Provider]bool, len(providers))
	for _, provider := range providers {
		normalized, normalizeErr := physical.Normalize(provider.Schema)
		if normalizeErr != nil {
			return preparedBundle{}, fmt.Errorf("registry codegen: normalize provider bundle: %w", normalizeErr)
		}
		identity := normalized.Provider.Provider
		if identity == "" || seen[identity] {
			return preparedBundle{}, fmt.Errorf("registry codegen: empty or duplicate provider bundle %q", identity)
		}
		if !declared[identity] {
			return preparedBundle{}, fmt.Errorf("registry codegen: provider bundle %s is not declared by ModelIR", identity)
		}
		seen[identity] = true
		actual, fingerprintErr := physical.PhysicalFingerprint(normalized)
		if fingerprintErr != nil {
			return preparedBundle{}, fingerprintErr
		}
		if actual.String() != string(provider.Fingerprint) {
			return preparedBundle{}, fmt.Errorf("registry codegen: provider %s blob/fingerprint mismatch", identity)
		}
		fingerprint, parseErr := parseDigest(string(provider.Fingerprint))
		if parseErr != nil {
			return preparedBundle{}, fmt.Errorf("registry codegen: provider %s fingerprint: %w", identity, parseErr)
		}
		actualSystem, systemErr := physical.SystemFingerprint(normalized.Provider, normalized.System)
		if systemErr != nil {
			return preparedBundle{}, fmt.Errorf("registry codegen: fingerprint provider %s system schema: %w", identity, systemErr)
		}
		if actualSystem.String() != string(provider.SystemFingerprint) {
			return preparedBundle{}, fmt.Errorf("registry codegen: provider %s system blob/fingerprint mismatch", identity)
		}
		systemFingerprint, systemParseErr := parseDigest(string(provider.SystemFingerprint))
		if systemParseErr != nil {
			return preparedBundle{}, fmt.Errorf("registry codegen: provider %s system fingerprint: %w", identity, systemParseErr)
		}
		payload, encodeErr := physical.CanonicalEncode(normalized)
		if encodeErr != nil {
			return preparedBundle{}, fmt.Errorf("registry codegen: encode provider %s bundle: %w", identity, encodeErr)
		}
		result.providers = append(result.providers, preparedProvider{provider: identity, systemFingerprint: systemFingerprint, document: preparedDocument{formatVersion: normalized.Version, canonicalVersion: normalized.CanonicalVersion, fingerprint: fingerprint, payload: payload}})
	}
	if len(seen) != len(declared) {
		var missing []string
		for provider := range declared {
			if !seen[provider] {
				missing = append(missing, string(provider))
			}
		}
		sort.Strings(missing)
		return preparedBundle{}, fmt.Errorf("registry codegen: missing declared provider bundles: %s", strings.Join(missing, ", "))
	}
	return result, nil
}

func parseDigest(value string) ([32]byte, error) {
	var result [32]byte
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != len(result) || hex.EncodeToString(decoded) != value {
		return result, fmt.Errorf("%q is not a canonical SHA-256 digest", value)
	}
	copy(result[:], decoded)
	return result, nil
}

func digestLiteral(golem string, digest [32]byte) string {
	values := make([]string, len(digest))
	for index, value := range digest {
		values[index] = fmt.Sprintf("0x%02x", value)
	}
	return golem + ".SchemaDigest{" + strings.Join(values, ", ") + "}"
}

func documentLiteral(golem string, document preparedDocument) string {
	return fmt.Sprintf("%s.GeneratedSchemaDocument(%d, %d, %s, []byte(%q))", golem, document.formatVersion, document.canonicalVersion, digestLiteral(golem, document.fingerprint), string(document.payload))
}

func providerLiteral(golem string, provider ir.Provider) string {
	switch provider {
	case ir.SQLite:
		return golem + ".SQLite"
	case ir.PostgreSQL:
		return golem + ".PostgreSQL"
	default:
		return fmt.Sprintf("%s.Provider(%q)", golem, provider)
	}
}

type importSet struct {
	current string
	aliases map[string]string
	used    map[string]bool
}

func newImports(current string) *importSet {
	return &importSet{current: current, aliases: map[string]string{}, used: map[string]bool{}}
}
func (set *importSet) qualify(path, preferred string) string {
	if path == set.current {
		return ""
	}
	if alias := set.aliases[path]; alias != "" {
		return alias
	}
	alias := preferred
	for suffix := 2; set.used[alias]; suffix++ {
		alias = fmt.Sprintf("%s%d", preferred, suffix)
	}
	set.aliases[path], set.used[alias] = alias, true
	return alias
}
func (set *importSet) write(buffer *bytes.Buffer) {
	paths := make([]string, 0, len(set.aliases))
	for path := range set.aliases {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	buffer.WriteString("import (\n")
	for _, path := range paths {
		fmt.Fprintf(buffer, "\t%s %q\n", set.aliases[path], path)
	}
	buffer.WriteString(")\n\n")
}
