ALTER TABLE "public"."tags" DROP CONSTRAINT "ck_max_length_1d00396c5e8c";
ALTER TABLE "public"."users" DROP CONSTRAINT "ck_max_length_4815c37e72be";
ALTER TABLE "public"."users" DROP CONSTRAINT "uq_users_handle";
ALTER TABLE "public"."users" ALTER COLUMN "handle" TYPE character varying(40) USING "handle"::character varying(40);
ALTER TABLE "public"."users" ADD CONSTRAINT "uq_users_handle" UNIQUE ("handle");
ALTER TABLE "public"."posts" DROP CONSTRAINT "ck_max_length_7aace88823b2";
ALTER TABLE "public"."posts" ALTER COLUMN "title" TYPE character varying(160) USING "title"::character varying(160);
ALTER TABLE "public"."post_tags" DROP CONSTRAINT "fk_post_tags_tag_name";
ALTER TABLE "public"."tags" DROP CONSTRAINT "uq_tags_name";
ALTER TABLE "public"."tags" ALTER COLUMN "name" TYPE character varying(64) USING "name"::character varying(64);
ALTER TABLE "public"."tags" ADD CONSTRAINT "uq_tags_name" UNIQUE ("name");
DROP INDEX "public"."idx_post_tags_tag_post";
ALTER TABLE "public"."users" DROP CONSTRAINT "ck_max_length_7f9f055183f7";
ALTER TABLE "public"."users" ALTER COLUMN "email" TYPE character varying(255) USING "email"::character varying(255);
ALTER TABLE "public"."post_tags" DROP CONSTRAINT "pk_post_tags";
ALTER TABLE "public"."post_tags" DROP CONSTRAINT "ck_max_length_eb8121184135";
ALTER TABLE "public"."post_tags" ALTER COLUMN "tag_name" TYPE character varying(64) USING "tag_name"::character varying(64);
CREATE INDEX "idx_post_tags_tag_post" ON "public"."post_tags" USING BTREE ("tag_name" ASC, "post_id" ASC);
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "pk_post_tags" PRIMARY KEY ("post_id", "tag_name");
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "fk_post_tags_tag_name" FOREIGN KEY ("tag_name") REFERENCES "public"."tags" ("name") ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE;
