// Code generated by golem. DO NOT EDIT.
// Golem generation digest: b2fd3d93a4f7cf41062cf1f6637d6ead0900e0071ba2c2087b5260ae1043d7e9
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v7

package p6metrics

import (
	golem "github.com/eleven-am/golem/go/golem"
)

type MetricFindOneRequest = golem.FindOneHookRequest[Metric]
type MetricFindOneResult = golem.FindOneHookResult[Metric]
type MetricFindFirstRequest = golem.FindFirstHookRequest[Metric]
type MetricFindFirstResult = golem.FindFirstHookResult[Metric]
type MetricFindManyRequest = golem.FindManyHookRequest[Metric]
type MetricFindManyResult = golem.FindManyHookResult[Metric]
type MetricCreateRequest = golem.CreateHookRequest[Metric]
type MetricCreateResult = golem.CreateHookResult[Metric]
type MetricUpdateRequest = golem.UpdateHookRequest[Metric]
type MetricUpdateResult = golem.UpdateHookResult[Metric]
type MetricDeleteRequest = golem.DeleteHookRequest[Metric]
type MetricDeleteResult = golem.DeleteHookResult[Metric]
type MetricUpdateManyRequest = golem.UpdateManyHookRequest[Metric]
type MetricUpdateManyResult = golem.UpdateManyHookResult[Metric]
type MetricDeleteManyRequest = golem.DeleteManyHookRequest[Metric]
type MetricDeleteManyResult = golem.DeleteManyHookResult[Metric]

type CategoryFindOneRequest = golem.FindOneHookRequest[Category]
type CategoryFindOneResult = golem.FindOneHookResult[Category]
type CategoryFindFirstRequest = golem.FindFirstHookRequest[Category]
type CategoryFindFirstResult = golem.FindFirstHookResult[Category]
type CategoryFindManyRequest = golem.FindManyHookRequest[Category]
type CategoryFindManyResult = golem.FindManyHookResult[Category]
type CategoryCreateRequest = golem.CreateHookRequest[Category]
type CategoryCreateResult = golem.CreateHookResult[Category]
type CategoryUpdateRequest = golem.UpdateHookRequest[Category]
type CategoryUpdateResult = golem.UpdateHookResult[Category]
type CategoryDeleteRequest = golem.DeleteHookRequest[Category]
type CategoryDeleteResult = golem.DeleteHookResult[Category]
type CategoryUpdateManyRequest = golem.UpdateManyHookRequest[Category]
type CategoryUpdateManyResult = golem.UpdateManyHookResult[Category]
type CategoryDeleteManyRequest = golem.DeleteManyHookRequest[Category]
type CategoryDeleteManyResult = golem.DeleteManyHookResult[Category]

func golemBuildMetricPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Metric]()
	Metric{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x41, 0xac, 0x9d, 0x78, 0xd2, 0x9f, 0x80, 0x2d, 0xb6, 0x6d, 0x1e, 0xef, 0xe9, 0xb3, 0x3a, 0x37})
}

func golemBuildCategoryPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Category]()
	Category{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0xc9, 0x9d, 0x5a, 0xe8, 0x2b, 0x33, 0xa9, 0x15, 0xa7, 0x52, 0xb4, 0xb8, 0xbf, 0x9d, 0x35, 0x9c})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, Metric](golem.ModelID{0x41, 0xac, 0x9d, 0x78, 0xd2, 0x9f, 0x80, 0x2d, 0xb6, 0x6d, 0x1e, 0xef, 0xe9, 0xb3, 0x3a, 0x37}, golemBuildMetricPolicy),
		golem.GeneratedPolicyBinding[Actor, Category](golem.ModelID{0xc9, 0x9d, 0x5a, 0xe8, 0x2b, 0x33, 0xa9, 0x15, 0xa7, 0x52, 0xb4, 0xb8, 0xbf, 0x9d, 0x35, 0x9c}, golemBuildCategoryPolicy),
	}
	hooks := []golem.HookBinding[Actor]{}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0xb2, 0xfd, 0x3d, 0x93, 0xa4, 0xf7, 0xcf, 0x41, 0x06, 0x2c, 0xf1, 0xf6, 0x63, 0x7d, 0x6e, 0xad, 0x09, 0x00, 0xe0, 0x07, 0x1b, 0xa2, 0xc2, 0x08, 0x7b, 0x52, 0x60, 0xae, 0x10, 0x43, 0xd7, 0xe9}, policies, hooks)
}
