export const DEMO_AGREEMENT_CASES = 580;

export const MAPPED_AGREEMENT_CASES = 278;

export const SQLITE_DEMO_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const SQLITE_MAPPED_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const POSTGRES_DEMO_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const POSTGRES_MAPPED_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const MAPPED_ANSWERS: Readonly<Record<string, string>> = {
  ["label/equals"]: '1,6',
  ["label/equals-empty"]: '2',
  ["label/equals-zero-text"]: '5',
  ["label/not"]: '2,3,4,5,7,8',
  ["label/lt-Zulu"]: '2,5',
  ["label/gte-Zulu"]: '1,3,4,6,7,8',
  ["label/lt-alpha"]: '2,4,5',
  ["label/equals-non-ascii"]: '7',
  ["label/lt-non-ascii"]: '1,2,3,4,5,6,8',
  ["label/gte-non-ascii"]: '7',
  ["label/in-non-ascii"]: '1,6,7',
  ["label/in"]: '1,2,6',
  ["label/notIn"]: '3,4,5,7,8',
  ["label/in-empty"]: '<none>',
  ["label/notIn-empty"]: '1,2,3,4,5,6,7,8',
  ["labelNull/equals-null"]: '2,5,7',
  ["labelNull/not-null"]: '1,3,4,6,8',
  ["labelNull/equals-empty"]: '3',
  ["labelNull/not-empty"]: '1,2,4,5,6,7,8',
  ["labelNull/lt-zulu"]: '1,3,6,8',
  ["labelNull/notIn"]: '2,3,4,5,6,7',
  ["amount/equals-zero"]: '1,5',
  ["amount/not-zero"]: '2,3,4,6,7,8',
  ["amount/gt-zero"]: '3,4,6,8',
  ["amount/lte-zero"]: '1,2,5,7',
  ["amount/multi"]: '1,3,5,6',
  ["amountNull/equals-null"]: '2,5',
  ["amountNull/lt-1"]: '1,4,6',
  ["amountNull/notIn"]: '2,4,5,7',
  ["big/equals-beyond"]: '4,7',
  ["big/gt-safe"]: '4,7',
  ["big/gte-safe"]: '3,4,7',
  ["big/lt-zero"]: '5',
  ["big/in-beyond"]: '4,5,7',
  ["big/notIn-beyond"]: '1,2,3,5,6,8',
  ["at/equals-D0"]: '1,4,7',
  ["at/lt-D2"]: '1,2,4,5,7,8',
  ["at/gte-D1"]: '2,3,5,6,8',
  ["flag/true"]: '1,3,5,7',
  ["flag/false"]: '2,4,6,8',
  ["flag/not-true"]: '2,4,6,8',
  ["flagNull/true"]: '1,5,8',
  ["flagNull/false"]: '3,6',
  ["flagNull/null"]: '2,4,7',
  ["flagNull/not-false"]: '1,2,4,5,7,8',
  ["flagNull/not-null"]: '1,3,5,6,8',
  ["state/equals-open"]: '1,4,7',
  ["state/not-open"]: '2,3,5,6,8',
  ["state/in"]: '1,3,4,6,7',
  ["state/notIn"]: '2,3,5,6,8',
  ["state/lt-ON_HOLD"]: '2,5,8',
  ["stateNull/null"]: '2,4,7',
  ["stateNull/not-null"]: '1,3,5,6,8',
  ["stateNull/equals-closed"]: '3,8',
  ["ownerId/null"]: '4,5,8',
  ["ownerId/not-null"]: '1,2,3,6,7',
  ["owner/is/kind-red"]: '1,6',
  ["owner/is/kind-empty"]: '2,7',
  ["owner/is/rank-gt-0"]: '1,6',
  ["owner/is/rankNull-null"]: '2,7',
  ["owner/is/rankNull-lt-1"]: '3',
  ["owner/is/empty"]: '1,2,3,6,7',
  ["owner/is/id-1"]: '1,6',
  ["owner/is/nested-NOT"]: '2,3,7',
  ["owner/is/kind-lt-Zulu"]: '2,7',
  ["parent/is/label-alpha"]: '2,3',
  ["parent/is/label-empty"]: '5',
  ["parent/is/id-1"]: '2,3',
  ["parent/is/big-gte-safe"]: '6',
  ["parent/is/flag-true"]: '2,3,6,8',
  ["parent/is/state-open"]: '2,3',
  ["parent/is/stateNull-null"]: '5',
  ["parent/is/labelNull-null"]: '5,8',
  ["parent/is/empty"]: '2,3,5,6,8',
  ["parent/is/parentId-null"]: '2,3',
  ["parent/is/nested-NOT"]: '5,6,8',
  ["parent/is/two-hop-label"]: '5,6',
  ["parent/is/two-hop-empty"]: '5,6,8',
  ["parent/is/two-hop-under-NOT"]: '2,3,8',
  ["parent/is/hop-then-owner"]: '2,3',
  ["owner/isNot/kind-red"]: '2,3,4,5,7,8',
  ["owner/isNot/rankNull-null"]: '1,3,4,5,6,8',
  ["owner/isNot/empty"]: '4,5,8',
  ["owner/is-null"]: '4,5,8',
  ["owner/isNot-null"]: '1,2,3,6,7',
  ["owner/bare-null"]: '4,5,8',
  ["parent/isNot/label-alpha"]: '1,4,5,6,7,8',
  ["parent/isNot/stateNull-null"]: '1,2,3,4,6,7,8',
  ["parent/is-null"]: '1,4,7',
  ["parent/isNot-null"]: '2,3,5,6,8',
  ["parent/bare-null"]: '1,4,7',
  ["parent/isNot/two-hop-label"]: '1,4,5,6,7',
  ["parent/isNot/hop-then-owner"]: '1,2,3,4,7',
  ["region/is/name"]: '1,6',
  ["region/is/name-empty"]: '<none>',
  ["region/is/code-upper"]: '2,7',
  ["region/is/code-lt-north"]: '2,7',
  ["region/is/empty"]: '1,2,6,7',
  ["region/regionCode-null"]: '3',
  ["chain/three-hop-label"]: '8',
  ["chain/three-hop-empty"]: '8',
  ["chain/four-hop-owner-kind"]: '8',
  ["chain/five-hop-region-name"]: '8',
  ["chain/four-hop-empty"]: '<none>',
  ["chain/three-hop-under-NOT"]: '2,3,5,6',
  ["chain/hop-then-owner-then-region"]: '2,3',
  ["alias/deep-chain-beside-shallow-hop"]: '8',
  ["alias/deep-chain-shadows-root-column"]: '8',
  ["alias/sibling-hops-same-table"]: '2,3',
  ["alias/sibling-hops-different-tables"]: '<none>',
  ["alias/hop-shadows-root-column"]: '3,5',
  ["alias/hop-and-root-same-column-name"]: '3',
  ["alias/three-hops-in-one-condition"]: '1,2,3,5,6',
  ["null-fk/OR-relation-then-scalar"]: '1,4,6,8',
  ["null-fk/OR-scalar-then-relation"]: '1,4,6,8',
  ["null-fk/OR-relation-then-null-scalar"]: '1,2,5,6,7',
  ["null-fk/OR-self-relation-then-scalar"]: '2,3,4,8',
  ["null-fk/OR-two-relations"]: '1,5,6',
  ["null-fk/NOT-relation"]: '2,3,4,5,7,8',
  ["null-fk/NOT-nested-is"]: '1,4,5,6,8',
  ["null-fk/NOT-of-OR-with-relation"]: '2,3,5,7',
  ["null-fk/relation-under-double-NOT"]: '1,6',
  ["null-fk/AND-relation-with-null-scalar"]: '1,6',
  ["null-fk/OR-two-hop-then-scalar"]: '4,5,6,8',
  ["null-fk/OR-hop-with-null-column-then-relation"]: '1,2,5,6',
  ["null-fk/OR-four-hop-then-scalar"]: '4,8',
  ["null-fk/OR-region-hop-then-scalar"]: '1,4,6,8',
  ["empty/OR-at-depth"]: '<none>',
  ["empty/OR-at-depth-two"]: '<none>',
  ["empty/NOT-of-OR-at-depth"]: '1,2,3,4,5,6,7,8',
  ["empty/OR-beside-a-branch"]: '1,5',
  ["empty/AND-of-empty-OR-and-true"]: '<none>',
  ["empty/OR-inside-relation"]: '<none>',
  ["empty/AND-inside-relation"]: '1,2,3,6,7',
  ["empty/NOT-empty-object"]: '<none>',
  ["empty/NOT-empty-array"]: '1,2,3,4,5,6,7,8',
  ["empty/AND-empty"]: '1,2,3,4,5,6,7,8',
  ["empty/OR-empty"]: '<none>',
  ["empty/object"]: '1,2,3,4,5,6,7,8',
  ["NOT(label/equals)"]: '2,3,4,5,7,8',
  ["NOT(label/equals-empty)"]: '1,3,4,5,6,7,8',
  ["NOT(label/equals-zero-text)"]: '1,2,3,4,6,7,8',
  ["NOT(label/not)"]: '1,6',
  ["NOT(label/lt-Zulu)"]: '1,3,4,6,7,8',
  ["NOT(label/gte-Zulu)"]: '2,5',
  ["NOT(label/lt-alpha)"]: '1,3,6,7,8',
  ["NOT(label/equals-non-ascii)"]: '1,2,3,4,5,6,8',
  ["NOT(label/lt-non-ascii)"]: '7',
  ["NOT(label/gte-non-ascii)"]: '1,2,3,4,5,6,8',
  ["NOT(label/in-non-ascii)"]: '2,3,4,5,8',
  ["NOT(label/in)"]: '3,4,5,7,8',
  ["NOT(label/notIn)"]: '1,2,6',
  ["NOT(label/in-empty)"]: '1,2,3,4,5,6,7,8',
  ["NOT(label/notIn-empty)"]: '<none>',
  ["NOT(labelNull/equals-null)"]: '1,3,4,6,8',
  ["NOT(labelNull/not-null)"]: '2,5,7',
  ["NOT(labelNull/equals-empty)"]: '1,2,4,5,6,7,8',
  ["NOT(labelNull/not-empty)"]: '3',
  ["NOT(labelNull/lt-zulu)"]: '2,4,5,7',
  ["NOT(labelNull/notIn)"]: '1,8',
  ["NOT(amount/equals-zero)"]: '2,3,4,6,7,8',
  ["NOT(amount/not-zero)"]: '1,5',
  ["NOT(amount/gt-zero)"]: '1,2,5,7',
  ["NOT(amount/lte-zero)"]: '3,4,6,8',
  ["NOT(amount/multi)"]: '2,4,7,8',
  ["NOT(amountNull/equals-null)"]: '1,3,4,6,7,8',
  ["NOT(amountNull/lt-1)"]: '2,3,5,7,8',
  ["NOT(amountNull/notIn)"]: '1,3,6,8',
  ["NOT(big/equals-beyond)"]: '1,2,3,5,6,8',
  ["NOT(big/gt-safe)"]: '1,2,3,5,6,8',
  ["NOT(big/gte-safe)"]: '1,2,5,6,8',
  ["NOT(big/lt-zero)"]: '1,2,3,4,6,7,8',
  ["NOT(big/in-beyond)"]: '1,2,3,6,8',
  ["NOT(big/notIn-beyond)"]: '4,7',
  ["NOT(at/equals-D0)"]: '2,3,5,6,8',
  ["NOT(at/lt-D2)"]: '3,6',
  ["NOT(at/gte-D1)"]: '1,4,7',
  ["NOT(flag/true)"]: '2,4,6,8',
  ["NOT(flag/false)"]: '1,3,5,7',
  ["NOT(flag/not-true)"]: '1,3,5,7',
  ["NOT(flagNull/true)"]: '2,3,4,6,7',
  ["NOT(flagNull/false)"]: '1,2,4,5,7,8',
  ["NOT(flagNull/null)"]: '1,3,5,6,8',
  ["NOT(flagNull/not-false)"]: '3,6',
  ["NOT(flagNull/not-null)"]: '2,4,7',
  ["NOT(state/equals-open)"]: '2,3,5,6,8',
  ["NOT(state/not-open)"]: '1,4,7',
  ["NOT(state/in)"]: '2,5,8',
  ["NOT(state/notIn)"]: '1,4,7',
  ["NOT(state/lt-ON_HOLD)"]: '1,3,4,6,7',
  ["NOT(stateNull/null)"]: '1,3,5,6,8',
  ["NOT(stateNull/not-null)"]: '2,4,7',
  ["NOT(stateNull/equals-closed)"]: '1,2,4,5,6,7',
  ["NOT(ownerId/null)"]: '1,2,3,6,7',
  ["NOT(ownerId/not-null)"]: '4,5,8',
  ["NOT(owner/is/kind-red)"]: '2,3,4,5,7,8',
  ["NOT(owner/is/kind-empty)"]: '1,3,4,5,6,8',
  ["NOT(owner/is/rank-gt-0)"]: '2,3,4,5,7,8',
  ["NOT(owner/is/rankNull-null)"]: '1,3,4,5,6,8',
  ["NOT(owner/is/rankNull-lt-1)"]: '1,2,4,5,6,7,8',
  ["NOT(owner/is/empty)"]: '4,5,8',
  ["NOT(owner/is/id-1)"]: '2,3,4,5,7,8',
  ["NOT(owner/is/nested-NOT)"]: '1,4,5,6,8',
  ["NOT(owner/is/kind-lt-Zulu)"]: '1,3,4,5,6,8',
  ["NOT(parent/is/label-alpha)"]: '1,4,5,6,7,8',
  ["NOT(parent/is/label-empty)"]: '1,2,3,4,6,7,8',
  ["NOT(parent/is/id-1)"]: '1,4,5,6,7,8',
  ["NOT(parent/is/big-gte-safe)"]: '1,2,3,4,5,7,8',
  ["NOT(parent/is/flag-true)"]: '1,4,5,7',
  ["NOT(parent/is/state-open)"]: '1,4,5,6,7,8',
  ["NOT(parent/is/stateNull-null)"]: '1,2,3,4,6,7,8',
  ["NOT(parent/is/labelNull-null)"]: '1,2,3,4,6,7',
  ["NOT(parent/is/empty)"]: '1,4,7',
  ["NOT(parent/is/parentId-null)"]: '1,4,5,6,7,8',
  ["NOT(parent/is/nested-NOT)"]: '1,2,3,4,7',
  ["NOT(parent/is/two-hop-label)"]: '1,2,3,4,7,8',
  ["NOT(parent/is/two-hop-empty)"]: '1,2,3,4,7',
  ["NOT(parent/is/two-hop-under-NOT)"]: '1,4,5,6,7',
  ["NOT(parent/is/hop-then-owner)"]: '1,4,5,6,7,8',
  ["NOT(owner/isNot/kind-red)"]: '1,6',
  ["NOT(owner/isNot/rankNull-null)"]: '2,7',
  ["NOT(owner/isNot/empty)"]: '1,2,3,6,7',
  ["NOT(owner/is-null)"]: '1,2,3,6,7',
  ["NOT(owner/isNot-null)"]: '4,5,8',
  ["NOT(owner/bare-null)"]: '1,2,3,6,7',
  ["NOT(parent/isNot/label-alpha)"]: '2,3',
  ["NOT(parent/isNot/stateNull-null)"]: '5',
  ["NOT(parent/is-null)"]: '2,3,5,6,8',
  ["NOT(parent/isNot-null)"]: '1,4,7',
  ["NOT(parent/bare-null)"]: '2,3,5,6,8',
  ["NOT(parent/isNot/two-hop-label)"]: '2,3,8',
  ["NOT(parent/isNot/hop-then-owner)"]: '5,6,8',
  ["NOT(region/is/name)"]: '2,3,4,5,7,8',
  ["NOT(region/is/name-empty)"]: '1,2,3,4,5,6,7,8',
  ["NOT(region/is/code-upper)"]: '1,3,4,5,6,8',
  ["NOT(region/is/code-lt-north)"]: '1,3,4,5,6,8',
  ["NOT(region/is/empty)"]: '3,4,5,8',
  ["NOT(region/regionCode-null)"]: '1,2,4,5,6,7,8',
  ["NOT(chain/three-hop-label)"]: '1,2,3,4,5,6,7',
  ["NOT(chain/three-hop-empty)"]: '1,2,3,4,5,6,7',
  ["NOT(chain/four-hop-owner-kind)"]: '1,2,3,4,5,6,7',
  ["NOT(chain/five-hop-region-name)"]: '1,2,3,4,5,6,7',
  ["NOT(chain/four-hop-empty)"]: '1,2,3,4,5,6,7,8',
  ["NOT(chain/three-hop-under-NOT)"]: '1,4,7,8',
  ["NOT(chain/hop-then-owner-then-region)"]: '1,4,5,6,7,8',
  ["NOT(alias/deep-chain-beside-shallow-hop)"]: '1,2,3,4,5,6,7',
  ["NOT(alias/deep-chain-shadows-root-column)"]: '1,2,3,4,5,6,7',
  ["NOT(alias/sibling-hops-same-table)"]: '1,4,5,6,7,8',
  ["NOT(alias/sibling-hops-different-tables)"]: '1,2,3,4,5,6,7,8',
  ["NOT(alias/hop-shadows-root-column)"]: '1,2,4,6,7,8',
  ["NOT(alias/hop-and-root-same-column-name)"]: '1,2,4,5,6,7,8',
  ["NOT(alias/three-hops-in-one-condition)"]: '4,7,8',
  ["NOT(null-fk/OR-relation-then-scalar)"]: '2,3,5,7',
  ["NOT(null-fk/OR-scalar-then-relation)"]: '2,3,5,7',
  ["NOT(null-fk/OR-relation-then-null-scalar)"]: '3,4,8',
  ["NOT(null-fk/OR-self-relation-then-scalar)"]: '1,5,6,7',
  ["NOT(null-fk/OR-two-relations)"]: '2,3,4,7,8',
  ["NOT(null-fk/NOT-relation)"]: '1,6',
  ["NOT(null-fk/NOT-nested-is)"]: '2,3,7',
  ["NOT(null-fk/NOT-of-OR-with-relation)"]: '1,4,6,8',
  ["NOT(null-fk/relation-under-double-NOT)"]: '2,3,4,5,7,8',
  ["NOT(null-fk/AND-relation-with-null-scalar)"]: '2,3,4,5,7,8',
  ["NOT(null-fk/OR-two-hop-then-scalar)"]: '1,2,3,7',
  ["NOT(null-fk/OR-hop-with-null-column-then-relation)"]: '3,4,7,8',
  ["NOT(null-fk/OR-four-hop-then-scalar)"]: '1,2,3,5,6,7',
  ["NOT(null-fk/OR-region-hop-then-scalar)"]: '2,3,5,7',
  ["NOT(empty/OR-at-depth)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/OR-at-depth-two)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/NOT-of-OR-at-depth)"]: '<none>',
  ["NOT(empty/OR-beside-a-branch)"]: '2,3,4,6,7,8',
  ["NOT(empty/AND-of-empty-OR-and-true)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/OR-inside-relation)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/AND-inside-relation)"]: '4,5,8',
  ["NOT(empty/NOT-empty-object)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/NOT-empty-array)"]: '<none>',
  ["NOT(empty/AND-empty)"]: '<none>',
  ["NOT(empty/OR-empty)"]: '1,2,3,4,5,6,7,8',
  ["NOT(empty/object)"]: '<none>',
};

export const AGREEMENT_STATEMENTS: Readonly<Record<string, string>> = {
  'mapped/empty-or-at-depth':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE ((1 = 0))',
  'mapped/nested-is-under-not':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE NOT ((EXISTS (SELECT 1 FROM "owner_rows" AS "t0_1" WHERE "t0_1"."owner_pk" = "t0"."owner_ref" AND (NOT (("t0_1"."kind_text" COLLATE BINARY IS ?))))))',
  'mapped/null-fk-or':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE ((EXISTS (SELECT 1 FROM "owner_rows" AS "t0_1" WHERE "t0_1"."owner_pk" = "t0"."owner_ref" AND (("t0_1"."kind_text" COLLATE BINARY IS ?)))) OR ("t0"."amount_value" IS ?))',
  'mapped/relation':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE (EXISTS (SELECT 1 FROM "owner_rows" AS "t0_1" WHERE "t0_1"."owner_pk" = "t0"."owner_ref" AND (("t0_1"."kind_text" COLLATE BINARY IS ?))))',
  'mapped/scalar':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE ("t0"."label_text" COLLATE BINARY IS ?)',
  'mapped/self-relation':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE (EXISTS (SELECT 1 FROM "tagged_rows" AS "t0_1" WHERE "t0_1"."row_pk" = "t0"."parent_ref" AND (("t0_1"."label_text" COLLATE BINARY IS ?))))',
  'mapped/sibling-hops':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE ((EXISTS (SELECT 1 FROM "tagged_rows" AS "t0_1" WHERE "t0_1"."row_pk" = "t0"."parent_ref" AND (("t0_1"."label_text" COLLATE BINARY IS ?)))) AND (EXISTS (SELECT 1 FROM "tagged_rows" AS "t0_1" WHERE "t0_1"."row_pk" = "t0"."parent_ref" AND (("t0_1"."amount_value" IS NOT NULL AND "t0_1"."amount_value" > ?)))))',
  'mapped/two-hop':
    'SELECT "t0"."row_pk" AS "id" FROM "tagged_rows" AS "t0" WHERE (EXISTS (SELECT 1 FROM "tagged_rows" AS "t0_1" WHERE "t0_1"."row_pk" = "t0"."parent_ref" AND ((EXISTS (SELECT 1 FROM "tagged_rows" AS "t0_2" WHERE "t0_2"."row_pk" = "t0_1"."parent_ref" AND (("t0_2"."label_text" COLLATE BINARY IS ?)))))))',
};

export const LIBRARY_AGREEMENT_CASES = 126;

export const GROUP_AGREEMENT_CASES = 6;

export const SQLITE_LIBRARY_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const POSTGRES_LIBRARY_DISAGREEMENTS: Readonly<Record<string, string>> = {};

export const LIBRARY_ANSWERS: Readonly<Record<string, string>> = {
  ["production/readable-by-u1"]: '1,4',
  ["production/readable-by-u2"]: '1',
  ["production/not-denied-to-u1"]: '1,3,4,5,6,7',
  ["production/not-denied-to-u2"]: '3,4,5,6,7',
  ["production/owns-every-video-u1"]: '2,4,5,6,7',
  ["production/owns-every-video-u2"]: '4,7',
  ["some/empty"]: '1,2,3,4,6',
  ["none/empty"]: '5,7',
  ["every/empty"]: '1,2,3,4,5,6,7',
  ["filter/empty"]: '1,2,3,4,5,6,7',
  ["some/label"]: '1',
  ["none/label"]: '2,3,4,5,6,7',
  ["every/label"]: '5,7',
  ["every/label-in"]: '1,5,6,7',
  ["some+none"]: '<none>',
  ["some+every+none"]: '1,3,6',
  ["videos/some/empty"]: '1,2,3,5,6',
  ["videos/none/empty"]: '4,7',
  ["videos/every/empty"]: '1,2,3,4,5,6,7',
  ["videos/every/storage-null"]: '3,4,7',
  ["videos/some/storage-null"]: '3',
  ["videos/every/storage-present"]: '1,2,4,5,6,7',
  ["null-leaf/every-access-allow"]: '3,5,6,7',
  ["null-leaf/every-access-not-deny"]: '3,4,5,6,7',
  ["null-leaf/every-access-null"]: '4,5,6,7',
  ["null-leaf/some-access-null"]: '1,4',
  ["null-leaf/none-access-null"]: '4,5,7',
  ["null-leaf/every-access-in"]: '2,3,5,6,7',
  ["null-leaf/every-access-notIn"]: '3,4,5,6,7',
  ["depth/three-many-many-one"]: '1,2',
  ["depth/four-many-many-one-many"]: '1,2,4',
  ["depth/four-every-at-the-end"]: '3,4',
  ["depth/four-none-at-the-end"]: '3,4,5,6,7',
  ["depth/five-back-through-membership"]: '1,2',
  ["depth/six-alternating"]: '1,2',
  ["depth/six-alternating-every"]: '<none>',
  ["depth/hop-back-to-the-root-model"]: '1',
  ["depth/NOT-inside-a-quantifier"]: '1,3,4,6',
  ["depth/quantifier-inside-a-NOT"]: '3,4,5,6,7',
  ["depth/sibling-quantifiers"]: '3',
  ["depth/some-storage-isNot-owner"]: '1,3',
  ["depth/every-storage-isNot-owner"]: '2,3,4,5,6,7',
  ["depth/none-storage-isNot-owner"]: '2,4,5,6,7',
  ["depth/some-storage-isNot-null"]: '1,2,5,6',
  ["depth/some-storage-is-null"]: '3',
  ["depth/some-storage-bare-null"]: '3',
  ["depth/quantifier-beside-a-to-one-chain"]: '1,3',
  ["string-fk/users-some-lower"]: '1,2',
  ["string-fk/slug-upper"]: '1',
  ["string-fk/slug-accented"]: '4',
  ["string-fk/slug-lt"]: '1',
  ["string-fk/slug-gte"]: '1,2,3,4',
  ["string-fk/members-lt"]: '1',
  ["string-fk/every-member-slug"]: '2,3,4,5,6,7',
  ["string-fk/usergroup-null"]: '1',
  ["string-fk/usergroup-not-null"]: '2,3,4,5,6,7',
  ["empty/OR-inside-some"]: '<none>',
  ["empty/OR-inside-none"]: '1,2,3,4,5,6,7',
  ["empty/OR-inside-every"]: '5,7',
  ["empty/AND-inside-every"]: '1,2,3,4,5,6,7',
  ["empty/object-inside-some"]: '1,2,3,4,6',
  ["empty/OR-two-levels-down"]: '<none>',
  ["empty/every-two-levels-down"]: '5,6,7',
  ["NOT(production/readable-by-u1)"]: '2,3,5,6,7',
  ["NOT(production/readable-by-u2)"]: '2,3,4,5,6,7',
  ["NOT(production/not-denied-to-u1)"]: '2',
  ["NOT(production/not-denied-to-u2)"]: '1,2',
  ["NOT(production/owns-every-video-u1)"]: '1,3',
  ["NOT(production/owns-every-video-u2)"]: '1,2,3,5,6',
  ["NOT(some/empty)"]: '5,7',
  ["NOT(none/empty)"]: '1,2,3,4,6',
  ["NOT(every/empty)"]: '<none>',
  ["NOT(filter/empty)"]: '<none>',
  ["NOT(some/label)"]: '2,3,4,5,6,7',
  ["NOT(none/label)"]: '1',
  ["NOT(every/label)"]: '1,2,3,4,6',
  ["NOT(every/label-in)"]: '2,3,4',
  ["NOT(some+none)"]: '1,2,3,4,5,6,7',
  ["NOT(some+every+none)"]: '2,4,5,7',
  ["NOT(videos/some/empty)"]: '4,7',
  ["NOT(videos/none/empty)"]: '1,2,3,5,6',
  ["NOT(videos/every/empty)"]: '<none>',
  ["NOT(videos/every/storage-null)"]: '1,2,5,6',
  ["NOT(videos/some/storage-null)"]: '1,2,4,5,6,7',
  ["NOT(videos/every/storage-present)"]: '3',
  ["NOT(null-leaf/every-access-allow)"]: '1,2,4',
  ["NOT(null-leaf/every-access-not-deny)"]: '1,2',
  ["NOT(null-leaf/every-access-null)"]: '1,2,3',
  ["NOT(null-leaf/some-access-null)"]: '2,3,5,6,7',
  ["NOT(null-leaf/none-access-null)"]: '1,2,3,6',
  ["NOT(null-leaf/every-access-in)"]: '1,4',
  ["NOT(null-leaf/every-access-notIn)"]: '1,2',
  ["NOT(depth/three-many-many-one)"]: '3,4,5,6,7',
  ["NOT(depth/four-many-many-one-many)"]: '3,5,6,7',
  ["NOT(depth/four-every-at-the-end)"]: '1,2,5,6,7',
  ["NOT(depth/four-none-at-the-end)"]: '1,2',
  ["NOT(depth/five-back-through-membership)"]: '3,4,5,6,7',
  ["NOT(depth/six-alternating)"]: '3,4,5,6,7',
  ["NOT(depth/six-alternating-every)"]: '1,2,3,4,5,6,7',
  ["NOT(depth/hop-back-to-the-root-model)"]: '2,3,4,5,6,7',
  ["NOT(depth/NOT-inside-a-quantifier)"]: '2,5,7',
  ["NOT(depth/quantifier-inside-a-NOT)"]: '1,2',
  ["NOT(depth/sibling-quantifiers)"]: '1,2,4,5,6,7',
  ["NOT(depth/some-storage-isNot-owner)"]: '2,4,5,6,7',
  ["NOT(depth/every-storage-isNot-owner)"]: '1',
  ["NOT(depth/none-storage-isNot-owner)"]: '1,3',
  ["NOT(depth/some-storage-isNot-null)"]: '3,4,7',
  ["NOT(depth/some-storage-is-null)"]: '1,2,4,5,6,7',
  ["NOT(depth/some-storage-bare-null)"]: '1,2,4,5,6,7',
  ["NOT(depth/quantifier-beside-a-to-one-chain)"]: '2,4,5,6,7',
  ["NOT(string-fk/users-some-lower)"]: '3,4,5,6,7',
  ["NOT(string-fk/slug-upper)"]: '2,3,4,5,6,7',
  ["NOT(string-fk/slug-accented)"]: '1,2,3,5,6,7',
  ["NOT(string-fk/slug-lt)"]: '2,3,4,5,6,7',
  ["NOT(string-fk/slug-gte)"]: '5,6,7',
  ["NOT(string-fk/members-lt)"]: '2,3,4,5,6,7',
  ["NOT(string-fk/every-member-slug)"]: '1',
  ["NOT(string-fk/usergroup-null)"]: '2,3,4,5,6,7',
  ["NOT(string-fk/usergroup-not-null)"]: '1',
  ["NOT(empty/OR-inside-some)"]: '1,2,3,4,5,6,7',
  ["NOT(empty/OR-inside-none)"]: '<none>',
  ["NOT(empty/OR-inside-every)"]: '1,2,3,4,6',
  ["NOT(empty/AND-inside-every)"]: '<none>',
  ["NOT(empty/object-inside-some)"]: '5,7',
  ["NOT(empty/OR-two-levels-down)"]: '1,2,3,4,5,6,7',
  ["NOT(empty/every-two-levels-down)"]: '1,2,3,4',
};

export const GROUP_ANSWERS: Readonly<Record<string, string>> = {
  ["group/every-access-allow"]: '4,6',
  ["group/every-access-deny"]: '3,6',
  ["group/some-access-allow"]: '1,2,4',
  ["group/none-access-allow"]: '3,5,6',
  ["group/every-access-null"]: '5,6',
  ["group/every-access-not-null"]: '1,3,4,6',
};

export const LIBRARY_STATEMENTS: Readonly<Record<string, string>> = {
  "production/readable-by-u1":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_2\" WHERE \"t0_2\".\"group_ref\" = \"t0_1\".\"group_pk\" AND ((NOT ((\"t0_2\".\"access_value\" COLLATE BINARY IS ?)) AND (EXISTS (SELECT 1 FROM \"usergroup_rows\" AS \"t0_3\" WHERE \"t0_3\".\"usergroup_slug\" COLLATE BINARY = \"t0_2\".\"usergroup_ref\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"membership_rows\" AS \"t0_4\" WHERE \"t0_4\".\"usergroup_ref\" COLLATE BINARY = \"t0_3\".\"usergroup_slug\" COLLATE BINARY AND ((\"t0_4\".\"user_ref\" COLLATE BINARY IS ?))))))))))))))",
  "production/not-denied-to-u1":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_2\" WHERE \"t0_2\".\"group_ref\" = \"t0_1\".\"group_pk\" AND (((\"t0_2\".\"access_value\" COLLATE BINARY IS ?) AND (EXISTS (SELECT 1 FROM \"usergroup_rows\" AS \"t0_3\" WHERE \"t0_3\".\"usergroup_slug\" COLLATE BINARY = \"t0_2\".\"usergroup_ref\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"membership_rows\" AS \"t0_4\" WHERE \"t0_4\".\"usergroup_ref\" COLLATE BINARY = \"t0_3\".\"usergroup_slug\" COLLATE BINARY AND ((\"t0_4\".\"user_ref\" COLLATE BINARY IS ?))))))))))))))",
  "production/owns-every-video-u1":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"video_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((((EXISTS (SELECT 1 FROM \"storage_rows\" AS \"t0_2\" WHERE \"t0_2\".\"storage_pk\" = \"t0_1\".\"storage_ref\" AND ((\"t0_2\".\"user_ref\" COLLATE BINARY IS ?))))) IS NOT TRUE))))",
  "depth/six-alternating":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_2\" WHERE \"t0_2\".\"group_ref\" = \"t0_1\".\"group_pk\" AND ((EXISTS (SELECT 1 FROM \"usergroup_rows\" AS \"t0_3\" WHERE \"t0_3\".\"usergroup_slug\" COLLATE BINARY = \"t0_2\".\"usergroup_ref\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"membership_rows\" AS \"t0_4\" WHERE \"t0_4\".\"usergroup_ref\" COLLATE BINARY = \"t0_3\".\"usergroup_slug\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"usergroup_rows\" AS \"t0_5\" WHERE \"t0_5\".\"usergroup_slug\" COLLATE BINARY = \"t0_4\".\"usergroup_ref\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_6\" WHERE \"t0_6\".\"usergroup_ref\" COLLATE BINARY = \"t0_5\".\"usergroup_slug\" COLLATE BINARY AND ((\"t0_6\".\"access_value\" COLLATE BINARY IS ?)))))))))))))))))))",
  "some/empty":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((1 = 1))))",
  "every/empty":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((((1 = 1)) IS NOT TRUE))))",
  "none/empty":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((1 = 1))))",
  "empty/OR-inside-every":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((((1 = 0)) IS NOT TRUE))))",
  "null-leaf/every-access-allow":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE NOT (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND (((NOT (EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_2\" WHERE \"t0_2\".\"group_ref\" = \"t0_1\".\"group_pk\" AND ((((\"t0_2\".\"access_value\" COLLATE BINARY IS ?)) IS NOT TRUE))))) IS NOT TRUE))))",
  "string-fk/users-some-lower":
    "SELECT \"t0\".\"media_pk\" AS \"id\" FROM \"media_rows\" AS \"t0\" WHERE (EXISTS (SELECT 1 FROM \"group_rows\" AS \"t0_1\" WHERE \"t0_1\".\"media_ref\" = \"t0\".\"media_pk\" AND ((EXISTS (SELECT 1 FROM \"policy_rows\" AS \"t0_2\" WHERE \"t0_2\".\"group_ref\" = \"t0_1\".\"group_pk\" AND ((EXISTS (SELECT 1 FROM \"usergroup_rows\" AS \"t0_3\" WHERE \"t0_3\".\"usergroup_slug\" COLLATE BINARY = \"t0_2\".\"usergroup_ref\" COLLATE BINARY AND ((EXISTS (SELECT 1 FROM \"membership_rows\" AS \"t0_4\" WHERE \"t0_4\".\"usergroup_ref\" COLLATE BINARY = \"t0_3\".\"usergroup_slug\" COLLATE BINARY AND ((\"t0_4\".\"user_ref\" COLLATE BINARY IS ?)))))))))))))",
};
