// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p8-graphql-abi-v4; generation 67e09dc14051301561faf0abeb051cae667ef0a297e1041961ab9de8acf86636; generator p1-v1; template p8-go-abi-v6.
package golemgqlgen

// THIS CODE WILL BE UPDATED WITH SCHEMA CHANGES. PREVIOUS IMPLEMENTATION FOR SCHEMA CHANGES WILL BE KEPT IN THE COMMENT SECTION. IMPLEMENTATION FOR UNCHANGED SCHEMA WILL BE KEPT.

import (
	"context"

	graphql1 "github.com/eleven-am/golem/go/graphql"
)

type Resolver struct{}

func (r *batchPayloadResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *commentResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentResolver) PostID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentResolver) AuthorID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentResolver) ParentID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentResolver) Body(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *commentResolver) CreatedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentResolver) Post(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *commentResolver) Author(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *commentResolver) Parent(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *commentResolver) Replies(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput, orderBy []*CommentOrderByInput, cursor *CommentWhereUniqueInput, distinct []CommentScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *commentResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *commentCountOutputResolver) Replies(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *commentEventResolver) EventID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentEventResolver) CausationID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentEventResolver) TransactionOrdinal(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *commentEventResolver) RecordedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentEventResolver) Type(ctx context.Context, obj graphql1.PreparedObject) (GolemEventType, error) {
	return graphql1.ResolvePreparedField[GolemEventType](ctx, obj)

}

func (r *commentEventResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *commentEventResolver) Entity(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *mutationResolver) CreateComment(ctx context.Context, data CommentCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateComment(ctx context.Context, where CommentWhereUniqueInput, data CommentUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpsertComment(ctx context.Context, where CommentWhereUniqueInput, create CommentCreateInput, update CommentUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteComment(ctx context.Context, where CommentWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateManyComments(ctx context.Context, where CommentWhereInput, data CommentUpdateManyInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteManyComments(ctx context.Context, where CommentWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) CreatePost(ctx context.Context, data PostCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdatePost(ctx context.Context, where PostWhereUniqueInput, data PostUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpsertPost(ctx context.Context, where PostWhereUniqueInput, create PostCreateInput, update PostUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeletePost(ctx context.Context, where PostWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateManyPosts(ctx context.Context, where PostWhereInput, data PostUpdateManyInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteManyPosts(ctx context.Context, where PostWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) CreatePostTag(ctx context.Context, data PostTagCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdatePostTag(ctx context.Context, where PostTagWhereUniqueInput, data PostTagUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpsertPostTag(ctx context.Context, where PostTagWhereUniqueInput, create PostTagCreateInput, update PostTagUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeletePostTag(ctx context.Context, where PostTagWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateManyPostTags(ctx context.Context, where PostTagWhereInput, data PostTagUpdateManyInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteManyPostTags(ctx context.Context, where PostTagWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) CreateTag(ctx context.Context, data TagCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateTag(ctx context.Context, where TagWhereUniqueInput, data TagUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpsertTag(ctx context.Context, where TagWhereUniqueInput, create TagCreateInput, update TagUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteTag(ctx context.Context, where TagWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateManyTags(ctx context.Context, where TagWhereInput, data TagUpdateManyInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteManyTags(ctx context.Context, where TagWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) CreateUser(ctx context.Context, data UserCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateUser(ctx context.Context, where UserWhereUniqueInput, data UserUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpsertUser(ctx context.Context, where UserWhereUniqueInput, create UserCreateInput, update UserUpdateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteUser(ctx context.Context, where UserWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) UpdateManyUsers(ctx context.Context, where UserWhereInput, data UserUpdateManyInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) DeleteManyUsers(ctx context.Context, where UserWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) PublishPost(ctx context.Context, fail bool, postID any) (any, error) {
	return graphql1.ResolvePreparedRoot[any](ctx)

}

func (r *postResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) AuthorID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) Title(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *postResolver) Body(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *postResolver) Published(ctx context.Context, obj graphql1.PreparedObject) (*bool, error) {
	return graphql1.ResolvePreparedField[*bool](ctx, obj)

}

func (r *postResolver) Reactions(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *postResolver) Priority(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *postResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) Momentum(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) LiveDate(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) LiveTime(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) Metadata(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) Visibility(ctx context.Context, obj graphql1.PreparedObject) (*Visibility, error) {
	return graphql1.ResolvePreparedField[*Visibility](ctx, obj)

}

func (r *postResolver) Topics(ctx context.Context, obj graphql1.PreparedObject) ([]string, error) {
	return graphql1.ResolvePreparedField[[]string](ctx, obj)

}

func (r *postResolver) CreatedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) UpdatedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postResolver) Author(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postResolver) Comments(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput, orderBy []*CommentOrderByInput, cursor *CommentWhereUniqueInput, distinct []CommentScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *postResolver) PostTags(ctx context.Context, obj graphql1.PreparedObject, where *PostTagWhereInput, orderBy []*PostTagOrderByInput, cursor *PostTagWhereUniqueInput, distinct []PostTagScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *postResolver) DisplayCode(ctx context.Context, obj graphql1.PreparedObject, prefix string) (string, error) {
	return graphql1.ResolvePreparedField[string](ctx, obj)

}

func (r *postResolver) Excerpt(ctx context.Context, obj graphql1.PreparedObject, maximum int) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *postResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAggregateResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postAggregateResolver) CountFields(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAggregateResolver) Sum(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAggregateResolver) Avg(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAggregateResolver) Min(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAggregateResolver) Max(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postAvgAggregateResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postAvgAggregateResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postAvgAggregateResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postCountAggregateResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postCountAggregateResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postCountAggregateResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postCountAggregateResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postCountOutputResolver) Comments(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *postCountOutputResolver) PostTags(ctx context.Context, obj graphql1.PreparedObject, where *PostTagWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *postEventResolver) EventID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postEventResolver) CausationID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postEventResolver) TransactionOrdinal(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *postEventResolver) RecordedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postEventResolver) Type(ctx context.Context, obj graphql1.PreparedObject) (GolemEventType, error) {
	return graphql1.ResolvePreparedField[GolemEventType](ctx, obj)

}

func (r *postEventResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postEventResolver) Entity(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Key(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postGroupResolver) CountFields(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Sum(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Avg(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Min(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupResolver) Max(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postGroupKeyResolver) AuthorID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postGroupKeyResolver) Published(ctx context.Context, obj graphql1.PreparedObject) (bool, error) {
	return graphql1.ResolvePreparedField[bool](ctx, obj)

}

func (r *postGroupKeyResolver) Visibility(ctx context.Context, obj graphql1.PreparedObject) (Visibility, error) {
	return graphql1.ResolvePreparedField[Visibility](ctx, obj)

}

func (r *postMaxAggregateResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postMaxAggregateResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postMaxAggregateResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postMinAggregateResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postMinAggregateResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postMinAggregateResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postRelationGroupResolver) Key(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postRelationGroupResolver) CountFields(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupResolver) Sum(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupResolver) Avg(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupResolver) Min(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupResolver) Max(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postRelationGroupKeyResolver) AuthorHandle(ctx context.Context, obj graphql1.PreparedObject) (string, error) {
	return graphql1.ResolvePreparedField[string](ctx, obj)

}

func (r *postRelationGroupKeyResolver) AuthorID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postRelationGroupKeyResolver) Published(ctx context.Context, obj graphql1.PreparedObject) (bool, error) {
	return graphql1.ResolvePreparedField[bool](ctx, obj)

}

func (r *postRelationGroupKeyResolver) Visibility(ctx context.Context, obj graphql1.PreparedObject) (Visibility, error) {
	return graphql1.ResolvePreparedField[Visibility](ctx, obj)

}

func (r *postSumAggregateResolver) Budget(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postSumAggregateResolver) Rating(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *postSumAggregateResolver) Views(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postTagResolver) PostID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *postTagResolver) TagName(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *postTagResolver) Post(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *postTagResolver) Tag(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *queryResolver) Comment(ctx context.Context, where CommentWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Comments(ctx context.Context, where *CommentWhereInput, orderBy []*CommentOrderByInput, cursor *CommentWhereUniqueInput, distinct []CommentScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Post(ctx context.Context, where PostWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Posts(ctx context.Context, where *PostWhereInput, orderBy []*PostOrderByInput, cursor *PostWhereUniqueInput, distinct []PostScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) AggregatePosts(ctx context.Context, where *PostWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) GroupByPosts(ctx context.Context, by []PostGroupField, where *PostWhereInput, having *PostGroupHavingInput, orderBy []*PostGroupOrderByInput, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) RelationGroupByPosts(ctx context.Context, by []PostRelationGroupField, where *PostWhereInput, having *PostRelationGroupHavingInput, orderBy []*PostRelationGroupOrderByInput, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) PostTag(ctx context.Context, where PostTagWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) PostTags(ctx context.Context, where *PostTagWhereInput, orderBy []*PostTagOrderByInput, cursor *PostTagWhereUniqueInput, distinct []PostTagScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Tag(ctx context.Context, where TagWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Tags(ctx context.Context, where *TagWhereInput, orderBy []*TagOrderByInput, cursor *TagWhereUniqueInput, distinct []TagScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) User(ctx context.Context, where UserWhereUniqueInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) Users(ctx context.Context, where *UserWhereInput, orderBy []*UserOrderByInput, cursor *UserWhereUniqueInput, distinct []UserScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *queryResolver) SearchPosts(ctx context.Context, take int, where PostWhereInput) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *subscriptionResolver) CommentEvents(ctx context.Context, where *CommentWhereInput) (<-chan graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedSubscriptionRoot[graphql1.PreparedObject](ctx)

}

func (r *subscriptionResolver) PostEvents(ctx context.Context, where *PostWhereInput) (<-chan graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedSubscriptionRoot[graphql1.PreparedObject](ctx)

}

func (r *tagResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *tagResolver) Name(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *tagResolver) PostTags(ctx context.Context, obj graphql1.PreparedObject, where *PostTagWhereInput, orderBy []*PostTagOrderByInput, cursor *PostTagWhereUniqueInput, distinct []PostTagScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *tagResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *tagCountOutputResolver) PostTags(ctx context.Context, obj graphql1.PreparedObject, where *PostTagWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *userResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *userResolver) Handle(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *userResolver) Email(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *userResolver) CreatedAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *userResolver) Posts(ctx context.Context, obj graphql1.PreparedObject, where *PostWhereInput, orderBy []*PostOrderByInput, cursor *PostWhereUniqueInput, distinct []PostScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *userResolver) Comments(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput, orderBy []*CommentOrderByInput, cursor *CommentWhereUniqueInput, distinct []CommentScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *userResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *userCountOutputResolver) Posts(ctx context.Context, obj graphql1.PreparedObject, where *PostWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *userCountOutputResolver) Comments(ctx context.Context, obj graphql1.PreparedObject, where *CommentWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *Resolver) BatchPayload() BatchPayloadResolver { return &batchPayloadResolver{r} }

func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

func (r *Resolver) CommentCountOutput() CommentCountOutputResolver {
	return &commentCountOutputResolver{r}
}

func (r *Resolver) CommentEvent() CommentEventResolver { return &commentEventResolver{r} }

func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Post() PostResolver { return &postResolver{r} }

func (r *Resolver) PostAggregate() PostAggregateResolver { return &postAggregateResolver{r} }

func (r *Resolver) PostAvgAggregate() PostAvgAggregateResolver { return &postAvgAggregateResolver{r} }

func (r *Resolver) PostCountAggregate() PostCountAggregateResolver {
	return &postCountAggregateResolver{r}
}

func (r *Resolver) PostCountOutput() PostCountOutputResolver { return &postCountOutputResolver{r} }

func (r *Resolver) PostEvent() PostEventResolver { return &postEventResolver{r} }

func (r *Resolver) PostGroup() PostGroupResolver { return &postGroupResolver{r} }

func (r *Resolver) PostGroupKey() PostGroupKeyResolver { return &postGroupKeyResolver{r} }

func (r *Resolver) PostMaxAggregate() PostMaxAggregateResolver { return &postMaxAggregateResolver{r} }

func (r *Resolver) PostMinAggregate() PostMinAggregateResolver { return &postMinAggregateResolver{r} }

func (r *Resolver) PostRelationGroup() PostRelationGroupResolver {
	return &postRelationGroupResolver{r}
}

func (r *Resolver) PostRelationGroupKey() PostRelationGroupKeyResolver {
	return &postRelationGroupKeyResolver{r}
}

func (r *Resolver) PostSumAggregate() PostSumAggregateResolver { return &postSumAggregateResolver{r} }

func (r *Resolver) PostTag() PostTagResolver { return &postTagResolver{r} }

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

func (r *Resolver) TagCountOutput() TagCountOutputResolver { return &tagCountOutputResolver{r} }

func (r *Resolver) User() UserResolver { return &userResolver{r} }

func (r *Resolver) UserCountOutput() UserCountOutputResolver { return &userCountOutputResolver{r} }

type batchPayloadResolver struct{ *Resolver }
type commentResolver struct{ *Resolver }
type commentCountOutputResolver struct{ *Resolver }
type commentEventResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type postAggregateResolver struct{ *Resolver }
type postAvgAggregateResolver struct{ *Resolver }
type postCountAggregateResolver struct{ *Resolver }
type postCountOutputResolver struct{ *Resolver }
type postEventResolver struct{ *Resolver }
type postGroupResolver struct{ *Resolver }
type postGroupKeyResolver struct{ *Resolver }
type postMaxAggregateResolver struct{ *Resolver }
type postMinAggregateResolver struct{ *Resolver }
type postRelationGroupResolver struct{ *Resolver }
type postRelationGroupKeyResolver struct{ *Resolver }
type postSumAggregateResolver struct{ *Resolver }
type postTagResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
type tagCountOutputResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type userCountOutputResolver struct{ *Resolver }
