// Code generated by golem. DO NOT EDIT.
// Golem generation digest: c472605678c26793aac520090116c841a2542253673c98d4763ecc6f6edf61fb
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v7

package p10operations

import (
	context "context"
	golem "github.com/eleven-am/golem/go/golem"
)

type TeamFindOneRequest = golem.FindOneHookRequest[Team]
type TeamFindOneResult = golem.FindOneHookResult[Team]
type TeamFindFirstRequest = golem.FindFirstHookRequest[Team]
type TeamFindFirstResult = golem.FindFirstHookResult[Team]
type TeamFindManyRequest = golem.FindManyHookRequest[Team]
type TeamFindManyResult = golem.FindManyHookResult[Team]
type TeamCreateRequest = golem.CreateHookRequest[Team]
type TeamCreateResult = golem.CreateHookResult[Team]
type TeamUpdateRequest = golem.UpdateHookRequest[Team]
type TeamUpdateResult = golem.UpdateHookResult[Team]
type TeamDeleteRequest = golem.DeleteHookRequest[Team]
type TeamDeleteResult = golem.DeleteHookResult[Team]
type TeamUpdateManyRequest = golem.UpdateManyHookRequest[Team]
type TeamUpdateManyResult = golem.UpdateManyHookResult[Team]
type TeamDeleteManyRequest = golem.DeleteManyHookRequest[Team]
type TeamDeleteManyResult = golem.DeleteManyHookResult[Team]

type InviteFindOneRequest = golem.FindOneHookRequest[Invite]
type InviteFindOneResult = golem.FindOneHookResult[Invite]
type InviteFindFirstRequest = golem.FindFirstHookRequest[Invite]
type InviteFindFirstResult = golem.FindFirstHookResult[Invite]
type InviteFindManyRequest = golem.FindManyHookRequest[Invite]
type InviteFindManyResult = golem.FindManyHookResult[Invite]
type InviteCreateRequest = golem.CreateHookRequest[Invite]
type InviteCreateResult = golem.CreateHookResult[Invite]
type InviteUpdateRequest = golem.UpdateHookRequest[Invite]
type InviteUpdateResult = golem.UpdateHookResult[Invite]
type InviteDeleteRequest = golem.DeleteHookRequest[Invite]
type InviteDeleteResult = golem.DeleteHookResult[Invite]
type InviteUpdateManyRequest = golem.UpdateManyHookRequest[Invite]
type InviteUpdateManyResult = golem.UpdateManyHookResult[Invite]
type InviteDeleteManyRequest = golem.DeleteManyHookRequest[Invite]
type InviteDeleteManyResult = golem.DeleteManyHookResult[Invite]

func golemBuildTeamPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Team]()
	Team{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x3d, 0xc9, 0xf4, 0xfb, 0x15, 0xff, 0x37, 0xeb, 0xad, 0x4c, 0x00, 0xfa, 0xa1, 0xa4, 0x18, 0x95})
}

func golemInvokeInviteBeforeCreate(ctx context.Context, request *InviteCreateRequest) error {
	return Invite{}.BeforeCreate(ctx, request)
}

func golemInvokeInviteAfterCreate(ctx context.Context, result InviteCreateResult) error {
	return Invite{}.AfterCreate(ctx, result)
}

func golemInvokeInviteAfterCommitCreate(ctx context.Context, result InviteCreateResult) error {
	return Invite{}.AfterCommitCreate(ctx, result)
}

func golemBuildInvitePolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Invite]()
	Invite{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, Team](golem.ModelID{0x3d, 0xc9, 0xf4, 0xfb, 0x15, 0xff, 0x37, 0xeb, 0xad, 0x4c, 0x00, 0xfa, 0xa1, 0xa4, 0x18, 0x95}, golemBuildTeamPolicy),
		golem.GeneratedPolicyBinding[Actor, Invite](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golemBuildInvitePolicy),
	}
	hooks := []golem.HookBinding[Actor]{
		golem.GeneratedBeforeHookBinding[Actor, Invite, InviteCreateRequest](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteBeforeCreate),
		golem.GeneratedAfterHookBinding[Actor, Invite, InviteCreateResult](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteAfterCreate),
		golem.GeneratedAfterCommitHookBinding[Actor, Invite, InviteCreateResult](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteAfterCommitCreate),
	}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0xc4, 0x72, 0x60, 0x56, 0x78, 0xc2, 0x67, 0x93, 0xaa, 0xc5, 0x20, 0x09, 0x01, 0x16, 0xc8, 0x41, 0xa2, 0x54, 0x22, 0x53, 0x67, 0x3c, 0x98, 0xd4, 0x76, 0x3e, 0xcc, 0x6f, 0x6e, 0xdf, 0x61, 0xfb}, policies, hooks)
}
