// Code generated by golem. DO NOT EDIT.
// Golem generation digest: 0c4924e145877361fef782a4b25d2628ec76cfb4afe77d9a0bbb233dfb6b6121
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v7

package p10operations

import (
	context "context"
	golem "github.com/eleven-am/golem/go/golem"
)

type TeamFindOneRequest = golem.FindOneHookRequest[Team]
type TeamFindOneResult = golem.FindOneHookResult[Team]
type TeamFindFirstRequest = golem.FindFirstHookRequest[Team]
type TeamFindFirstResult = golem.FindFirstHookResult[Team]
type TeamFindManyRequest = golem.FindManyHookRequest[Team]
type TeamFindManyResult = golem.FindManyHookResult[Team]
type TeamCreateRequest = golem.CreateHookRequest[Team]
type TeamCreateResult = golem.CreateHookResult[Team]
type TeamUpdateRequest = golem.UpdateHookRequest[Team]
type TeamUpdateResult = golem.UpdateHookResult[Team]
type TeamDeleteRequest = golem.DeleteHookRequest[Team]
type TeamDeleteResult = golem.DeleteHookResult[Team]
type TeamUpdateManyRequest = golem.UpdateManyHookRequest[Team]
type TeamUpdateManyResult = golem.UpdateManyHookResult[Team]
type TeamDeleteManyRequest = golem.DeleteManyHookRequest[Team]
type TeamDeleteManyResult = golem.DeleteManyHookResult[Team]

type InviteFindOneRequest = golem.FindOneHookRequest[Invite]
type InviteFindOneResult = golem.FindOneHookResult[Invite]
type InviteFindFirstRequest = golem.FindFirstHookRequest[Invite]
type InviteFindFirstResult = golem.FindFirstHookResult[Invite]
type InviteFindManyRequest = golem.FindManyHookRequest[Invite]
type InviteFindManyResult = golem.FindManyHookResult[Invite]
type InviteCreateRequest = golem.CreateHookRequest[Invite]
type InviteCreateResult = golem.CreateHookResult[Invite]
type InviteUpdateRequest = golem.UpdateHookRequest[Invite]
type InviteUpdateResult = golem.UpdateHookResult[Invite]
type InviteDeleteRequest = golem.DeleteHookRequest[Invite]
type InviteDeleteResult = golem.DeleteHookResult[Invite]
type InviteUpdateManyRequest = golem.UpdateManyHookRequest[Invite]
type InviteUpdateManyResult = golem.UpdateManyHookResult[Invite]
type InviteDeleteManyRequest = golem.DeleteManyHookRequest[Invite]
type InviteDeleteManyResult = golem.DeleteManyHookResult[Invite]

func golemInvokeTeamAfterCreate(ctx context.Context, result TeamCreateResult) error {
	return Team{}.AfterCreate(ctx, result)
}

func golemBuildTeamPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Team]()
	Team{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x3d, 0xc9, 0xf4, 0xfb, 0x15, 0xff, 0x37, 0xeb, 0xad, 0x4c, 0x00, 0xfa, 0xa1, 0xa4, 0x18, 0x95})
}

func golemInvokeInviteBeforeCreate(ctx context.Context, request *InviteCreateRequest) error {
	return Invite{}.BeforeCreate(ctx, request)
}

func golemInvokeInviteAfterCreate(ctx context.Context, result InviteCreateResult) error {
	return Invite{}.AfterCreate(ctx, result)
}

func golemInvokeInviteAfterCommitCreate(ctx context.Context, result InviteCreateResult) error {
	return Invite{}.AfterCommitCreate(ctx, result)
}

func golemInvokeInviteAfterUpdateMany(ctx context.Context, result InviteUpdateManyResult) error {
	return Invite{}.AfterUpdateMany(ctx, result)
}

func golemBuildInvitePolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[Invite]()
	Invite{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, Team](golem.ModelID{0x3d, 0xc9, 0xf4, 0xfb, 0x15, 0xff, 0x37, 0xeb, 0xad, 0x4c, 0x00, 0xfa, 0xa1, 0xa4, 0x18, 0x95}, golemBuildTeamPolicy),
		golem.GeneratedPolicyBinding[Actor, Invite](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golemBuildInvitePolicy),
	}
	hooks := []golem.HookBinding[Actor]{
		golem.GeneratedAfterHookBinding[Actor, Team, TeamCreateResult](golem.ModelID{0x3d, 0xc9, 0xf4, 0xfb, 0x15, 0xff, 0x37, 0xeb, 0xad, 0x4c, 0x00, 0xfa, 0xa1, 0xa4, 0x18, 0x95}, golem.HookCreate, golemInvokeTeamAfterCreate),
		golem.GeneratedBeforeHookBinding[Actor, Invite, InviteCreateRequest](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteBeforeCreate),
		golem.GeneratedAfterHookBinding[Actor, Invite, InviteCreateResult](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteAfterCreate),
		golem.GeneratedAfterCommitHookBinding[Actor, Invite, InviteCreateResult](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookCreate, golemInvokeInviteAfterCommitCreate),
		golem.GeneratedAfterHookBinding[Actor, Invite, InviteUpdateManyResult](golem.ModelID{0x56, 0x41, 0x75, 0xa9, 0x22, 0xa4, 0xb6, 0x93, 0x73, 0x61, 0xd8, 0x96, 0x04, 0x48, 0xc4, 0xe4}, golem.HookUpdateMany, golemInvokeInviteAfterUpdateMany),
	}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0x0c, 0x49, 0x24, 0xe1, 0x45, 0x87, 0x73, 0x61, 0xfe, 0xf7, 0x82, 0xa4, 0xb2, 0x5d, 0x26, 0x28, 0xec, 0x76, 0xcf, 0xb4, 0xaf, 0xe7, 0x7d, 0x9a, 0x0b, 0xbb, 0x23, 0x3d, 0xfb, 0x6b, 0x61, 0x21}, policies, hooks)
}
