package p7verify

import "github.com/eleven-am/golem/go/internal/mutationverify"

// MutationCatalog is the complete P7 named-mutation inventory from
// P7-EVIDENCE.md. Every entry is executable: it names an exact production
// patch and at least one exact test. The runner treats a missing patch site,
// a provider skip, a compile-only failure, or a surviving test as failure.
func MutationCatalog() []mutationverify.Mutation {
	pg := []string{CrashPostgresDSN, CrashPostgresLinguisticDSN}
	m := func(label, summary, path, before, after, pkg, test string) mutationverify.Mutation {
		return mutationverify.Mutation{Label: label, Summary: summary,
			Patches: []mutationverify.Patch{{Path: path, Before: before, After: after}},
			Tests:   []mutationverify.Test{{Package: pkg, Name: test}}}
	}
	providerMutation := func(label, summary, path, before, after, pkg, test string) mutationverify.Mutation {
		item := m(label, summary, path, before, after, pkg, test)
		item.Tests[0].Env = pg
		return item
	}
	return []mutationverify.Mutation{
		m("MUTATE_FACT_ON_CLAIM", "write operational claim data into an immutable fact column",
			"internal/provider/sqlite/event_delivery.go",
			"\tif err := sqliteMaterializeMissing(ctx, connection, options.Groups); err != nil {\n",
			"\tif _, mutantErr := connection.ExecContext(ctx, `UPDATE \"main\".\"_golem_outbox\" SET \"metadata\"=\"metadata\"||x'00'`); mutantErr != nil { return nil, mutantErr }\n\tif err := sqliteMaterializeMissing(ctx, connection, options.Groups); err != nil {\n",
			"./internal/provider/sqlite", "TestP7SQLiteDeliveryProviderCommonHarness"),
		m("ACK_BEFORE_TRANSPORT_SUCCESS", "acknowledge the lease before transport acceptance",
			"internal/event/outbox/publisher.go",
			"\tstarted := time.Now()\n\tpublishErr, owned := publisher.publishWithRenewal(ctx, lease, batch)\n",
			"\t_, _ = publisher.coordinator.Acknowledge(ctx, lease.Delivery.CausationID, lease.Delivery.LeaseToken)\n\tstarted := time.Now()\n\tpublishErr, owned := publisher.publishWithRenewal(ctx, lease, batch)\n",
			"./internal/event/outbox", "TestP7PublisherReusesIdenticalCausalBatchAfterAmbiguousAcceptanceWindows"),
		m("NEW_EVENT_ID_ON_RETRY", "derive a fresh random event identity on each publication attempt",
			"internal/event/outbox/publisher.go",
			"\t\tnotice, noticeErr := eventvalue.NewRoutedNotice(envelope.EventID(), envelope.GenerationDigest(), envelope.ResolvedEventSchemaDigest(), envelope.ModelID(), envelope.Action(), envelope.CausationID(), envelope.TransactionOrdinal(), envelope.Encoded())\n",
			"\t\trandomText, _ := eventprovider.NewLeaseToken()\n\t\trandomID, _ := parseUUID[golem.EventID](randomText)\n\t\tnotice, noticeErr := eventvalue.NewRoutedNotice(randomID, envelope.GenerationDigest(), envelope.ResolvedEventSchemaDigest(), envelope.ModelID(), envelope.Action(), envelope.CausationID(), envelope.TransactionOrdinal(), envelope.Encoded())\n",
			"./internal/event/outbox", "TestP7PublisherReusesIdenticalCausalBatchAfterAmbiguousAcceptanceWindows"),
		m("ACK_FOREIGN_OR_EXPIRED_LEASE", "remove the lease-token fence from acknowledgement",
			"internal/provider/sqlite/event_delivery.go",
			"\treturn coordinator.fenced(ctx, `UPDATE \"main\".\"_golem_outbox_delivery\" SET \"status\"='delivered',\"lease_token\"=NULL,\"lease_until\"=NULL,\"delivered_at\"=`+sqliteDatabaseMicros+`,\"blocked_at\"=NULL,\"retired_at\"=NULL,\"updated_at\"=`+sqliteDatabaseMicros+` WHERE \"causation_id\"=? AND \"lease_token\"=? AND \"status\"='leased'`, causation, token)\n",
			"\treturn coordinator.fenced(ctx, `UPDATE \"main\".\"_golem_outbox_delivery\" SET \"status\"='delivered',\"lease_token\"=NULL,\"lease_until\"=NULL,\"delivered_at\"=`+sqliteDatabaseMicros+`,\"blocked_at\"=NULL,\"retired_at\"=NULL,\"updated_at\"=`+sqliteDatabaseMicros+` WHERE \"causation_id\"=? AND \"status\"='leased'`, causation)\n",
			"./internal/provider/sqlite", "TestP7SQLiteExpiredTokenCanRenewUntilDatabaseReownershipThenIsFenced"),
		m("LEASE_BY_WORKER_NAME", "replace the unguessable lease token with one diagnostic worker label",
			"internal/provider/sqlite/event_delivery.go", "tokens[index], leaseUntil, now, causation, now, now)", "map[int]string{index: \"publisher-worker\"}[index], leaseUntil, now, causation, now, now)",
			"./internal/p7verify", "TestP7MutationLeaseTokensArePerClaimCapabilities"),
		m("LEASE_WITH_WORKER_CLOCK", "use process time instead of database time for claim eligibility",
			"internal/provider/sqlite/event_delivery.go",
			"\tvar now int64\n\tif err := connection.GetContext(ctx, &now, \"SELECT \"+sqliteDatabaseMicros); err != nil {\n\t\treturn nil, fmt.Errorf(\"P7_SQLITE_DELIVERY: read database time: %w\", err)\n\t}\n",
			"\tnow := time.Now().UTC().Add(24 * time.Hour).UnixMicro()\n",
			"./internal/p7verify", "TestP7MutationLeaseExpiryUsesDatabaseClock"),
		{
			Label: "SQLITE_DEFERRED_CLAIM", Summary: "use deferred ownership and discover candidates before acquiring the write lock",
			Patches: []mutationverify.Patch{
				{Path: "internal/provider/sqlite/event_delivery.go", Before: "if _, err := connection.ExecContext(ctx, \"BEGIN IMMEDIATE\"); err != nil {\n\t\treturn nil, fmt.Errorf(\"P7_SQLITE_DELIVERY: begin immediate claim: %w\", err)\n\t}", After: "if _, err := connection.ExecContext(ctx, \"BEGIN DEFERRED\"); err != nil {\n\t\treturn nil, fmt.Errorf(\"P7_SQLITE_DELIVERY: begin deferred claim: %w\", err)\n\t}"},
				{Path: "internal/provider/sqlite/event_delivery.go", Before: "\tif err := sqliteMaterializeMissing(ctx, connection, options.Groups); err != nil {\n\t\treturn nil, err\n\t}\n", After: ""},
				{Path: "internal/provider/sqlite/event_delivery.go", Before: "\tleases := make([]eventprovider.Lease, 0, len(causations))\n", After: "\tif err := sqliteMaterializeMissing(ctx, connection, options.Groups); err != nil { return nil, err }\n\tleases := make([]eventprovider.Lease, 0, len(causations))\n"},
			},
			Tests: []mutationverify.Test{{Package: "./internal/provider/sqlite", Name: "TestP7SQLiteConcurrentWorkersClaimWholeCausationsExclusively"}},
		},
		providerMutation("POSTGRES_NO_SKIP_LOCKED", "remove SKIP LOCKED from PostgreSQL claim",
			"internal/provider/postgresql/event_delivery.go", " FOR UPDATE SKIP LOCKED LIMIT $1`", " FOR UPDATE LIMIT $1`",
			"./internal/p7verify", "TestP7MutationPostgresClaimsUseSkipLocked"),
		m("SPLIT_CAUSATION_CLAIM", "load only the first fact from a claimed causation",
			"internal/provider/sqlite/event_delivery.go", " WHERE \"causation_id\"=? ORDER BY \"transaction_ordinal\"`, causation)", " WHERE \"causation_id\"=? ORDER BY \"transaction_ordinal\" LIMIT 1`, causation)",
			"./internal/provider/sqlite", "TestP7SQLiteDeliveryProviderCommonHarness"),
		m("ORDER_BY_EVENT_ID", "order one causal group by event identity instead of transaction ordinal",
			"internal/provider/sqlite/event_delivery.go", " WHERE \"causation_id\"=? ORDER BY \"transaction_ordinal\"`, causation)", " WHERE \"causation_id\"=? ORDER BY \"event_id\"`, causation)",
			"./internal/p7verify", "TestP7MutationCausalFactsUseTransactionOrdinalNotEventID"),
		m("CLAIM_GLOBAL_COMMIT_ORDER", "collapse the explicit causal tie-break and treat recorded time as total order",
			"internal/provider/sqlite/event_delivery.go", " ORDER BY \"first_recorded_at\",\"causation_id\" LIMIT ?`, now, now, options.Groups)", " ORDER BY \"first_recorded_at\" LIMIT ?`, now, now, options.Groups)",
			"./internal/p7verify", "TestP7MutationClaimTieHasCausationIdentityOrder"),
		m("TRUST_DUPLICATE_COLUMNS", "stop comparing model/action/ordinal duplicate columns with fact metadata",
			"internal/mutation/fact/verify.go",
			"\tif row.ModelID != hex.EncodeToString(model[:]) || row.Action != actionText(envelope.Action()) || row.TransactionOrdinal != int64(envelope.TransactionOrdinal()) {\n",
			"\tif false && (row.ModelID != hex.EncodeToString(model[:]) || row.Action != actionText(envelope.Action()) || row.TransactionOrdinal != int64(envelope.TransactionOrdinal())) {\n",
			"./internal/event/outbox", "TestP7PublisherRejectsOrdinalAndDuplicatedColumnCorruptionBeforeTransport"),
		m("CURRENT_GENERATION_ONLY", "route V2 history through its original generation instead of logical event schema",
			"internal/event/codec/codec.go", "\t\tEventSchema:   wireSchema,\n", "\t\tEventSchema:   golem.SchemaDigest(fact.Generation()),\n",
			"./runtime", "TestP7PendingV2FactSurvivesGraphQLOnlyRegeneration"),
		m("EVENT_SCHEMA_INCLUDES_GRAPHQL_NAME", "include a GraphQL payload name in logical event fingerprinting",
			"internal/graphql/contract/contract.go", "\tfingerprint, err := ir.EventSchemaFingerprint(shape)\n", "\tshape.ModelID = ir.ModelID(contract.GraphQLName)\n\tfingerprint, err := ir.EventSchemaFingerprint(shape)\n",
			"./internal/graphql/contract", "TestP7EventSchemaDigestIgnoresGraphQLOnlyChangesButTracksLogicalEventShape"),
		{
			Label: "ACCEPT_UNKNOWN_CODEC", Summary: "accept an unknown event codec identity as the active codec",
			Patches: []mutationverify.Patch{
				{Path: "internal/event/codec/codec.go", Before: "if err != nil || identity != CodecIdentity {", After: "if err != nil || len(identity) == 0 {"},
				{Path: "internal/event/codec/codec.go", Before: "\tif !bytes.Equal(canonical, encoded) {", After: "\tif false && !bytes.Equal(canonical, encoded) {"},
			},
			Tests: []mutationverify.Test{{Package: "./internal/p7verify", Name: "TestP7MutationUnknownCodecIdentityIsRejected"}},
		},
		m("DROP_AFTER_MAX_ATTEMPTS", "ack a transient failure after an arbitrary attempt ceiling",
			"internal/event/outbox/publisher.go", "\tif publishErr != nil {\n", "\tif publishErr != nil && lease.Delivery.AttemptCount > 3 { _, _ = publisher.coordinator.Acknowledge(ctx, lease.Delivery.CausationID, lease.Delivery.LeaseToken); return nil }\n\tif publishErr != nil {\n",
			"./internal/event/outbox", "TestP7TransientFailureNeverDropsAtArbitraryAttemptCount"),
		m("SILENTLY_DROP_CORRUPT_FACT", "ack a malformed durable fact instead of blocking it",
			"internal/event/outbox/publisher.go", "\t\tif row.CausationID != lease.Delivery.CausationID || row.TransactionOrdinal != int64(index+1) {\n\t\t\treturn publisher.blockInvalid(ctx, lease, \"fact-order-invalid\")\n\t\t}", "\t\tif row.CausationID != lease.Delivery.CausationID || row.TransactionOrdinal != int64(index+1) {\n\t\t\t_, _ = publisher.coordinator.Acknowledge(ctx, lease.Delivery.CausationID, lease.Delivery.LeaseToken)\n\t\t\treturn nil\n\t\t}",
			"./internal/event/outbox", "TestP7PublisherRejectsOrdinalAndDuplicatedColumnCorruptionBeforeTransport"),
		m("DELETE_PENDING_ON_RETENTION", "make pending delivery states eligible for retention",
			"internal/provider/sqlite/event_delivery.go", "WHERE d.\"status\"='delivered' AND d.\"delivered_at\"<=?", "WHERE d.\"status\" IN ('delivered','pending') AND COALESCE(d.\"delivered_at\",d.\"first_recorded_at\")<=?",
			"./internal/p7verify", "TestP7MutationRetentionCannotTouchPendingFacts"),
		m("PARTIAL_BATCH_ACK", "permit a transport error after a prefix to reach acknowledgement",
			"internal/event/outbox/publisher.go", "\tif publishErr != nil {\n", "\tif publishErr != nil && len(batch.Events()) == 0 {\n",
			"./internal/event/outbox", "TestP7PublisherReusesIdenticalCausalBatchAfterAmbiguousAcceptanceWindows"),
		m("SKIP_DELETE_SNAPSHOT", "omit compiler-owned stored scalar inventory from delete facts",
			"runtime/event_cdc_encoder.go", "\t\trequirement, err = mutationir.NewDeleteFactRequirement(identity, mutationir.DeleteSnapshotStoredScalars, deleteSnapshot)\n", "\t\t_ = deleteSnapshot\n\t\trequirement, err = mutationir.NewDeleteFactRequirement(identity, mutationir.DeleteSnapshotUnverifiable, nil)\n",
			"./runtime", "TestP7ProductionCDCEncoderCapturesCompilerOwnedDeleteSnapshot"),
		m("EXPOSE_DELETE_SNAPSHOT", "attach the private delete snapshot as a public event entity",
			"internal/event/typedvalue/value.go", "if entity.ModelID() != metadata.ModelID || metadata.Action == golem.EventDeleted {", "if entity.ModelID() != metadata.ModelID {",
			"./internal/p7verify", "TestP7MutationDeletedEntityCannotEnterPublicTypedValue"),
		m("FILTER_DELETED_SNAPSHOT_IN_GO", "evaluate a deleted-event where clause against its private Go snapshot",
			"runtime/events.go", "\t\tif state.originalWhere != nil {\n\t\t\treturn subscription.Suppress[any](events.SuppressionDeleteFiltered), nil\n\t\t}\n", "\t\tif state.originalWhere != nil && false {\n\t\t\treturn subscription.Suppress[any](events.SuppressionDeleteFiltered), nil\n\t\t}\n",
			"./runtime", "TestP7SQLiteFreshSubscriptionAuthorizationDeleteAndDuplicateOracle"),
		reuseAdmissionCallerMutation("REUSE_SUBSCRIBE_TIME_POLICY", "reuse the subscribe-time caller policy set instead of constructing fresh policy per event"),
		reuseAdmissionCallerMutation("REUSE_SUBSCRIBE_TIME_ACTOR", "reuse the subscribe-time actor/caller instead of resolving a fresh actor per event"),
		{
			Label: "REUSE_EVENT_LOADERS", Summary: "retain a GraphQL computed execution across event Recv calls",
			Patches: []mutationverify.Patch{
				{Path: "graphql/subscription.go", Before: "\tcloseErr error\n", After: "\tcloseErr error\n\tcomputed *computedExecution\n"},
				{Path: "graphql/subscription.go", Before: "\tcomputed, err := newComputedExecution(stream.executor.compilation, stream.executor.computed, stream.executor.maxComputedBatch)\n\tif err != nil {\n\t\treturn Response{}, err\n\t}\n", After: "\tcomputed := stream.computed\n\tif computed == nil {\n\t\tvar buildErr error\n\t\tcomputed, buildErr = newComputedExecution(stream.executor.compilation, stream.executor.computed, stream.executor.maxComputedBatch)\n\t\tif buildErr != nil { return Response{}, buildErr }\n\t\tstream.computed = computed\n\t}\n"},
				{Path: "graphql/subscription.go", Before: "\tdefer computed.close()\n", After: "\t// mutant: computed execution retained until stream close\n"},
			},
			Tests: []mutationverify.Test{{Package: "./graphql", Name: "TestP7SecondAndFiveHundredthEventSeeFreshComputedValues"}},
		},
		{
			Label: "SUBSCRIBE_WITHOUT_INITIAL_READ_AUTH", Summary: "replace caller admission and its model-read denial with a system allow-all plan",
			Patches: []mutationverify.Patch{
				{Path: "runtime/events.go", Before: "\tprepared, err := initial.Prepare(readRequest)\n", After: "\t_ = initial\n\tprepared, err := caller.app.System().Prepare(readRequest)\n"},
				{Path: "runtime/events.go", Before: "\tpolicy, present := initial.policies.Policy(policyir.ModelID(model))\n\tif !present {\n\t\treturn nil, golem.RuntimeReadError(golem.CodeForbidden, \"events\", model, golem.FieldID{}, \"read is not permitted\", nil)\n\t}\n\trowConstraint, err := policyresolve.RowConstraint(policy, policyir.ActionRead, policyir.ModelID(model))\n\tif err != nil {\n\t\treturn nil, golem.RuntimeReadError(golem.CodeForbidden, \"events\", model, golem.FieldID{}, \"read is not permitted\", err)\n\t}\n", After: "\trowConstraint, _ := policyir.NewConstant(policyir.ModelID(model), true)\n"},
			},
			Tests: []mutationverify.Test{{Package: "./runtime", Name: "TestP7CallerAndGraphQLSubscribeAuthorizeReadBeforeRegistration"}},
		},
		m("AUTH_ONLY_WHEN_ENTITY_SELECTED", "skip created/updated fresh read authorization for identity-only selection",
			"runtime/events.go", "\tcase golem.EventCreated, golem.EventUpdated:\n\t\trow, delivered, readErr := app.readEventEntity", "\tcase golem.EventCreated, golem.EventUpdated:\n\t\tif !state.entitySelected { break }\n\t\trow, delivered, readErr := app.readEventEntity",
			"./runtime", "TestP7IdentityOnlyEventStillReauthorizes"),
		m("GROUP_ACROSS_PRINCIPALS", "remove principal identity from the shared evaluation key",
			"internal/subscription/key.go", "principal: key.principal, policy: key.policy, filter: key.filter,", "principal: CanonicalIdentity{}, policy: key.policy, filter: key.filter,",
			"./internal/subscription", "TestP7DifferentPrincipalsNeverShareEvaluation"),
		m("GROUP_WITHOUT_SELECTION_IN_KEY", "remove selected result shape from the shared evaluation key",
			"internal/subscription/key.go", "selection: key.selection, dependencies: key.dependencies, encoder: key.encoder,", "selection: CanonicalIdentity{}, dependencies: key.dependencies, encoder: key.encoder,",
			"./internal/subscription", "TestP7DifferentSelectionFilterOrPolicyVersionNeverShareResult"),
		m("AUDIT_ID_IS_SECURITY_ID", "replace unique retained-principal identity with a constant audit-equivalent identity",
			"internal/subscription/key.go", "principal: key.principal, policy: key.policy, filter: key.filter,", "principal: CanonicalIdentity{}, policy: key.policy, filter: key.filter,",
			"./internal/subscription", "TestP7AuditPrincipalCollisionDoesNotAuthorizeSharing"),
		m("SHARE_HOOKED_OR_COMPUTED_EVALUATION", "mark runtime event subscriptions shareable despite hooks/computed work",
			"runtime/events.go", "\t\tShareable: false,\n", "\t\tShareable: true,\n",
			"./runtime", "TestP7FreshPrincipalActorPolicyAndExecutionPerEvent"),
		m("DROP_ON_QUEUE_OVERFLOW", "drop a full-queue event while keeping the subscriber registered",
			"internal/subscription/hub.go", "\tdefault:\n\t\tcleanup := hub.removeLocked(item, events.CodeSubscriptionOverflow)", "\tdefault:\n\t\tcleanup := func() {}",
			"./internal/subscription", "TestP7SubscriberQueueExactBoundaryAndOverflowDisconnect"),
		m("UNBOUNDED_EVALUATION_GOROUTINES", "start one evaluation worker per possible subscriber instead of the normalized bound",
			"internal/subscription/hub.go", "for index := 0; index < hub.limits.EvaluationConcurrency; index++ {", "for index := 0; index < hub.limits.EvaluationConcurrency*8; index++ {",
			"./internal/subscription", "TestP7EvaluationConcurrencyHardBound"),
		m("START_EVALUATION_AFTER_CANCEL", "detach evaluation jobs from run cancellation",
			"internal/subscription/hub.go", "result, err := hub.evaluate(run.ctx, job)", "result, err := hub.evaluate(context.Background(), job)",
			"./internal/subscription", "TestP7CancellationDoesNotStartQueuedEvaluation"),
		m("GRAPHQL_SECOND_EVENT_ENGINE", "bypass active gqlgen execution for event responses",
			"graphql/websocket.go", "serialized = state.server.executePrepared(ctx, request, prepared.Operation.Document, prepared.Operation.Definition, prepared.Operation.Variables, response)", "serialized = Response{Data: map[string]any{\"payload\": map[string]any{\"kind\": \"SECOND_ENGINE\"}}}",
			"./graphql", "TestP7ActiveGQLGenSerializesSubscriptionAliasesDirectivesEnumsAndObjects"),
		m("EMIT_DISABLED_SUBSCRIPTION", "emit an event root from a reserved name when subscriptions are disabled",
			"internal/graphql/schema/schema.go", "\t\tif view.contract.Subscriptions {\n", "\t\tif view.contract.Subscriptions || roots.Events != \"\" {\n",
			"./internal/graphql/schema", "TestP7SubscriptionSDLUsesClosedEventABI"),
		m("HAND_SERIALIZE_WS_ENTITY", "send the runtime response without active gqlgen scalar/field serialization",
			"graphql/websocket.go", "serialized = state.server.executePrepared(ctx, request, prepared.Operation.Document, prepared.Operation.Definition, prepared.Operation.Variables, response)", "serialized = Response{Data: map[string]any{\"payload\": response.Data}}",
			"./graphql", "TestP7ActiveGQLGenSerializesSubscriptionAliasesDirectivesEnumsAndObjects"),
		m("ACCEPT_LEGACY_WS_AS_NEW", "negotiate the obsolete graphql-ws subprotocol as P7",
			"graphql/websocket.go", "containsProtocol(websocket.Subprotocols(request), graphqlTransportWS)", "(containsProtocol(websocket.Subprotocols(request), graphqlTransportWS) || containsProtocol(websocket.Subprotocols(request), \"graphql-ws\"))",
			"./graphql", "TestP7WebSocketRejectsLegacyDuplicateMalformedAndTimesOutInit"),
		m("OBSERVER_PANIC_PROPAGATES", "remove observer panic isolation",
			"events/observer.go", "\tfunc() {\n\t\tdefer func() { _ = recover() }()\n\t\tobserver.ObserveEvent(ctx, observation)\n\t}()\n", "\tobserver.ObserveEvent(ctx, observation)\n",
			"./internal/subscription", "TestP7ObserverPanicIsCorrectnessNeutral"),
		m("CLAIM_EXTERNAL_WRITES_VISIBLE_WITHOUT_CDC", "report external writes observed even with no adapter",
			"runtime/event_lifecycle.go", "len(app.eventAdapterNames) != 0,", "true,",
			"./runtime", "TestP7CapabilitiesReportExternalWritesObservedFalse"),
		m("CDC_RANDOM_EVENT_ID", "replace replay-stable CDC event IDs with a random value",
			"internal/event/cdc/cdc.go", "eventID := deriveEventID(identity, owned.SourceTransactionID, change.Ordinal)", "eventID := deriveEventID(identity, owned.SourceTransactionID+time.Now().UTC().String(), change.Ordinal)",
			"./internal/event/cdc", "TestP7CDCReplayDerivesStableEventIDs"),
		m("CDC_CHECKPOINT_BEFORE_ACCEPT", "emit CDC acknowledgement before transport acceptance",
			"internal/event/cdc/cdc.go", "\tif err := emitter.config.Transport.Publish(ctx, batch); err != nil {\n\t\treturn events.Failure(events.CodeCDCUnavailable)\n\t}", "\tif err := emitter.config.Transport.Publish(ctx, batch); err != nil {\n\t\treturn nil\n\t}",
			"./internal/event/cdc", "TestP7CDCCheckpointAdvancesOnlyAfterTransportAcceptance"),
		m("CDC_SECOND_CODEC_OR_AUTH_PATH", "skip the shared encoder's sealed notice validation",
			"internal/event/cdc/cdc.go", "if encodeErr != nil || !notice.Valid() || notice.EventID() != eventID || notice.CausationID() != causation || notice.TransactionOrdinal() != change.Ordinal || notice.ModelID() != change.Model || notice.Action() != change.Action {", "if encodeErr != nil {",
			"./internal/event/cdc", "TestP7CDCRejectsEncoderMetadataMismatch"),
		m("CDC_DUPLICATES_GOLEM_OUTBOX_WRITE", "ignore adapter-owned Golem-transaction correlation",
			"internal/event/cdc/cdc.go", "\tif correlated {\n", "\tif correlated && false {\n",
			"./internal/event/cdc", "TestP7CDCGolemTransactionCorrelationAvoidsSecondEvent"),
		m("RUN_HOOK_ON_PUBLISH_RETRY", "invoke application-owned work once per publisher retry",
			"internal/event/outbox/publisher.go", "\tif publishErr != nil {\n", "\tif publishErr != nil { if publisher.hooks.AfterPublishBeforeAck != nil { _ = publisher.hooks.AfterPublishBeforeAck(batch) }\n",
			"./internal/p7verify", "TestP7MutationPublisherRetryPathContainsNoApplicationCallback"),
		m("SKIP_REQUIRED_POSTGRES_LIVE_GATE", "allow the crash command to succeed without both required PostgreSQL profiles",
			"internal/p7verify/crash.go", "\t\treturn fmt.Errorf(\"P7_CRASH_REQUIRED_PROFILE: missing %s\", strings.Join(missing, \",\"))\n", "\t\treturn nil\n",
			"./internal/cmd/p7crash", "TestP7CrashCommandMissingRequiredPostgreSQLProfilesIsFailure"),
	}
}

func reuseAdmissionCallerMutation(label, summary string) mutationverify.Mutation {
	return mutationverify.Mutation{
		Label: label, Summary: summary,
		Patches: []mutationverify.Patch{
			{Path: "runtime/events.go", Before: "\tentitySelected bool\n", After: "\tentitySelected bool\n\tinitial any\n"},
			{Path: "runtime/events.go", Before: "\t\toriginalWhere: originalWhere, metadata: metadata, entitySelected: entitySelected,\n", After: "\t\toriginalWhere: originalWhere, metadata: metadata, entitySelected: entitySelected, initial: initial,\n"},
			{Path: "runtime/events.go", Before: "\tfresh, err := app.ForPrincipal(eventContext, state.principal)\n", After: "\tfresh := any(state.initial).(*Caller[P, A])\n"},
		},
		Tests: []mutationverify.Test{{Package: "./runtime", Name: "TestP7FreshPrincipalActorPolicyAndExecutionPerEvent"}},
	}
}
