// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p8-graphql-abi-v5; generation c472605678c26793aac520090116c841a2542253673c98d4763ecc6f6edf61fb; generator p1-v1; template p8-go-abi-v7.

package golemgqlgen

import (
	"fmt"
	"io"
	"strconv"
)

type BigIntAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type BigIntFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type BigIntListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type BigIntListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type BigIntUpdateOperationsInput struct {
	Set       any `json:"set,omitempty"`
	Increment any `json:"increment,omitempty"`
	Decrement any `json:"decrement,omitempty"`
}

type BooleanAnalyticsFilter struct {
	Equals *bool `json:"equals,omitempty"`
	Not    *bool `json:"not,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type BooleanFilter struct {
	Equals *bool  `json:"equals,omitempty"`
	Not    *bool  `json:"not,omitempty"`
	In     []bool `json:"in,omitempty"`
	NotIn  []bool `json:"notIn,omitempty"`
}

type BooleanListFilter struct {
	Equals   []bool `json:"equals,omitempty"`
	Has      *bool  `json:"has,omitempty"`
	HasEvery []bool `json:"hasEvery,omitempty"`
	HasSome  []bool `json:"hasSome,omitempty"`
	IsEmpty  *bool  `json:"isEmpty,omitempty"`
}

type BooleanListUpdateOperationsInput struct {
	Set []bool `json:"set,omitempty"`
}

type BooleanUpdateOperationsInput struct {
	Set *bool `json:"set,omitempty"`
}

type BytesFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
}

type BytesUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type DateAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DateFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DateListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DateListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DateTimeAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DateTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DateTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DateTimeListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DateTimeUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type DateUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type DecimalAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DecimalFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DecimalListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DecimalListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DecimalUpdateOperationsInput struct {
	Set       any `json:"set,omitempty"`
	Increment any `json:"increment,omitempty"`
	Decrement any `json:"decrement,omitempty"`
}

type FloatAnalyticsFilter struct {
	Equals *float64 `json:"equals,omitempty"`
	Not    *float64 `json:"not,omitempty"`
	Lt     *float64 `json:"lt,omitempty"`
	Lte    *float64 `json:"lte,omitempty"`
	Gt     *float64 `json:"gt,omitempty"`
	Gte    *float64 `json:"gte,omitempty"`
	IsNull *bool    `json:"isNull,omitempty"`
}

type FloatFilter struct {
	Equals *float64  `json:"equals,omitempty"`
	Not    *float64  `json:"not,omitempty"`
	In     []float64 `json:"in,omitempty"`
	NotIn  []float64 `json:"notIn,omitempty"`
	Lt     *float64  `json:"lt,omitempty"`
	Lte    *float64  `json:"lte,omitempty"`
	Gt     *float64  `json:"gt,omitempty"`
	Gte    *float64  `json:"gte,omitempty"`
}

type FloatListFilter struct {
	Equals   []float64 `json:"equals,omitempty"`
	Has      *float64  `json:"has,omitempty"`
	HasEvery []float64 `json:"hasEvery,omitempty"`
	HasSome  []float64 `json:"hasSome,omitempty"`
	IsEmpty  *bool     `json:"isEmpty,omitempty"`
}

type FloatListUpdateOperationsInput struct {
	Set []float64 `json:"set,omitempty"`
}

type FloatUpdateOperationsInput struct {
	Set       *float64 `json:"set,omitempty"`
	Increment *float64 `json:"increment,omitempty"`
	Decrement *float64 `json:"decrement,omitempty"`
}

type IntAnalyticsFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type IntFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	In     []int `json:"in,omitempty"`
	NotIn  []int `json:"notIn,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
}

type IntListFilter struct {
	Equals   []int `json:"equals,omitempty"`
	Has      *int  `json:"has,omitempty"`
	HasEvery []int `json:"hasEvery,omitempty"`
	HasSome  []int `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type IntListUpdateOperationsInput struct {
	Set []int `json:"set,omitempty"`
}

type IntUpdateOperationsInput struct {
	Set       *int `json:"set,omitempty"`
	Increment *int `json:"increment,omitempty"`
	Decrement *int `json:"decrement,omitempty"`
}

type InviteConnectOrCreateWithoutTeamInput struct {
	Where  *InviteWhereUniqueInput       `json:"where"`
	Create *InviteCreateWithoutTeamInput `json:"create"`
}

type InviteCreateInput struct {
	ID     any                            `json:"id"`
	Owner  string                         `json:"owner"`
	Email  string                         `json:"email"`
	Status string                         `json:"status"`
	Team   *InviteTeamCreateRelationInput `json:"team"`
}

type InviteCreateWithoutTeamInput struct {
	ID     any    `json:"id"`
	Owner  string `json:"owner"`
	Email  string `json:"email"`
	Status string `json:"status"`
}

type InviteListRelationFilter struct {
	Some  *InviteWhereInput `json:"some,omitempty"`
	Every *InviteWhereInput `json:"every,omitempty"`
	None  *InviteWhereInput `json:"none,omitempty"`
}

type InviteOrderByInput struct {
	ID     *SortOrder `json:"id,omitempty"`
	TeamID *SortOrder `json:"teamID,omitempty"`
	Owner  *SortOrder `json:"owner,omitempty"`
	Email  *SortOrder `json:"email,omitempty"`
	Status *SortOrder `json:"status,omitempty"`
}

type InviteTeamCreateRelationInput struct {
	Create          *TeamCreateWithoutInvitesInput          `json:"create,omitempty"`
	Connect         *TeamWhereUniqueInput                   `json:"connect,omitempty"`
	ConnectOrCreate *TeamConnectOrCreateWithoutInvitesInput `json:"connectOrCreate,omitempty"`
}

type InviteTeamUpdateRelationInput struct {
	Create          *TeamCreateWithoutInvitesInput          `json:"create,omitempty"`
	Connect         *TeamWhereUniqueInput                   `json:"connect,omitempty"`
	ConnectOrCreate *TeamConnectOrCreateWithoutInvitesInput `json:"connectOrCreate,omitempty"`
	Update          *TeamUpdateWithoutInvitesInput          `json:"update,omitempty"`
	Upsert          *TeamUpsertWithoutInvitesInput          `json:"upsert,omitempty"`
}

type InviteUpdateInput struct {
	ID     *UUIDUpdateOperationsInput     `json:"id,omitempty"`
	Owner  *StringUpdateOperationsInput   `json:"owner,omitempty"`
	Email  *StringUpdateOperationsInput   `json:"email,omitempty"`
	Status *StringUpdateOperationsInput   `json:"status,omitempty"`
	Team   *InviteTeamUpdateRelationInput `json:"team,omitempty"`
}

type InviteUpdateManyInput struct {
	ID     *UUIDUpdateOperationsInput   `json:"id,omitempty"`
	TeamID *UUIDUpdateOperationsInput   `json:"teamID,omitempty"`
	Owner  *StringUpdateOperationsInput `json:"owner,omitempty"`
	Email  *StringUpdateOperationsInput `json:"email,omitempty"`
	Status *StringUpdateOperationsInput `json:"status,omitempty"`
}

type InviteUpdateManyWithWhereWithoutTeamInput struct {
	Where *InviteWhereInput      `json:"where"`
	Data  *InviteUpdateManyInput `json:"data"`
}

type InviteUpdateWithWhereWithoutTeamInput struct {
	Where *InviteWhereUniqueInput       `json:"where"`
	Data  *InviteUpdateWithoutTeamInput `json:"data"`
}

type InviteUpdateWithoutTeamInput struct {
	ID     *UUIDUpdateOperationsInput   `json:"id,omitempty"`
	Owner  *StringUpdateOperationsInput `json:"owner,omitempty"`
	Email  *StringUpdateOperationsInput `json:"email,omitempty"`
	Status *StringUpdateOperationsInput `json:"status,omitempty"`
}

type InviteUpsertWithWhereWithoutTeamInput struct {
	Where  *InviteWhereUniqueInput       `json:"where"`
	Create *InviteCreateWithoutTeamInput `json:"create"`
	Update *InviteUpdateWithoutTeamInput `json:"update"`
}

type InviteWhereInput struct {
	All    *bool               `json:"all,omitempty"`
	And    []*InviteWhereInput `json:"AND,omitempty"`
	Or     []*InviteWhereInput `json:"OR,omitempty"`
	Not    []*InviteWhereInput `json:"NOT,omitempty"`
	ID     *UUIDFilter         `json:"id,omitempty"`
	TeamID *UUIDFilter         `json:"teamID,omitempty"`
	Owner  *StringFilter       `json:"owner,omitempty"`
	Email  *StringFilter       `json:"email,omitempty"`
	Status *StringFilter       `json:"status,omitempty"`
	Team   *TeamRelationFilter `json:"team,omitempty"`
}

type InviteWhereUniqueInput struct {
	ID any `json:"ID,omitempty"`
}

type JSONFilter struct {
	Equals           any        `json:"equals,omitempty"`
	Not              any        `json:"not,omitempty"`
	Lt               any        `json:"lt,omitempty"`
	Lte              any        `json:"lte,omitempty"`
	Gt               any        `json:"gt,omitempty"`
	Gte              any        `json:"gte,omitempty"`
	StringContains   *string    `json:"stringContains,omitempty"`
	StringStartsWith *string    `json:"stringStartsWith,omitempty"`
	StringEndsWith   *string    `json:"stringEndsWith,omitempty"`
	ArrayContains    any        `json:"arrayContains,omitempty"`
	ArrayStartsWith  any        `json:"arrayStartsWith,omitempty"`
	ArrayEndsWith    any        `json:"arrayEndsWith,omitempty"`
	Path             []string   `json:"path,omitempty"`
	Mode             *QueryMode `json:"mode,omitempty"`
}

type JSONUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type NullableBigIntFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableBigIntListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableBigIntListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableBigIntUpdateOperationsInput struct {
	Set       any   `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment any   `json:"increment,omitempty"`
	Decrement any   `json:"decrement,omitempty"`
}

type NullableBooleanFilter struct {
	Equals *bool  `json:"equals,omitempty"`
	Not    *bool  `json:"not,omitempty"`
	In     []bool `json:"in,omitempty"`
	NotIn  []bool `json:"notIn,omitempty"`
	IsNull *bool  `json:"isNull,omitempty"`
}

type NullableBooleanListFilter struct {
	Equals   []bool `json:"equals,omitempty"`
	Has      *bool  `json:"has,omitempty"`
	HasEvery []bool `json:"hasEvery,omitempty"`
	HasSome  []bool `json:"hasSome,omitempty"`
	IsEmpty  *bool  `json:"isEmpty,omitempty"`
	IsNull   *bool  `json:"isNull,omitempty"`
}

type NullableBooleanListUpdateOperationsInput struct {
	Set     []bool `json:"set,omitempty"`
	SetNull *bool  `json:"setNull,omitempty"`
}

type NullableBooleanUpdateOperationsInput struct {
	Set     *bool `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableBytesFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableBytesUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDateListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDateListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDateTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDateTimeListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateTimeUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDecimalFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDecimalListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDecimalListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDecimalUpdateOperationsInput struct {
	Set       any   `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment any   `json:"increment,omitempty"`
	Decrement any   `json:"decrement,omitempty"`
}

type NullableFloatFilter struct {
	Equals *float64  `json:"equals,omitempty"`
	Not    *float64  `json:"not,omitempty"`
	In     []float64 `json:"in,omitempty"`
	NotIn  []float64 `json:"notIn,omitempty"`
	Lt     *float64  `json:"lt,omitempty"`
	Lte    *float64  `json:"lte,omitempty"`
	Gt     *float64  `json:"gt,omitempty"`
	Gte    *float64  `json:"gte,omitempty"`
	IsNull *bool     `json:"isNull,omitempty"`
}

type NullableFloatListFilter struct {
	Equals   []float64 `json:"equals,omitempty"`
	Has      *float64  `json:"has,omitempty"`
	HasEvery []float64 `json:"hasEvery,omitempty"`
	HasSome  []float64 `json:"hasSome,omitempty"`
	IsEmpty  *bool     `json:"isEmpty,omitempty"`
	IsNull   *bool     `json:"isNull,omitempty"`
}

type NullableFloatListUpdateOperationsInput struct {
	Set     []float64 `json:"set,omitempty"`
	SetNull *bool     `json:"setNull,omitempty"`
}

type NullableFloatUpdateOperationsInput struct {
	Set       *float64 `json:"set,omitempty"`
	SetNull   *bool    `json:"setNull,omitempty"`
	Increment *float64 `json:"increment,omitempty"`
	Decrement *float64 `json:"decrement,omitempty"`
}

type NullableIntFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	In     []int `json:"in,omitempty"`
	NotIn  []int `json:"notIn,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableIntListFilter struct {
	Equals   []int `json:"equals,omitempty"`
	Has      *int  `json:"has,omitempty"`
	HasEvery []int `json:"hasEvery,omitempty"`
	HasSome  []int `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableIntListUpdateOperationsInput struct {
	Set     []int `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableIntUpdateOperationsInput struct {
	Set       *int  `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment *int  `json:"increment,omitempty"`
	Decrement *int  `json:"decrement,omitempty"`
}

type NullableJSONFilter struct {
	Equals           any        `json:"equals,omitempty"`
	Not              any        `json:"not,omitempty"`
	Lt               any        `json:"lt,omitempty"`
	Lte              any        `json:"lte,omitempty"`
	Gt               any        `json:"gt,omitempty"`
	Gte              any        `json:"gte,omitempty"`
	StringContains   *string    `json:"stringContains,omitempty"`
	StringStartsWith *string    `json:"stringStartsWith,omitempty"`
	StringEndsWith   *string    `json:"stringEndsWith,omitempty"`
	ArrayContains    any        `json:"arrayContains,omitempty"`
	ArrayStartsWith  any        `json:"arrayStartsWith,omitempty"`
	ArrayEndsWith    any        `json:"arrayEndsWith,omitempty"`
	Path             []string   `json:"path,omitempty"`
	Mode             *QueryMode `json:"mode,omitempty"`
	IsNull           *bool      `json:"isNull,omitempty"`
}

type NullableJSONUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableStringFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	In         []string   `json:"in,omitempty"`
	NotIn      []string   `json:"notIn,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
	IsNull     *bool      `json:"isNull,omitempty"`
}

type NullableStringListFilter struct {
	Equals   []string `json:"equals,omitempty"`
	Has      *string  `json:"has,omitempty"`
	HasEvery []string `json:"hasEvery,omitempty"`
	HasSome  []string `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
	IsNull   *bool    `json:"isNull,omitempty"`
}

type NullableStringListUpdateOperationsInput struct {
	Set     []string `json:"set,omitempty"`
	SetNull *bool    `json:"setNull,omitempty"`
}

type NullableStringUpdateOperationsInput struct {
	Set     *string `json:"set,omitempty"`
	SetNull *bool   `json:"setNull,omitempty"`
}

type NullableTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableTimeListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableTimeUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableUUIDFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableUUIDListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableUUIDListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableUUIDUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type StringAnalyticsFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
	IsNull     *bool      `json:"isNull,omitempty"`
}

type StringFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	In         []string   `json:"in,omitempty"`
	NotIn      []string   `json:"notIn,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
}

type StringListFilter struct {
	Equals   []string `json:"equals,omitempty"`
	Has      *string  `json:"has,omitempty"`
	HasEvery []string `json:"hasEvery,omitempty"`
	HasSome  []string `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
}

type StringListUpdateOperationsInput struct {
	Set []string `json:"set,omitempty"`
}

type StringUpdateOperationsInput struct {
	Set *string `json:"set,omitempty"`
}

type TeamConnectOrCreateWithoutInvitesInput struct {
	Where  *TeamWhereUniqueInput          `json:"where"`
	Create *TeamCreateWithoutInvitesInput `json:"create"`
}

type TeamCreateInput struct {
	ID      any                             `json:"id"`
	Owner   string                          `json:"owner"`
	Invites *TeamInvitesCreateRelationInput `json:"invites,omitempty"`
}

type TeamCreateWithoutInvitesInput struct {
	ID    any    `json:"id"`
	Owner string `json:"owner"`
}

type TeamInvitesCreateRelationInput struct {
	Create          []*InviteCreateWithoutTeamInput          `json:"create,omitempty"`
	CreateMany      []*InviteCreateWithoutTeamInput          `json:"createMany,omitempty"`
	Connect         []*InviteWhereUniqueInput                `json:"connect,omitempty"`
	ConnectOrCreate []*InviteConnectOrCreateWithoutTeamInput `json:"connectOrCreate,omitempty"`
}

type TeamInvitesUpdateRelationInput struct {
	Create          []*InviteCreateWithoutTeamInput              `json:"create,omitempty"`
	CreateMany      []*InviteCreateWithoutTeamInput              `json:"createMany,omitempty"`
	Connect         []*InviteWhereUniqueInput                    `json:"connect,omitempty"`
	Disconnect      []*InviteWhereUniqueInput                    `json:"disconnect,omitempty"`
	Set             []*InviteWhereUniqueInput                    `json:"set,omitempty"`
	Delete          []*InviteWhereUniqueInput                    `json:"delete,omitempty"`
	DeleteMany      []*InviteWhereInput                          `json:"deleteMany,omitempty"`
	ConnectOrCreate []*InviteConnectOrCreateWithoutTeamInput     `json:"connectOrCreate,omitempty"`
	Update          []*InviteUpdateWithWhereWithoutTeamInput     `json:"update,omitempty"`
	UpdateMany      []*InviteUpdateManyWithWhereWithoutTeamInput `json:"updateMany,omitempty"`
	Upsert          []*InviteUpsertWithWhereWithoutTeamInput     `json:"upsert,omitempty"`
}

type TeamOrderByInput struct {
	ID    *SortOrder `json:"id,omitempty"`
	Owner *SortOrder `json:"owner,omitempty"`
}

type TeamRelationFilter struct {
	Is    *TeamWhereInput `json:"is,omitempty"`
	IsNot *TeamWhereInput `json:"isNot,omitempty"`
}

type TeamUpdateInput struct {
	ID      *UUIDUpdateOperationsInput      `json:"id,omitempty"`
	Owner   *StringUpdateOperationsInput    `json:"owner,omitempty"`
	Invites *TeamInvitesUpdateRelationInput `json:"invites,omitempty"`
}

type TeamUpdateManyInput struct {
	ID    *UUIDUpdateOperationsInput   `json:"id,omitempty"`
	Owner *StringUpdateOperationsInput `json:"owner,omitempty"`
}

type TeamUpdateWithoutInvitesInput struct {
	ID    *UUIDUpdateOperationsInput   `json:"id,omitempty"`
	Owner *StringUpdateOperationsInput `json:"owner,omitempty"`
}

type TeamUpsertWithoutInvitesInput struct {
	Create *TeamCreateWithoutInvitesInput `json:"create"`
	Update *TeamUpdateWithoutInvitesInput `json:"update"`
}

type TeamWhereInput struct {
	All     *bool                     `json:"all,omitempty"`
	And     []*TeamWhereInput         `json:"AND,omitempty"`
	Or      []*TeamWhereInput         `json:"OR,omitempty"`
	Not     []*TeamWhereInput         `json:"NOT,omitempty"`
	ID      *UUIDFilter               `json:"id,omitempty"`
	Owner   *StringFilter             `json:"owner,omitempty"`
	Invites *InviteListRelationFilter `json:"invites,omitempty"`
}

type TeamWhereUniqueInput struct {
	ID any `json:"ID,omitempty"`
}

type TimeAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type TimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type TimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type TimeListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type TimeUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type UUIDAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type UUIDFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
}

type UUIDListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type UUIDListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type UUIDUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type InviteScalarField string

const (
	InviteScalarFieldID     InviteScalarField = "id"
	InviteScalarFieldTeamID InviteScalarField = "teamID"
	InviteScalarFieldOwner  InviteScalarField = "owner"
	InviteScalarFieldEmail  InviteScalarField = "email"
	InviteScalarFieldStatus InviteScalarField = "status"
)

var AllInviteScalarField = []InviteScalarField{
	InviteScalarFieldID,
	InviteScalarFieldTeamID,
	InviteScalarFieldOwner,
	InviteScalarFieldEmail,
	InviteScalarFieldStatus,
}

func (e InviteScalarField) IsValid() bool {
	switch e {
	case InviteScalarFieldID, InviteScalarFieldTeamID, InviteScalarFieldOwner, InviteScalarFieldEmail, InviteScalarFieldStatus:
		return true
	}
	return false
}

func (e InviteScalarField) String() string {
	return string(e)
}

func (e *InviteScalarField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InviteScalarField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InviteScalarField", str)
	}
	return nil
}

func (e InviteScalarField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type QueryMode string

const (
	QueryModeSensitive   QueryMode = "sensitive"
	QueryModeInsensitive QueryMode = "insensitive"
)

var AllQueryMode = []QueryMode{
	QueryModeSensitive,
	QueryModeInsensitive,
}

func (e QueryMode) IsValid() bool {
	switch e {
	case QueryModeSensitive, QueryModeInsensitive:
		return true
	}
	return false
}

func (e QueryMode) String() string {
	return string(e)
}

func (e *QueryMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QueryMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QueryMode", str)
	}
	return nil
}

func (e QueryMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TeamScalarField string

const (
	TeamScalarFieldID    TeamScalarField = "id"
	TeamScalarFieldOwner TeamScalarField = "owner"
)

var AllTeamScalarField = []TeamScalarField{
	TeamScalarFieldID,
	TeamScalarFieldOwner,
}

func (e TeamScalarField) IsValid() bool {
	switch e {
	case TeamScalarFieldID, TeamScalarFieldOwner:
		return true
	}
	return false
}

func (e TeamScalarField) String() string {
	return string(e)
}

func (e *TeamScalarField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamScalarField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamScalarField", str)
	}
	return nil
}

func (e TeamScalarField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
