// Code generated by golem. DO NOT EDIT.
// Golem generation digest: 47a892588f095edc040a25025ee6e59abfc5eeffa9e7daca2d976d8e3fa59edf
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v5

package p5extensions

import (
	golem "github.com/eleven-am/golem/go/golem"
)

type UserFindOneRequest = golem.FindOneHookRequest[User]
type UserFindOneResult = golem.FindOneHookResult[User]
type UserFindFirstRequest = golem.FindFirstHookRequest[User]
type UserFindFirstResult = golem.FindFirstHookResult[User]
type UserFindManyRequest = golem.FindManyHookRequest[User]
type UserFindManyResult = golem.FindManyHookResult[User]
type UserCreateRequest = golem.CreateHookRequest[User]
type UserCreateResult = golem.CreateHookResult[User]
type UserUpdateRequest = golem.UpdateHookRequest[User]
type UserUpdateResult = golem.UpdateHookResult[User]
type UserDeleteRequest = golem.DeleteHookRequest[User]
type UserDeleteResult = golem.DeleteHookResult[User]
type UserUpdateManyRequest = golem.UpdateManyHookRequest[User]
type UserUpdateManyResult = golem.UpdateManyHookResult[User]
type UserDeleteManyRequest = golem.DeleteManyHookRequest[User]
type UserDeleteManyResult = golem.DeleteManyHookResult[User]

func golemBuildUserPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[User]()
	User{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, User](golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9}, golemBuildUserPolicy),
	}
	hooks := []golem.HookBinding[Actor]{}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0x47, 0xa8, 0x92, 0x58, 0x8f, 0x09, 0x5e, 0xdc, 0x04, 0x0a, 0x25, 0x02, 0x5e, 0xe6, 0xe5, 0x9a, 0xbf, 0xc5, 0xee, 0xff, 0xa9, 0xe7, 0xda, 0xca, 0x2d, 0x97, 0x6d, 0x8e, 0x3f, 0xa5, 0x9e, 0xdf}, policies, hooks)
}
