// Code generated by golem. DO NOT EDIT.
// Golem generation digest: 0626c50a3f118c854373f417ea00fb40213bcaad9d6ff6feb5d61a5c3e4b9c48
// Golem generator version: p1-v1
// Golem template ABI version: p8-go-abi-v7

package p5extensions

import (
	golem "github.com/eleven-am/golem/go/golem"
)

type UserFindOneRequest = golem.FindOneHookRequest[User]
type UserFindOneResult = golem.FindOneHookResult[User]
type UserFindFirstRequest = golem.FindFirstHookRequest[User]
type UserFindFirstResult = golem.FindFirstHookResult[User]
type UserFindManyRequest = golem.FindManyHookRequest[User]
type UserFindManyResult = golem.FindManyHookResult[User]
type UserCreateRequest = golem.CreateHookRequest[User]
type UserCreateResult = golem.CreateHookResult[User]
type UserUpdateRequest = golem.UpdateHookRequest[User]
type UserUpdateResult = golem.UpdateHookResult[User]
type UserDeleteRequest = golem.DeleteHookRequest[User]
type UserDeleteResult = golem.DeleteHookResult[User]
type UserUpdateManyRequest = golem.UpdateManyHookRequest[User]
type UserUpdateManyResult = golem.UpdateManyHookResult[User]
type UserDeleteManyRequest = golem.DeleteManyHookRequest[User]
type UserDeleteManyResult = golem.DeleteManyHookResult[User]

func golemBuildUserPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[User]()
	User{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, User](golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9}, golemBuildUserPolicy),
	}
	hooks := []golem.HookBinding[Actor]{}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0x06, 0x26, 0xc5, 0x0a, 0x3f, 0x11, 0x8c, 0x85, 0x43, 0x73, 0xf4, 0x17, 0xea, 0x00, 0xfb, 0x40, 0x21, 0x3b, 0xca, 0xad, 0x9d, 0x6f, 0xf6, 0xfe, 0xb5, 0xd6, 0x1a, 0x5c, 0x3e, 0x4b, 0x9c, 0x48}, policies, hooks)
}
