// Code generated by golem. DO NOT EDIT.
// Golem generation digest: 8fcc42932feef23d8c0a0d5d10b8e026ef0ebca6152bc0b45a130cb8cda21bd7
// Golem generator version: p1-v1
// Golem template ABI version: p2-go-abi-v4

package p5extensions

import (
	golem "github.com/eleven-am/golem/go/golem"
)

type UserFindOneRequest = golem.FindOneHookRequest[User]
type UserFindOneResult = golem.FindOneHookResult[User]
type UserFindFirstRequest = golem.FindFirstHookRequest[User]
type UserFindFirstResult = golem.FindFirstHookResult[User]
type UserFindManyRequest = golem.FindManyHookRequest[User]
type UserFindManyResult = golem.FindManyHookResult[User]
type UserCreateRequest = golem.CreateHookRequest[User]
type UserCreateResult = golem.CreateHookResult[User]
type UserUpdateRequest = golem.UpdateHookRequest[User]
type UserUpdateResult = golem.UpdateHookResult[User]
type UserDeleteRequest = golem.DeleteHookRequest[User]
type UserDeleteResult = golem.DeleteHookResult[User]
type UserUpdateManyRequest = golem.UpdateManyHookRequest[User]
type UserUpdateManyResult = golem.UpdateManyHookResult[User]
type UserDeleteManyRequest = golem.DeleteManyHookRequest[User]
type UserDeleteManyResult = golem.DeleteManyHookResult[User]

func golemBuildUserPolicy(actor Actor) (golem.FrozenPolicy, error) {
	rules := golem.NewRules[User]()
	User{}.DefinePolicy(rules, actor)
	return rules.Freeze(golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9})
}

func GolemGeneratedBindings() golem.PackageBindings[Actor] {
	policies := []golem.PolicyBinding[Actor]{
		golem.GeneratedPolicyBinding[Actor, User](golem.ModelID{0x2d, 0xde, 0xf4, 0x9e, 0xf5, 0xff, 0xc7, 0x8a, 0x73, 0xb3, 0x85, 0x91, 0x72, 0xb8, 0xe9, 0xe9}, golemBuildUserPolicy),
	}
	hooks := []golem.HookBinding[Actor]{}
	return golem.GeneratedStampedPackageBindings(golem.SchemaDigest{0x8f, 0xcc, 0x42, 0x93, 0x2f, 0xee, 0xf2, 0x3d, 0x8c, 0x0a, 0x0d, 0x5d, 0x10, 0xb8, 0xe0, 0x26, 0xef, 0x0e, 0xbc, 0xa6, 0x15, 0x2b, 0xc0, 0xb4, 0x5a, 0x13, 0x0c, 0xb8, 0xcd, 0xa2, 0x1b, 0xd7}, policies, hooks)
}
