// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p7-graphql-abi-v3; generation 869ab6c77cec0944b8a0fcb452a355c5dd0e4ff9e0893713e52f01c03a39b5cf; generator p1-v1; template p2-go-abi-v4.
package golemgqlgen

// THIS CODE WILL BE UPDATED WITH SCHEMA CHANGES. PREVIOUS IMPLEMENTATION FOR SCHEMA CHANGES WILL BE KEPT IN THE COMMENT SECTION. IMPLEMENTATION FOR UNCHANGED SCHEMA WILL BE KEPT.

import (
	"context"

	graphql1 "github.com/eleven-am/golem/go/graphql"
)

type Resolver struct{}

func (r *batchPayloadResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *categoryResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *categoryResolver) Name(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *categoryResolver) ParentID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *categoryResolver) Parent(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *categoryResolver) Children(ctx context.Context, obj graphql1.PreparedObject, where *CategoryWhereInput, orderBy []*CategoryOrderByInput, cursor *CategoryWhereUniqueInput, distinct []CategoryScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *categoryResolver) Metrics(ctx context.Context, obj graphql1.PreparedObject, where *MetricWhereInput, orderBy []*MetricOrderByInput, cursor *MetricWhereUniqueInput, distinct []MetricScalarField, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[[]graphql1.PreparedObject](ctx, obj)

}

func (r *categoryResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *categoryCountOutputResolver) Children(ctx context.Context, obj graphql1.PreparedObject, where *CategoryWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *categoryCountOutputResolver) Metrics(ctx context.Context, obj graphql1.PreparedObject, where *MetricWhereInput) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Flag(ctx context.Context, obj graphql1.PreparedObject) (*bool, error) {
	return graphql1.ResolvePreparedField[*bool](ctx, obj)

}

func (r *metricResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Label(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricResolver) Reference(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Day(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Clock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) OccurredAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) State(ctx context.Context, obj graphql1.PreparedObject) (*Status, error) {
	return graphql1.ResolvePreparedField[*Status](ctx, obj)

}

func (r *metricResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) OptionalLabel(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricResolver) OptionalDay(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) OptionalClock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) OptionalInstant(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) CategoryID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricResolver) Category(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAggregateResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricAggregateResolver) CountFields(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAggregateResolver) Sum(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAggregateResolver) Avg(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAggregateResolver) Min(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAggregateResolver) Max(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricAvgAggregateResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricAvgAggregateResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricAvgAggregateResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricAvgAggregateResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricAvgAggregateResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricAvgAggregateResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricAvgAggregateResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricAvgAggregateResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricCountAggregateResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) CategoryID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Clock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Day(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Flag(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Label(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OccurredAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalClock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalDay(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalInstant(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) OptionalLabel(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Reference(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricCountAggregateResolver) State(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupResolver) Key(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupResolver) Count(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupResolver) CountFields(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupResolver) Sum(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupResolver) Avg(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupResolver) Min(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupResolver) Max(ctx context.Context, obj graphql1.PreparedObject) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedField[graphql1.PreparedObject](ctx, obj)

}

func (r *metricGroupKeyResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) CategoryID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Clock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Day(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (float64, error) {
	return graphql1.ResolvePreparedField[float64](ctx, obj)

}

func (r *metricGroupKeyResolver) Flag(ctx context.Context, obj graphql1.PreparedObject) (bool, error) {
	return graphql1.ResolvePreparedField[bool](ctx, obj)

}

func (r *metricGroupKeyResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (float64, error) {
	return graphql1.ResolvePreparedField[float64](ctx, obj)

}

func (r *metricGroupKeyResolver) ID(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *metricGroupKeyResolver) Label(ctx context.Context, obj graphql1.PreparedObject) (string, error) {
	return graphql1.ResolvePreparedField[string](ctx, obj)

}

func (r *metricGroupKeyResolver) OccurredAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalClock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalDay(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalInstant(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) OptionalLabel(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricGroupKeyResolver) Reference(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricGroupKeyResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (int, error) {
	return graphql1.ResolvePreparedField[int](ctx, obj)

}

func (r *metricGroupKeyResolver) State(ctx context.Context, obj graphql1.PreparedObject) (Status, error) {
	return graphql1.ResolvePreparedField[Status](ctx, obj)

}

func (r *metricMaxAggregateResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) Clock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) Day(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricMaxAggregateResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricMaxAggregateResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricMaxAggregateResolver) Label(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricMaxAggregateResolver) OccurredAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalClock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalDay(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalInstant(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMaxAggregateResolver) OptionalLabel(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricMaxAggregateResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricMinAggregateResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) Clock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) Day(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricMinAggregateResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricMinAggregateResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricMinAggregateResolver) Label(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricMinAggregateResolver) OccurredAt(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalClock(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalDay(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalInstant(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricMinAggregateResolver) OptionalLabel(ctx context.Context, obj graphql1.PreparedObject) (*string, error) {
	return graphql1.ResolvePreparedField[*string](ctx, obj)

}

func (r *metricMinAggregateResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (*int, error) {
	return graphql1.ResolvePreparedField[*int](ctx, obj)

}

func (r *metricSumAggregateResolver) Amount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricSumAggregateResolver) Big(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricSumAggregateResolver) Double(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricSumAggregateResolver) Float(ctx context.Context, obj graphql1.PreparedObject) (*float64, error) {
	return graphql1.ResolvePreparedField[*float64](ctx, obj)

}

func (r *metricSumAggregateResolver) Integer(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricSumAggregateResolver) OptionalAmount(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricSumAggregateResolver) OptionalBig(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *metricSumAggregateResolver) Small(ctx context.Context, obj graphql1.PreparedObject) (any, error) {
	return graphql1.ResolvePreparedField[any](ctx, obj)

}

func (r *mutationResolver) CreateCategory(ctx context.Context, data CategoryCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *mutationResolver) CreateMetric(ctx context.Context, data MetricCreateInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) AggregateMetrics(ctx context.Context, where *MetricWhereInput) (graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[graphql1.PreparedObject](ctx)

}

func (r *queryResolver) GroupByMetrics(ctx context.Context, by []MetricGroupField, where *MetricWhereInput, having *MetricGroupHavingInput, orderBy []*MetricGroupOrderByInput, skip *int, take *int) ([]graphql1.PreparedObject, error) {
	return graphql1.ResolvePreparedRoot[[]graphql1.PreparedObject](ctx)

}

func (r *Resolver) BatchPayload() BatchPayloadResolver { return &batchPayloadResolver{r} }

func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

func (r *Resolver) CategoryCountOutput() CategoryCountOutputResolver {
	return &categoryCountOutputResolver{r}
}

func (r *Resolver) Metric() MetricResolver { return &metricResolver{r} }

func (r *Resolver) MetricAggregate() MetricAggregateResolver { return &metricAggregateResolver{r} }

func (r *Resolver) MetricAvgAggregate() MetricAvgAggregateResolver {
	return &metricAvgAggregateResolver{r}
}

func (r *Resolver) MetricCountAggregate() MetricCountAggregateResolver {
	return &metricCountAggregateResolver{r}
}

func (r *Resolver) MetricGroup() MetricGroupResolver { return &metricGroupResolver{r} }

func (r *Resolver) MetricGroupKey() MetricGroupKeyResolver { return &metricGroupKeyResolver{r} }

func (r *Resolver) MetricMaxAggregate() MetricMaxAggregateResolver {
	return &metricMaxAggregateResolver{r}
}

func (r *Resolver) MetricMinAggregate() MetricMinAggregateResolver {
	return &metricMinAggregateResolver{r}
}

func (r *Resolver) MetricSumAggregate() MetricSumAggregateResolver {
	return &metricSumAggregateResolver{r}
}

func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type batchPayloadResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type categoryCountOutputResolver struct{ *Resolver }
type metricResolver struct{ *Resolver }
type metricAggregateResolver struct{ *Resolver }
type metricAvgAggregateResolver struct{ *Resolver }
type metricCountAggregateResolver struct{ *Resolver }
type metricGroupResolver struct{ *Resolver }
type metricGroupKeyResolver struct{ *Resolver }
type metricMaxAggregateResolver struct{ *Resolver }
type metricMinAggregateResolver struct{ *Resolver }
type metricSumAggregateResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
