// Code generated by golem. DO NOT EDIT.
// gqlgen v0.17.70; GraphQL ABI p7-graphql-abi-v3; generation 869ab6c77cec0944b8a0fcb452a355c5dd0e4ff9e0893713e52f01c03a39b5cf; generator p1-v1; template p2-go-abi-v4.

package golemgqlgen

import (
	"fmt"
	"io"
	"strconv"
)

type BigIntAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type BigIntFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type BigIntListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type BigIntListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type BigIntUpdateOperationsInput struct {
	Set       any `json:"set,omitempty"`
	Increment any `json:"increment,omitempty"`
	Decrement any `json:"decrement,omitempty"`
}

type BooleanAnalyticsFilter struct {
	Equals *bool `json:"equals,omitempty"`
	Not    *bool `json:"not,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type BooleanFilter struct {
	Equals *bool  `json:"equals,omitempty"`
	Not    *bool  `json:"not,omitempty"`
	In     []bool `json:"in,omitempty"`
	NotIn  []bool `json:"notIn,omitempty"`
}

type BooleanListFilter struct {
	Equals   []bool `json:"equals,omitempty"`
	Has      *bool  `json:"has,omitempty"`
	HasEvery []bool `json:"hasEvery,omitempty"`
	HasSome  []bool `json:"hasSome,omitempty"`
	IsEmpty  *bool  `json:"isEmpty,omitempty"`
}

type BooleanListUpdateOperationsInput struct {
	Set []bool `json:"set,omitempty"`
}

type BooleanUpdateOperationsInput struct {
	Set *bool `json:"set,omitempty"`
}

type BytesFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
}

type BytesUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type CategoryChildrenCreateRelationInput struct {
	Create          []*CategoryCreateWithoutParentInput          `json:"create,omitempty"`
	CreateMany      []*CategoryCreateWithoutParentInput          `json:"createMany,omitempty"`
	Connect         []*CategoryWhereUniqueInput                  `json:"connect,omitempty"`
	ConnectOrCreate []*CategoryConnectOrCreateWithoutParentInput `json:"connectOrCreate,omitempty"`
}

type CategoryChildrenUpdateRelationInput struct {
	Create          []*CategoryCreateWithoutParentInput              `json:"create,omitempty"`
	CreateMany      []*CategoryCreateWithoutParentInput              `json:"createMany,omitempty"`
	Connect         []*CategoryWhereUniqueInput                      `json:"connect,omitempty"`
	Disconnect      []*CategoryWhereUniqueInput                      `json:"disconnect,omitempty"`
	Set             []*CategoryWhereUniqueInput                      `json:"set,omitempty"`
	Delete          []*CategoryWhereUniqueInput                      `json:"delete,omitempty"`
	DeleteMany      []*CategoryWhereInput                            `json:"deleteMany,omitempty"`
	ConnectOrCreate []*CategoryConnectOrCreateWithoutParentInput     `json:"connectOrCreate,omitempty"`
	Update          []*CategoryUpdateWithWhereWithoutParentInput     `json:"update,omitempty"`
	UpdateMany      []*CategoryUpdateManyWithWhereWithoutParentInput `json:"updateMany,omitempty"`
	Upsert          []*CategoryUpsertWithWhereWithoutParentInput     `json:"upsert,omitempty"`
}

type CategoryConnectOrCreateWithoutChildrenInput struct {
	Where  *CategoryWhereUniqueInput           `json:"where"`
	Create *CategoryCreateWithoutChildrenInput `json:"create"`
}

type CategoryConnectOrCreateWithoutMetricsInput struct {
	Where  *CategoryWhereUniqueInput          `json:"where"`
	Create *CategoryCreateWithoutMetricsInput `json:"create"`
}

type CategoryConnectOrCreateWithoutParentInput struct {
	Where  *CategoryWhereUniqueInput         `json:"where"`
	Create *CategoryCreateWithoutParentInput `json:"create"`
}

type CategoryCreateInput struct {
	ID       any                                  `json:"id"`
	Name     string                               `json:"name"`
	Parent   *CategoryParentCreateRelationInput   `json:"parent,omitempty"`
	Children *CategoryChildrenCreateRelationInput `json:"children,omitempty"`
	Metrics  *CategoryMetricsCreateRelationInput  `json:"metrics,omitempty"`
}

type CategoryCreateWithoutChildrenInput struct {
	ID      any                                 `json:"id"`
	Name    string                              `json:"name"`
	Parent  *CategoryParentCreateRelationInput  `json:"parent,omitempty"`
	Metrics *CategoryMetricsCreateRelationInput `json:"metrics,omitempty"`
}

type CategoryCreateWithoutMetricsInput struct {
	ID       any                                  `json:"id"`
	Name     string                               `json:"name"`
	Parent   *CategoryParentCreateRelationInput   `json:"parent,omitempty"`
	Children *CategoryChildrenCreateRelationInput `json:"children,omitempty"`
}

type CategoryCreateWithoutParentInput struct {
	ID       any                                  `json:"id"`
	Name     string                               `json:"name"`
	Children *CategoryChildrenCreateRelationInput `json:"children,omitempty"`
	Metrics  *CategoryMetricsCreateRelationInput  `json:"metrics,omitempty"`
}

type CategoryListRelationFilter struct {
	Some  *CategoryWhereInput `json:"some,omitempty"`
	Every *CategoryWhereInput `json:"every,omitempty"`
	None  *CategoryWhereInput `json:"none,omitempty"`
}

type CategoryMetricsCreateRelationInput struct {
	Create          []*MetricCreateWithoutCategoryInput          `json:"create,omitempty"`
	CreateMany      []*MetricCreateWithoutCategoryInput          `json:"createMany,omitempty"`
	Connect         []*MetricWhereUniqueInput                    `json:"connect,omitempty"`
	ConnectOrCreate []*MetricConnectOrCreateWithoutCategoryInput `json:"connectOrCreate,omitempty"`
}

type CategoryMetricsUpdateRelationInput struct {
	Create          []*MetricCreateWithoutCategoryInput              `json:"create,omitempty"`
	CreateMany      []*MetricCreateWithoutCategoryInput              `json:"createMany,omitempty"`
	Connect         []*MetricWhereUniqueInput                        `json:"connect,omitempty"`
	Disconnect      []*MetricWhereUniqueInput                        `json:"disconnect,omitempty"`
	Set             []*MetricWhereUniqueInput                        `json:"set,omitempty"`
	Delete          []*MetricWhereUniqueInput                        `json:"delete,omitempty"`
	DeleteMany      []*MetricWhereInput                              `json:"deleteMany,omitempty"`
	ConnectOrCreate []*MetricConnectOrCreateWithoutCategoryInput     `json:"connectOrCreate,omitempty"`
	Update          []*MetricUpdateWithWhereWithoutCategoryInput     `json:"update,omitempty"`
	UpdateMany      []*MetricUpdateManyWithWhereWithoutCategoryInput `json:"updateMany,omitempty"`
	Upsert          []*MetricUpsertWithWhereWithoutCategoryInput     `json:"upsert,omitempty"`
}

type CategoryOrderByInput struct {
	ID       *SortOrder `json:"id,omitempty"`
	Name     *SortOrder `json:"name,omitempty"`
	ParentID *SortOrder `json:"parentID,omitempty"`
}

type CategoryParentCreateRelationInput struct {
	Create          *CategoryCreateWithoutChildrenInput          `json:"create,omitempty"`
	Connect         *CategoryWhereUniqueInput                    `json:"connect,omitempty"`
	ConnectOrCreate *CategoryConnectOrCreateWithoutChildrenInput `json:"connectOrCreate,omitempty"`
}

type CategoryParentUpdateRelationInput struct {
	Create          *CategoryCreateWithoutChildrenInput          `json:"create,omitempty"`
	Connect         *CategoryWhereUniqueInput                    `json:"connect,omitempty"`
	ConnectOrCreate *CategoryConnectOrCreateWithoutChildrenInput `json:"connectOrCreate,omitempty"`
	Update          *CategoryUpdateWithoutChildrenInput          `json:"update,omitempty"`
	Upsert          *CategoryUpsertWithoutChildrenInput          `json:"upsert,omitempty"`
	Disconnect      *bool                                        `json:"disconnect,omitempty"`
	Delete          *bool                                        `json:"delete,omitempty"`
}

type CategoryRelationFilter struct {
	Is    *CategoryWhereInput `json:"is,omitempty"`
	IsNot *CategoryWhereInput `json:"isNot,omitempty"`
}

type CategoryUpdateInput struct {
	ID       *UUIDUpdateOperationsInput           `json:"id,omitempty"`
	Name     *StringUpdateOperationsInput         `json:"name,omitempty"`
	Parent   *CategoryParentUpdateRelationInput   `json:"parent,omitempty"`
	Children *CategoryChildrenUpdateRelationInput `json:"children,omitempty"`
	Metrics  *CategoryMetricsUpdateRelationInput  `json:"metrics,omitempty"`
}

type CategoryUpdateManyInput struct {
	ID       *UUIDUpdateOperationsInput         `json:"id,omitempty"`
	Name     *StringUpdateOperationsInput       `json:"name,omitempty"`
	ParentID *NullableUUIDUpdateOperationsInput `json:"parentID,omitempty"`
}

type CategoryUpdateManyWithWhereWithoutParentInput struct {
	Where *CategoryWhereInput      `json:"where"`
	Data  *CategoryUpdateManyInput `json:"data"`
}

type CategoryUpdateWithWhereWithoutParentInput struct {
	Where *CategoryWhereUniqueInput         `json:"where"`
	Data  *CategoryUpdateWithoutParentInput `json:"data"`
}

type CategoryUpdateWithoutChildrenInput struct {
	ID      *UUIDUpdateOperationsInput          `json:"id,omitempty"`
	Name    *StringUpdateOperationsInput        `json:"name,omitempty"`
	Parent  *CategoryParentUpdateRelationInput  `json:"parent,omitempty"`
	Metrics *CategoryMetricsUpdateRelationInput `json:"metrics,omitempty"`
}

type CategoryUpdateWithoutMetricsInput struct {
	ID       *UUIDUpdateOperationsInput           `json:"id,omitempty"`
	Name     *StringUpdateOperationsInput         `json:"name,omitempty"`
	Parent   *CategoryParentUpdateRelationInput   `json:"parent,omitempty"`
	Children *CategoryChildrenUpdateRelationInput `json:"children,omitempty"`
}

type CategoryUpdateWithoutParentInput struct {
	ID       *UUIDUpdateOperationsInput           `json:"id,omitempty"`
	Name     *StringUpdateOperationsInput         `json:"name,omitempty"`
	Children *CategoryChildrenUpdateRelationInput `json:"children,omitempty"`
	Metrics  *CategoryMetricsUpdateRelationInput  `json:"metrics,omitempty"`
}

type CategoryUpsertWithWhereWithoutParentInput struct {
	Where  *CategoryWhereUniqueInput         `json:"where"`
	Create *CategoryCreateWithoutParentInput `json:"create"`
	Update *CategoryUpdateWithoutParentInput `json:"update"`
}

type CategoryUpsertWithoutChildrenInput struct {
	Create *CategoryCreateWithoutChildrenInput `json:"create"`
	Update *CategoryUpdateWithoutChildrenInput `json:"update"`
}

type CategoryUpsertWithoutMetricsInput struct {
	Create *CategoryCreateWithoutMetricsInput `json:"create"`
	Update *CategoryUpdateWithoutMetricsInput `json:"update"`
}

type CategoryWhereInput struct {
	All      *bool                       `json:"all,omitempty"`
	And      []*CategoryWhereInput       `json:"AND,omitempty"`
	Or       []*CategoryWhereInput       `json:"OR,omitempty"`
	Not      []*CategoryWhereInput       `json:"NOT,omitempty"`
	ID       *UUIDFilter                 `json:"id,omitempty"`
	Name     *StringFilter               `json:"name,omitempty"`
	ParentID *NullableUUIDFilter         `json:"parentID,omitempty"`
	Parent   *CategoryRelationFilter     `json:"parent,omitempty"`
	Children *CategoryListRelationFilter `json:"children,omitempty"`
	Metrics  *MetricListRelationFilter   `json:"metrics,omitempty"`
}

type CategoryWhereUniqueInput struct {
	ID any `json:"ID,omitempty"`
}

type DateAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DateFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DateListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DateListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DateTimeAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DateTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DateTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DateTimeListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DateTimeUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type DateUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type DecimalAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type DecimalFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type DecimalListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type DecimalListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type DecimalUpdateOperationsInput struct {
	Set       any `json:"set,omitempty"`
	Increment any `json:"increment,omitempty"`
	Decrement any `json:"decrement,omitempty"`
}

type FloatAnalyticsFilter struct {
	Equals *float64 `json:"equals,omitempty"`
	Not    *float64 `json:"not,omitempty"`
	Lt     *float64 `json:"lt,omitempty"`
	Lte    *float64 `json:"lte,omitempty"`
	Gt     *float64 `json:"gt,omitempty"`
	Gte    *float64 `json:"gte,omitempty"`
	IsNull *bool    `json:"isNull,omitempty"`
}

type FloatFilter struct {
	Equals *float64  `json:"equals,omitempty"`
	Not    *float64  `json:"not,omitempty"`
	In     []float64 `json:"in,omitempty"`
	NotIn  []float64 `json:"notIn,omitempty"`
	Lt     *float64  `json:"lt,omitempty"`
	Lte    *float64  `json:"lte,omitempty"`
	Gt     *float64  `json:"gt,omitempty"`
	Gte    *float64  `json:"gte,omitempty"`
}

type FloatListFilter struct {
	Equals   []float64 `json:"equals,omitempty"`
	Has      *float64  `json:"has,omitempty"`
	HasEvery []float64 `json:"hasEvery,omitempty"`
	HasSome  []float64 `json:"hasSome,omitempty"`
	IsEmpty  *bool     `json:"isEmpty,omitempty"`
}

type FloatListUpdateOperationsInput struct {
	Set []float64 `json:"set,omitempty"`
}

type FloatUpdateOperationsInput struct {
	Set       *float64 `json:"set,omitempty"`
	Increment *float64 `json:"increment,omitempty"`
	Decrement *float64 `json:"decrement,omitempty"`
}

type IntAnalyticsFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type IntFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	In     []int `json:"in,omitempty"`
	NotIn  []int `json:"notIn,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
}

type IntListFilter struct {
	Equals   []int `json:"equals,omitempty"`
	Has      *int  `json:"has,omitempty"`
	HasEvery []int `json:"hasEvery,omitempty"`
	HasSome  []int `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type IntListUpdateOperationsInput struct {
	Set []int `json:"set,omitempty"`
}

type IntUpdateOperationsInput struct {
	Set       *int `json:"set,omitempty"`
	Increment *int `json:"increment,omitempty"`
	Decrement *int `json:"decrement,omitempty"`
}

type JSONFilter struct {
	Equals           any        `json:"equals,omitempty"`
	Not              any        `json:"not,omitempty"`
	Lt               any        `json:"lt,omitempty"`
	Lte              any        `json:"lte,omitempty"`
	Gt               any        `json:"gt,omitempty"`
	Gte              any        `json:"gte,omitempty"`
	StringContains   *string    `json:"stringContains,omitempty"`
	StringStartsWith *string    `json:"stringStartsWith,omitempty"`
	StringEndsWith   *string    `json:"stringEndsWith,omitempty"`
	ArrayContains    any        `json:"arrayContains,omitempty"`
	ArrayStartsWith  any        `json:"arrayStartsWith,omitempty"`
	ArrayEndsWith    any        `json:"arrayEndsWith,omitempty"`
	Path             []string   `json:"path,omitempty"`
	Mode             *QueryMode `json:"mode,omitempty"`
}

type JSONUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type MetricAvgAggregateHavingInput struct {
	Amount         *DecimalAnalyticsFilter `json:"amount,omitempty"`
	Big            *FloatAnalyticsFilter   `json:"big,omitempty"`
	Double         *FloatAnalyticsFilter   `json:"double,omitempty"`
	Float          *FloatAnalyticsFilter   `json:"float,omitempty"`
	Integer        *FloatAnalyticsFilter   `json:"integer,omitempty"`
	OptionalAmount *DecimalAnalyticsFilter `json:"optionalAmount,omitempty"`
	OptionalBig    *FloatAnalyticsFilter   `json:"optionalBig,omitempty"`
	Small          *FloatAnalyticsFilter   `json:"small,omitempty"`
}

type MetricAvgAggregateOrderByInput struct {
	Amount         *SortOrder `json:"amount,omitempty"`
	Big            *SortOrder `json:"big,omitempty"`
	Double         *SortOrder `json:"double,omitempty"`
	Float          *SortOrder `json:"float,omitempty"`
	Integer        *SortOrder `json:"integer,omitempty"`
	OptionalAmount *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig    *SortOrder `json:"optionalBig,omitempty"`
	Small          *SortOrder `json:"small,omitempty"`
}

type MetricCategoryCreateRelationInput struct {
	Create          *CategoryCreateWithoutMetricsInput          `json:"create,omitempty"`
	Connect         *CategoryWhereUniqueInput                   `json:"connect,omitempty"`
	ConnectOrCreate *CategoryConnectOrCreateWithoutMetricsInput `json:"connectOrCreate,omitempty"`
}

type MetricCategoryUpdateRelationInput struct {
	Create          *CategoryCreateWithoutMetricsInput          `json:"create,omitempty"`
	Connect         *CategoryWhereUniqueInput                   `json:"connect,omitempty"`
	ConnectOrCreate *CategoryConnectOrCreateWithoutMetricsInput `json:"connectOrCreate,omitempty"`
	Update          *CategoryUpdateWithoutMetricsInput          `json:"update,omitempty"`
	Upsert          *CategoryUpsertWithoutMetricsInput          `json:"upsert,omitempty"`
	Disconnect      *bool                                       `json:"disconnect,omitempty"`
	Delete          *bool                                       `json:"delete,omitempty"`
}

type MetricConnectOrCreateWithoutCategoryInput struct {
	Where  *MetricWhereUniqueInput           `json:"where"`
	Create *MetricCreateWithoutCategoryInput `json:"create"`
}

type MetricCountAggregateHavingInput struct {
	Amount          *BigIntAnalyticsFilter `json:"amount,omitempty"`
	Big             *BigIntAnalyticsFilter `json:"big,omitempty"`
	CategoryID      *BigIntAnalyticsFilter `json:"categoryID,omitempty"`
	Clock           *BigIntAnalyticsFilter `json:"clock,omitempty"`
	Day             *BigIntAnalyticsFilter `json:"day,omitempty"`
	Double          *BigIntAnalyticsFilter `json:"double,omitempty"`
	Flag            *BigIntAnalyticsFilter `json:"flag,omitempty"`
	Float           *BigIntAnalyticsFilter `json:"float,omitempty"`
	ID              *BigIntAnalyticsFilter `json:"id,omitempty"`
	Integer         *BigIntAnalyticsFilter `json:"integer,omitempty"`
	Label           *BigIntAnalyticsFilter `json:"label,omitempty"`
	OccurredAt      *BigIntAnalyticsFilter `json:"occurredAt,omitempty"`
	OptionalAmount  *BigIntAnalyticsFilter `json:"optionalAmount,omitempty"`
	OptionalBig     *BigIntAnalyticsFilter `json:"optionalBig,omitempty"`
	OptionalClock   *BigIntAnalyticsFilter `json:"optionalClock,omitempty"`
	OptionalDay     *BigIntAnalyticsFilter `json:"optionalDay,omitempty"`
	OptionalInstant *BigIntAnalyticsFilter `json:"optionalInstant,omitempty"`
	OptionalLabel   *BigIntAnalyticsFilter `json:"optionalLabel,omitempty"`
	Reference       *BigIntAnalyticsFilter `json:"reference,omitempty"`
	Small           *BigIntAnalyticsFilter `json:"small,omitempty"`
	State           *BigIntAnalyticsFilter `json:"state,omitempty"`
}

type MetricCountAggregateOrderByInput struct {
	Amount          *SortOrder `json:"amount,omitempty"`
	Big             *SortOrder `json:"big,omitempty"`
	CategoryID      *SortOrder `json:"categoryID,omitempty"`
	Clock           *SortOrder `json:"clock,omitempty"`
	Day             *SortOrder `json:"day,omitempty"`
	Double          *SortOrder `json:"double,omitempty"`
	Flag            *SortOrder `json:"flag,omitempty"`
	Float           *SortOrder `json:"float,omitempty"`
	ID              *SortOrder `json:"id,omitempty"`
	Integer         *SortOrder `json:"integer,omitempty"`
	Label           *SortOrder `json:"label,omitempty"`
	OccurredAt      *SortOrder `json:"occurredAt,omitempty"`
	OptionalAmount  *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig     *SortOrder `json:"optionalBig,omitempty"`
	OptionalClock   *SortOrder `json:"optionalClock,omitempty"`
	OptionalDay     *SortOrder `json:"optionalDay,omitempty"`
	OptionalInstant *SortOrder `json:"optionalInstant,omitempty"`
	OptionalLabel   *SortOrder `json:"optionalLabel,omitempty"`
	Reference       *SortOrder `json:"reference,omitempty"`
	Small           *SortOrder `json:"small,omitempty"`
	State           *SortOrder `json:"state,omitempty"`
}

type MetricCreateInput struct {
	ID              any                                `json:"id"`
	Flag            bool                               `json:"flag"`
	Small           int                                `json:"small"`
	Integer         int                                `json:"integer"`
	Big             any                                `json:"big"`
	Float           float64                            `json:"float"`
	Double          float64                            `json:"double"`
	Amount          any                                `json:"amount"`
	Label           string                             `json:"label"`
	Reference       any                                `json:"reference"`
	Day             any                                `json:"day"`
	Clock           any                                `json:"clock"`
	OccurredAt      any                                `json:"occurredAt"`
	State           Status                             `json:"state"`
	OptionalBig     any                                `json:"optionalBig,omitempty"`
	OptionalAmount  any                                `json:"optionalAmount,omitempty"`
	OptionalLabel   *string                            `json:"optionalLabel,omitempty"`
	OptionalDay     any                                `json:"optionalDay,omitempty"`
	OptionalClock   any                                `json:"optionalClock,omitempty"`
	OptionalInstant any                                `json:"optionalInstant,omitempty"`
	Category        *MetricCategoryCreateRelationInput `json:"category,omitempty"`
}

type MetricCreateWithoutCategoryInput struct {
	ID              any     `json:"id"`
	Flag            bool    `json:"flag"`
	Small           int     `json:"small"`
	Integer         int     `json:"integer"`
	Big             any     `json:"big"`
	Float           float64 `json:"float"`
	Double          float64 `json:"double"`
	Amount          any     `json:"amount"`
	Label           string  `json:"label"`
	Reference       any     `json:"reference"`
	Day             any     `json:"day"`
	Clock           any     `json:"clock"`
	OccurredAt      any     `json:"occurredAt"`
	State           Status  `json:"state"`
	OptionalBig     any     `json:"optionalBig,omitempty"`
	OptionalAmount  any     `json:"optionalAmount,omitempty"`
	OptionalLabel   *string `json:"optionalLabel,omitempty"`
	OptionalDay     any     `json:"optionalDay,omitempty"`
	OptionalClock   any     `json:"optionalClock,omitempty"`
	OptionalInstant any     `json:"optionalInstant,omitempty"`
}

type MetricGroupHavingInput struct {
	And         []*MetricGroupHavingInput        `json:"AND,omitempty"`
	Or          []*MetricGroupHavingInput        `json:"OR,omitempty"`
	Not         *MetricGroupHavingInput          `json:"NOT,omitempty"`
	Key         *MetricGroupKeyHavingInput       `json:"key,omitempty"`
	Count       *BigIntAnalyticsFilter           `json:"count,omitempty"`
	CountFields *MetricCountAggregateHavingInput `json:"countFields,omitempty"`
	Sum         *MetricSumAggregateHavingInput   `json:"sum,omitempty"`
	Avg         *MetricAvgAggregateHavingInput   `json:"avg,omitempty"`
	Min         *MetricMinAggregateHavingInput   `json:"min,omitempty"`
	Max         *MetricMaxAggregateHavingInput   `json:"max,omitempty"`
}

type MetricGroupKeyHavingInput struct {
	Amount          *DecimalAnalyticsFilter  `json:"amount,omitempty"`
	Big             *BigIntAnalyticsFilter   `json:"big,omitempty"`
	CategoryID      *UUIDAnalyticsFilter     `json:"categoryID,omitempty"`
	Clock           *TimeAnalyticsFilter     `json:"clock,omitempty"`
	Day             *DateAnalyticsFilter     `json:"day,omitempty"`
	Double          *FloatAnalyticsFilter    `json:"double,omitempty"`
	Flag            *BooleanAnalyticsFilter  `json:"flag,omitempty"`
	Float           *FloatAnalyticsFilter    `json:"float,omitempty"`
	ID              *UUIDAnalyticsFilter     `json:"id,omitempty"`
	Integer         *IntAnalyticsFilter      `json:"integer,omitempty"`
	Label           *StringAnalyticsFilter   `json:"label,omitempty"`
	OccurredAt      *DateTimeAnalyticsFilter `json:"occurredAt,omitempty"`
	OptionalAmount  *DecimalAnalyticsFilter  `json:"optionalAmount,omitempty"`
	OptionalBig     *BigIntAnalyticsFilter   `json:"optionalBig,omitempty"`
	OptionalClock   *TimeAnalyticsFilter     `json:"optionalClock,omitempty"`
	OptionalDay     *DateAnalyticsFilter     `json:"optionalDay,omitempty"`
	OptionalInstant *DateTimeAnalyticsFilter `json:"optionalInstant,omitempty"`
	OptionalLabel   *StringAnalyticsFilter   `json:"optionalLabel,omitempty"`
	Reference       *UUIDAnalyticsFilter     `json:"reference,omitempty"`
	Small           *IntAnalyticsFilter      `json:"small,omitempty"`
	State           *StatusAnalyticsFilter   `json:"state,omitempty"`
}

type MetricGroupKeyOrderByInput struct {
	Amount          *SortOrder `json:"amount,omitempty"`
	Big             *SortOrder `json:"big,omitempty"`
	CategoryID      *SortOrder `json:"categoryID,omitempty"`
	Clock           *SortOrder `json:"clock,omitempty"`
	Day             *SortOrder `json:"day,omitempty"`
	Double          *SortOrder `json:"double,omitempty"`
	Flag            *SortOrder `json:"flag,omitempty"`
	Float           *SortOrder `json:"float,omitempty"`
	ID              *SortOrder `json:"id,omitempty"`
	Integer         *SortOrder `json:"integer,omitempty"`
	Label           *SortOrder `json:"label,omitempty"`
	OccurredAt      *SortOrder `json:"occurredAt,omitempty"`
	OptionalAmount  *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig     *SortOrder `json:"optionalBig,omitempty"`
	OptionalClock   *SortOrder `json:"optionalClock,omitempty"`
	OptionalDay     *SortOrder `json:"optionalDay,omitempty"`
	OptionalInstant *SortOrder `json:"optionalInstant,omitempty"`
	OptionalLabel   *SortOrder `json:"optionalLabel,omitempty"`
	Reference       *SortOrder `json:"reference,omitempty"`
	Small           *SortOrder `json:"small,omitempty"`
	State           *SortOrder `json:"state,omitempty"`
}

type MetricGroupOrderByInput struct {
	Key         *MetricGroupKeyOrderByInput       `json:"key,omitempty"`
	Count       *SortOrder                        `json:"count,omitempty"`
	CountFields *MetricCountAggregateOrderByInput `json:"countFields,omitempty"`
	Sum         *MetricSumAggregateOrderByInput   `json:"sum,omitempty"`
	Avg         *MetricAvgAggregateOrderByInput   `json:"avg,omitempty"`
	Min         *MetricMinAggregateOrderByInput   `json:"min,omitempty"`
	Max         *MetricMaxAggregateOrderByInput   `json:"max,omitempty"`
}

type MetricListRelationFilter struct {
	Some  *MetricWhereInput `json:"some,omitempty"`
	Every *MetricWhereInput `json:"every,omitempty"`
	None  *MetricWhereInput `json:"none,omitempty"`
}

type MetricMaxAggregateHavingInput struct {
	Amount          *DecimalAnalyticsFilter  `json:"amount,omitempty"`
	Big             *BigIntAnalyticsFilter   `json:"big,omitempty"`
	Clock           *TimeAnalyticsFilter     `json:"clock,omitempty"`
	Day             *DateAnalyticsFilter     `json:"day,omitempty"`
	Double          *FloatAnalyticsFilter    `json:"double,omitempty"`
	Float           *FloatAnalyticsFilter    `json:"float,omitempty"`
	Integer         *IntAnalyticsFilter      `json:"integer,omitempty"`
	Label           *StringAnalyticsFilter   `json:"label,omitempty"`
	OccurredAt      *DateTimeAnalyticsFilter `json:"occurredAt,omitempty"`
	OptionalAmount  *DecimalAnalyticsFilter  `json:"optionalAmount,omitempty"`
	OptionalBig     *BigIntAnalyticsFilter   `json:"optionalBig,omitempty"`
	OptionalClock   *TimeAnalyticsFilter     `json:"optionalClock,omitempty"`
	OptionalDay     *DateAnalyticsFilter     `json:"optionalDay,omitempty"`
	OptionalInstant *DateTimeAnalyticsFilter `json:"optionalInstant,omitempty"`
	OptionalLabel   *StringAnalyticsFilter   `json:"optionalLabel,omitempty"`
	Small           *IntAnalyticsFilter      `json:"small,omitempty"`
}

type MetricMaxAggregateOrderByInput struct {
	Amount          *SortOrder `json:"amount,omitempty"`
	Big             *SortOrder `json:"big,omitempty"`
	Clock           *SortOrder `json:"clock,omitempty"`
	Day             *SortOrder `json:"day,omitempty"`
	Double          *SortOrder `json:"double,omitempty"`
	Float           *SortOrder `json:"float,omitempty"`
	Integer         *SortOrder `json:"integer,omitempty"`
	Label           *SortOrder `json:"label,omitempty"`
	OccurredAt      *SortOrder `json:"occurredAt,omitempty"`
	OptionalAmount  *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig     *SortOrder `json:"optionalBig,omitempty"`
	OptionalClock   *SortOrder `json:"optionalClock,omitempty"`
	OptionalDay     *SortOrder `json:"optionalDay,omitempty"`
	OptionalInstant *SortOrder `json:"optionalInstant,omitempty"`
	OptionalLabel   *SortOrder `json:"optionalLabel,omitempty"`
	Small           *SortOrder `json:"small,omitempty"`
}

type MetricMinAggregateHavingInput struct {
	Amount          *DecimalAnalyticsFilter  `json:"amount,omitempty"`
	Big             *BigIntAnalyticsFilter   `json:"big,omitempty"`
	Clock           *TimeAnalyticsFilter     `json:"clock,omitempty"`
	Day             *DateAnalyticsFilter     `json:"day,omitempty"`
	Double          *FloatAnalyticsFilter    `json:"double,omitempty"`
	Float           *FloatAnalyticsFilter    `json:"float,omitempty"`
	Integer         *IntAnalyticsFilter      `json:"integer,omitempty"`
	Label           *StringAnalyticsFilter   `json:"label,omitempty"`
	OccurredAt      *DateTimeAnalyticsFilter `json:"occurredAt,omitempty"`
	OptionalAmount  *DecimalAnalyticsFilter  `json:"optionalAmount,omitempty"`
	OptionalBig     *BigIntAnalyticsFilter   `json:"optionalBig,omitempty"`
	OptionalClock   *TimeAnalyticsFilter     `json:"optionalClock,omitempty"`
	OptionalDay     *DateAnalyticsFilter     `json:"optionalDay,omitempty"`
	OptionalInstant *DateTimeAnalyticsFilter `json:"optionalInstant,omitempty"`
	OptionalLabel   *StringAnalyticsFilter   `json:"optionalLabel,omitempty"`
	Small           *IntAnalyticsFilter      `json:"small,omitempty"`
}

type MetricMinAggregateOrderByInput struct {
	Amount          *SortOrder `json:"amount,omitempty"`
	Big             *SortOrder `json:"big,omitempty"`
	Clock           *SortOrder `json:"clock,omitempty"`
	Day             *SortOrder `json:"day,omitempty"`
	Double          *SortOrder `json:"double,omitempty"`
	Float           *SortOrder `json:"float,omitempty"`
	Integer         *SortOrder `json:"integer,omitempty"`
	Label           *SortOrder `json:"label,omitempty"`
	OccurredAt      *SortOrder `json:"occurredAt,omitempty"`
	OptionalAmount  *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig     *SortOrder `json:"optionalBig,omitempty"`
	OptionalClock   *SortOrder `json:"optionalClock,omitempty"`
	OptionalDay     *SortOrder `json:"optionalDay,omitempty"`
	OptionalInstant *SortOrder `json:"optionalInstant,omitempty"`
	OptionalLabel   *SortOrder `json:"optionalLabel,omitempty"`
	Small           *SortOrder `json:"small,omitempty"`
}

type MetricOrderByInput struct {
	ID              *SortOrder `json:"id,omitempty"`
	Flag            *SortOrder `json:"flag,omitempty"`
	Small           *SortOrder `json:"small,omitempty"`
	Integer         *SortOrder `json:"integer,omitempty"`
	Big             *SortOrder `json:"big,omitempty"`
	Float           *SortOrder `json:"float,omitempty"`
	Double          *SortOrder `json:"double,omitempty"`
	Amount          *SortOrder `json:"amount,omitempty"`
	Label           *SortOrder `json:"label,omitempty"`
	Reference       *SortOrder `json:"reference,omitempty"`
	Day             *SortOrder `json:"day,omitempty"`
	Clock           *SortOrder `json:"clock,omitempty"`
	OccurredAt      *SortOrder `json:"occurredAt,omitempty"`
	State           *SortOrder `json:"state,omitempty"`
	OptionalBig     *SortOrder `json:"optionalBig,omitempty"`
	OptionalAmount  *SortOrder `json:"optionalAmount,omitempty"`
	OptionalLabel   *SortOrder `json:"optionalLabel,omitempty"`
	OptionalDay     *SortOrder `json:"optionalDay,omitempty"`
	OptionalClock   *SortOrder `json:"optionalClock,omitempty"`
	OptionalInstant *SortOrder `json:"optionalInstant,omitempty"`
	CategoryID      *SortOrder `json:"categoryID,omitempty"`
}

type MetricSumAggregateHavingInput struct {
	Amount         *DecimalAnalyticsFilter `json:"amount,omitempty"`
	Big            *BigIntAnalyticsFilter  `json:"big,omitempty"`
	Double         *FloatAnalyticsFilter   `json:"double,omitempty"`
	Float          *FloatAnalyticsFilter   `json:"float,omitempty"`
	Integer        *BigIntAnalyticsFilter  `json:"integer,omitempty"`
	OptionalAmount *DecimalAnalyticsFilter `json:"optionalAmount,omitempty"`
	OptionalBig    *BigIntAnalyticsFilter  `json:"optionalBig,omitempty"`
	Small          *BigIntAnalyticsFilter  `json:"small,omitempty"`
}

type MetricSumAggregateOrderByInput struct {
	Amount         *SortOrder `json:"amount,omitempty"`
	Big            *SortOrder `json:"big,omitempty"`
	Double         *SortOrder `json:"double,omitempty"`
	Float          *SortOrder `json:"float,omitempty"`
	Integer        *SortOrder `json:"integer,omitempty"`
	OptionalAmount *SortOrder `json:"optionalAmount,omitempty"`
	OptionalBig    *SortOrder `json:"optionalBig,omitempty"`
	Small          *SortOrder `json:"small,omitempty"`
}

type MetricUpdateInput struct {
	ID              *UUIDUpdateOperationsInput             `json:"id,omitempty"`
	Flag            *BooleanUpdateOperationsInput          `json:"flag,omitempty"`
	Small           *IntUpdateOperationsInput              `json:"small,omitempty"`
	Integer         *IntUpdateOperationsInput              `json:"integer,omitempty"`
	Big             *BigIntUpdateOperationsInput           `json:"big,omitempty"`
	Float           *FloatUpdateOperationsInput            `json:"float,omitempty"`
	Double          *FloatUpdateOperationsInput            `json:"double,omitempty"`
	Amount          *DecimalUpdateOperationsInput          `json:"amount,omitempty"`
	Label           *StringUpdateOperationsInput           `json:"label,omitempty"`
	Reference       *UUIDUpdateOperationsInput             `json:"reference,omitempty"`
	Day             *DateUpdateOperationsInput             `json:"day,omitempty"`
	Clock           *TimeUpdateOperationsInput             `json:"clock,omitempty"`
	OccurredAt      *DateTimeUpdateOperationsInput         `json:"occurredAt,omitempty"`
	State           *StatusUpdateOperationsInput           `json:"state,omitempty"`
	OptionalBig     *NullableBigIntUpdateOperationsInput   `json:"optionalBig,omitempty"`
	OptionalAmount  *NullableDecimalUpdateOperationsInput  `json:"optionalAmount,omitempty"`
	OptionalLabel   *NullableStringUpdateOperationsInput   `json:"optionalLabel,omitempty"`
	OptionalDay     *NullableDateUpdateOperationsInput     `json:"optionalDay,omitempty"`
	OptionalClock   *NullableTimeUpdateOperationsInput     `json:"optionalClock,omitempty"`
	OptionalInstant *NullableDateTimeUpdateOperationsInput `json:"optionalInstant,omitempty"`
	Category        *MetricCategoryUpdateRelationInput     `json:"category,omitempty"`
}

type MetricUpdateManyInput struct {
	ID              *UUIDUpdateOperationsInput             `json:"id,omitempty"`
	Flag            *BooleanUpdateOperationsInput          `json:"flag,omitempty"`
	Small           *IntUpdateOperationsInput              `json:"small,omitempty"`
	Integer         *IntUpdateOperationsInput              `json:"integer,omitempty"`
	Big             *BigIntUpdateOperationsInput           `json:"big,omitempty"`
	Float           *FloatUpdateOperationsInput            `json:"float,omitempty"`
	Double          *FloatUpdateOperationsInput            `json:"double,omitempty"`
	Amount          *DecimalUpdateOperationsInput          `json:"amount,omitempty"`
	Label           *StringUpdateOperationsInput           `json:"label,omitempty"`
	Reference       *UUIDUpdateOperationsInput             `json:"reference,omitempty"`
	Day             *DateUpdateOperationsInput             `json:"day,omitempty"`
	Clock           *TimeUpdateOperationsInput             `json:"clock,omitempty"`
	OccurredAt      *DateTimeUpdateOperationsInput         `json:"occurredAt,omitempty"`
	State           *StatusUpdateOperationsInput           `json:"state,omitempty"`
	OptionalBig     *NullableBigIntUpdateOperationsInput   `json:"optionalBig,omitempty"`
	OptionalAmount  *NullableDecimalUpdateOperationsInput  `json:"optionalAmount,omitempty"`
	OptionalLabel   *NullableStringUpdateOperationsInput   `json:"optionalLabel,omitempty"`
	OptionalDay     *NullableDateUpdateOperationsInput     `json:"optionalDay,omitempty"`
	OptionalClock   *NullableTimeUpdateOperationsInput     `json:"optionalClock,omitempty"`
	OptionalInstant *NullableDateTimeUpdateOperationsInput `json:"optionalInstant,omitempty"`
	CategoryID      *NullableUUIDUpdateOperationsInput     `json:"categoryID,omitempty"`
}

type MetricUpdateManyWithWhereWithoutCategoryInput struct {
	Where *MetricWhereInput      `json:"where"`
	Data  *MetricUpdateManyInput `json:"data"`
}

type MetricUpdateWithWhereWithoutCategoryInput struct {
	Where *MetricWhereUniqueInput           `json:"where"`
	Data  *MetricUpdateWithoutCategoryInput `json:"data"`
}

type MetricUpdateWithoutCategoryInput struct {
	ID              *UUIDUpdateOperationsInput             `json:"id,omitempty"`
	Flag            *BooleanUpdateOperationsInput          `json:"flag,omitempty"`
	Small           *IntUpdateOperationsInput              `json:"small,omitempty"`
	Integer         *IntUpdateOperationsInput              `json:"integer,omitempty"`
	Big             *BigIntUpdateOperationsInput           `json:"big,omitempty"`
	Float           *FloatUpdateOperationsInput            `json:"float,omitempty"`
	Double          *FloatUpdateOperationsInput            `json:"double,omitempty"`
	Amount          *DecimalUpdateOperationsInput          `json:"amount,omitempty"`
	Label           *StringUpdateOperationsInput           `json:"label,omitempty"`
	Reference       *UUIDUpdateOperationsInput             `json:"reference,omitempty"`
	Day             *DateUpdateOperationsInput             `json:"day,omitempty"`
	Clock           *TimeUpdateOperationsInput             `json:"clock,omitempty"`
	OccurredAt      *DateTimeUpdateOperationsInput         `json:"occurredAt,omitempty"`
	State           *StatusUpdateOperationsInput           `json:"state,omitempty"`
	OptionalBig     *NullableBigIntUpdateOperationsInput   `json:"optionalBig,omitempty"`
	OptionalAmount  *NullableDecimalUpdateOperationsInput  `json:"optionalAmount,omitempty"`
	OptionalLabel   *NullableStringUpdateOperationsInput   `json:"optionalLabel,omitempty"`
	OptionalDay     *NullableDateUpdateOperationsInput     `json:"optionalDay,omitempty"`
	OptionalClock   *NullableTimeUpdateOperationsInput     `json:"optionalClock,omitempty"`
	OptionalInstant *NullableDateTimeUpdateOperationsInput `json:"optionalInstant,omitempty"`
}

type MetricUpsertWithWhereWithoutCategoryInput struct {
	Where  *MetricWhereUniqueInput           `json:"where"`
	Create *MetricCreateWithoutCategoryInput `json:"create"`
	Update *MetricUpdateWithoutCategoryInput `json:"update"`
}

type MetricWhereInput struct {
	All             *bool                   `json:"all,omitempty"`
	And             []*MetricWhereInput     `json:"AND,omitempty"`
	Or              []*MetricWhereInput     `json:"OR,omitempty"`
	Not             []*MetricWhereInput     `json:"NOT,omitempty"`
	ID              *UUIDFilter             `json:"id,omitempty"`
	Flag            *BooleanFilter          `json:"flag,omitempty"`
	Small           *IntFilter              `json:"small,omitempty"`
	Integer         *IntFilter              `json:"integer,omitempty"`
	Big             *BigIntFilter           `json:"big,omitempty"`
	Float           *FloatFilter            `json:"float,omitempty"`
	Double          *FloatFilter            `json:"double,omitempty"`
	Amount          *DecimalFilter          `json:"amount,omitempty"`
	Label           *StringFilter           `json:"label,omitempty"`
	Reference       *UUIDFilter             `json:"reference,omitempty"`
	Day             *DateFilter             `json:"day,omitempty"`
	Clock           *TimeFilter             `json:"clock,omitempty"`
	OccurredAt      *DateTimeFilter         `json:"occurredAt,omitempty"`
	State           *StatusFilter           `json:"state,omitempty"`
	OptionalBig     *NullableBigIntFilter   `json:"optionalBig,omitempty"`
	OptionalAmount  *NullableDecimalFilter  `json:"optionalAmount,omitempty"`
	OptionalLabel   *NullableStringFilter   `json:"optionalLabel,omitempty"`
	OptionalDay     *NullableDateFilter     `json:"optionalDay,omitempty"`
	OptionalClock   *NullableTimeFilter     `json:"optionalClock,omitempty"`
	OptionalInstant *NullableDateTimeFilter `json:"optionalInstant,omitempty"`
	CategoryID      *NullableUUIDFilter     `json:"categoryID,omitempty"`
	Category        *CategoryRelationFilter `json:"category,omitempty"`
}

type MetricWhereUniqueInput struct {
	ID any `json:"ID,omitempty"`
}

type NullableBigIntFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableBigIntListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableBigIntListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableBigIntUpdateOperationsInput struct {
	Set       any   `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment any   `json:"increment,omitempty"`
	Decrement any   `json:"decrement,omitempty"`
}

type NullableBooleanFilter struct {
	Equals *bool  `json:"equals,omitempty"`
	Not    *bool  `json:"not,omitempty"`
	In     []bool `json:"in,omitempty"`
	NotIn  []bool `json:"notIn,omitempty"`
	IsNull *bool  `json:"isNull,omitempty"`
}

type NullableBooleanListFilter struct {
	Equals   []bool `json:"equals,omitempty"`
	Has      *bool  `json:"has,omitempty"`
	HasEvery []bool `json:"hasEvery,omitempty"`
	HasSome  []bool `json:"hasSome,omitempty"`
	IsEmpty  *bool  `json:"isEmpty,omitempty"`
	IsNull   *bool  `json:"isNull,omitempty"`
}

type NullableBooleanListUpdateOperationsInput struct {
	Set     []bool `json:"set,omitempty"`
	SetNull *bool  `json:"setNull,omitempty"`
}

type NullableBooleanUpdateOperationsInput struct {
	Set     *bool `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableBytesFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableBytesUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDateListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDateListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDateTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDateTimeListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateTimeUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDateUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDecimalFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableDecimalListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableDecimalListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableDecimalUpdateOperationsInput struct {
	Set       any   `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment any   `json:"increment,omitempty"`
	Decrement any   `json:"decrement,omitempty"`
}

type NullableFloatFilter struct {
	Equals *float64  `json:"equals,omitempty"`
	Not    *float64  `json:"not,omitempty"`
	In     []float64 `json:"in,omitempty"`
	NotIn  []float64 `json:"notIn,omitempty"`
	Lt     *float64  `json:"lt,omitempty"`
	Lte    *float64  `json:"lte,omitempty"`
	Gt     *float64  `json:"gt,omitempty"`
	Gte    *float64  `json:"gte,omitempty"`
	IsNull *bool     `json:"isNull,omitempty"`
}

type NullableFloatListFilter struct {
	Equals   []float64 `json:"equals,omitempty"`
	Has      *float64  `json:"has,omitempty"`
	HasEvery []float64 `json:"hasEvery,omitempty"`
	HasSome  []float64 `json:"hasSome,omitempty"`
	IsEmpty  *bool     `json:"isEmpty,omitempty"`
	IsNull   *bool     `json:"isNull,omitempty"`
}

type NullableFloatListUpdateOperationsInput struct {
	Set     []float64 `json:"set,omitempty"`
	SetNull *bool     `json:"setNull,omitempty"`
}

type NullableFloatUpdateOperationsInput struct {
	Set       *float64 `json:"set,omitempty"`
	SetNull   *bool    `json:"setNull,omitempty"`
	Increment *float64 `json:"increment,omitempty"`
	Decrement *float64 `json:"decrement,omitempty"`
}

type NullableIntFilter struct {
	Equals *int  `json:"equals,omitempty"`
	Not    *int  `json:"not,omitempty"`
	In     []int `json:"in,omitempty"`
	NotIn  []int `json:"notIn,omitempty"`
	Lt     *int  `json:"lt,omitempty"`
	Lte    *int  `json:"lte,omitempty"`
	Gt     *int  `json:"gt,omitempty"`
	Gte    *int  `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableIntListFilter struct {
	Equals   []int `json:"equals,omitempty"`
	Has      *int  `json:"has,omitempty"`
	HasEvery []int `json:"hasEvery,omitempty"`
	HasSome  []int `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableIntListUpdateOperationsInput struct {
	Set     []int `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableIntUpdateOperationsInput struct {
	Set       *int  `json:"set,omitempty"`
	SetNull   *bool `json:"setNull,omitempty"`
	Increment *int  `json:"increment,omitempty"`
	Decrement *int  `json:"decrement,omitempty"`
}

type NullableJSONFilter struct {
	Equals           any        `json:"equals,omitempty"`
	Not              any        `json:"not,omitempty"`
	Lt               any        `json:"lt,omitempty"`
	Lte              any        `json:"lte,omitempty"`
	Gt               any        `json:"gt,omitempty"`
	Gte              any        `json:"gte,omitempty"`
	StringContains   *string    `json:"stringContains,omitempty"`
	StringStartsWith *string    `json:"stringStartsWith,omitempty"`
	StringEndsWith   *string    `json:"stringEndsWith,omitempty"`
	ArrayContains    any        `json:"arrayContains,omitempty"`
	ArrayStartsWith  any        `json:"arrayStartsWith,omitempty"`
	ArrayEndsWith    any        `json:"arrayEndsWith,omitempty"`
	Path             []string   `json:"path,omitempty"`
	Mode             *QueryMode `json:"mode,omitempty"`
	IsNull           *bool      `json:"isNull,omitempty"`
}

type NullableJSONUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableStatusFilter struct {
	Equals *Status  `json:"equals,omitempty"`
	Not    *Status  `json:"not,omitempty"`
	In     []Status `json:"in,omitempty"`
	NotIn  []Status `json:"notIn,omitempty"`
	IsNull *bool    `json:"isNull,omitempty"`
}

type NullableStatusListFilter struct {
	Equals   []Status `json:"equals,omitempty"`
	Has      *Status  `json:"has,omitempty"`
	HasEvery []Status `json:"hasEvery,omitempty"`
	HasSome  []Status `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
	IsNull   *bool    `json:"isNull,omitempty"`
}

type NullableStatusListUpdateOperationsInput struct {
	Set     []Status `json:"set,omitempty"`
	SetNull *bool    `json:"setNull,omitempty"`
}

type NullableStatusUpdateOperationsInput struct {
	Set     *Status `json:"set,omitempty"`
	SetNull *bool   `json:"setNull,omitempty"`
}

type NullableStringFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	In         []string   `json:"in,omitempty"`
	NotIn      []string   `json:"notIn,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
	IsNull     *bool      `json:"isNull,omitempty"`
}

type NullableStringListFilter struct {
	Equals   []string `json:"equals,omitempty"`
	Has      *string  `json:"has,omitempty"`
	HasEvery []string `json:"hasEvery,omitempty"`
	HasSome  []string `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
	IsNull   *bool    `json:"isNull,omitempty"`
}

type NullableStringListUpdateOperationsInput struct {
	Set     []string `json:"set,omitempty"`
	SetNull *bool    `json:"setNull,omitempty"`
}

type NullableStringUpdateOperationsInput struct {
	Set     *string `json:"set,omitempty"`
	SetNull *bool   `json:"setNull,omitempty"`
}

type NullableTimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableTimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableTimeListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableTimeUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableUUIDFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type NullableUUIDListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
	IsNull   *bool `json:"isNull,omitempty"`
}

type NullableUUIDListUpdateOperationsInput struct {
	Set     []any `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type NullableUUIDUpdateOperationsInput struct {
	Set     any   `json:"set,omitempty"`
	SetNull *bool `json:"setNull,omitempty"`
}

type StatusAnalyticsFilter struct {
	Equals *Status `json:"equals,omitempty"`
	Not    *Status `json:"not,omitempty"`
	IsNull *bool   `json:"isNull,omitempty"`
}

type StatusFilter struct {
	Equals *Status  `json:"equals,omitempty"`
	Not    *Status  `json:"not,omitempty"`
	In     []Status `json:"in,omitempty"`
	NotIn  []Status `json:"notIn,omitempty"`
}

type StatusListFilter struct {
	Equals   []Status `json:"equals,omitempty"`
	Has      *Status  `json:"has,omitempty"`
	HasEvery []Status `json:"hasEvery,omitempty"`
	HasSome  []Status `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
}

type StatusListUpdateOperationsInput struct {
	Set []Status `json:"set,omitempty"`
}

type StatusUpdateOperationsInput struct {
	Set *Status `json:"set,omitempty"`
}

type StringAnalyticsFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
	IsNull     *bool      `json:"isNull,omitempty"`
}

type StringFilter struct {
	Equals     *string    `json:"equals,omitempty"`
	Not        *string    `json:"not,omitempty"`
	In         []string   `json:"in,omitempty"`
	NotIn      []string   `json:"notIn,omitempty"`
	Lt         *string    `json:"lt,omitempty"`
	Lte        *string    `json:"lte,omitempty"`
	Gt         *string    `json:"gt,omitempty"`
	Gte        *string    `json:"gte,omitempty"`
	Contains   *string    `json:"contains,omitempty"`
	StartsWith *string    `json:"startsWith,omitempty"`
	EndsWith   *string    `json:"endsWith,omitempty"`
	Mode       *QueryMode `json:"mode,omitempty"`
}

type StringListFilter struct {
	Equals   []string `json:"equals,omitempty"`
	Has      *string  `json:"has,omitempty"`
	HasEvery []string `json:"hasEvery,omitempty"`
	HasSome  []string `json:"hasSome,omitempty"`
	IsEmpty  *bool    `json:"isEmpty,omitempty"`
}

type StringListUpdateOperationsInput struct {
	Set []string `json:"set,omitempty"`
}

type StringUpdateOperationsInput struct {
	Set *string `json:"set,omitempty"`
}

type TimeAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type TimeFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
	Lt     any   `json:"lt,omitempty"`
	Lte    any   `json:"lte,omitempty"`
	Gt     any   `json:"gt,omitempty"`
	Gte    any   `json:"gte,omitempty"`
}

type TimeListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type TimeListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type TimeUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type UUIDAnalyticsFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	IsNull *bool `json:"isNull,omitempty"`
}

type UUIDFilter struct {
	Equals any   `json:"equals,omitempty"`
	Not    any   `json:"not,omitempty"`
	In     []any `json:"in,omitempty"`
	NotIn  []any `json:"notIn,omitempty"`
}

type UUIDListFilter struct {
	Equals   []any `json:"equals,omitempty"`
	Has      any   `json:"has,omitempty"`
	HasEvery []any `json:"hasEvery,omitempty"`
	HasSome  []any `json:"hasSome,omitempty"`
	IsEmpty  *bool `json:"isEmpty,omitempty"`
}

type UUIDListUpdateOperationsInput struct {
	Set []any `json:"set,omitempty"`
}

type UUIDUpdateOperationsInput struct {
	Set any `json:"set,omitempty"`
}

type CategoryScalarField string

const (
	CategoryScalarFieldID       CategoryScalarField = "id"
	CategoryScalarFieldName     CategoryScalarField = "name"
	CategoryScalarFieldParentID CategoryScalarField = "parentID"
)

var AllCategoryScalarField = []CategoryScalarField{
	CategoryScalarFieldID,
	CategoryScalarFieldName,
	CategoryScalarFieldParentID,
}

func (e CategoryScalarField) IsValid() bool {
	switch e {
	case CategoryScalarFieldID, CategoryScalarFieldName, CategoryScalarFieldParentID:
		return true
	}
	return false
}

func (e CategoryScalarField) String() string {
	return string(e)
}

func (e *CategoryScalarField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryScalarField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryScalarField", str)
	}
	return nil
}

func (e CategoryScalarField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MetricGroupField string

const (
	MetricGroupFieldAmount          MetricGroupField = "amount"
	MetricGroupFieldBig             MetricGroupField = "big"
	MetricGroupFieldCategoryID      MetricGroupField = "categoryID"
	MetricGroupFieldClock           MetricGroupField = "clock"
	MetricGroupFieldDay             MetricGroupField = "day"
	MetricGroupFieldDouble          MetricGroupField = "double"
	MetricGroupFieldFlag            MetricGroupField = "flag"
	MetricGroupFieldFloat           MetricGroupField = "float"
	MetricGroupFieldID              MetricGroupField = "id"
	MetricGroupFieldInteger         MetricGroupField = "integer"
	MetricGroupFieldLabel           MetricGroupField = "label"
	MetricGroupFieldOccurredAt      MetricGroupField = "occurredAt"
	MetricGroupFieldOptionalAmount  MetricGroupField = "optionalAmount"
	MetricGroupFieldOptionalBig     MetricGroupField = "optionalBig"
	MetricGroupFieldOptionalClock   MetricGroupField = "optionalClock"
	MetricGroupFieldOptionalDay     MetricGroupField = "optionalDay"
	MetricGroupFieldOptionalInstant MetricGroupField = "optionalInstant"
	MetricGroupFieldOptionalLabel   MetricGroupField = "optionalLabel"
	MetricGroupFieldReference       MetricGroupField = "reference"
	MetricGroupFieldSmall           MetricGroupField = "small"
	MetricGroupFieldState           MetricGroupField = "state"
)

var AllMetricGroupField = []MetricGroupField{
	MetricGroupFieldAmount,
	MetricGroupFieldBig,
	MetricGroupFieldCategoryID,
	MetricGroupFieldClock,
	MetricGroupFieldDay,
	MetricGroupFieldDouble,
	MetricGroupFieldFlag,
	MetricGroupFieldFloat,
	MetricGroupFieldID,
	MetricGroupFieldInteger,
	MetricGroupFieldLabel,
	MetricGroupFieldOccurredAt,
	MetricGroupFieldOptionalAmount,
	MetricGroupFieldOptionalBig,
	MetricGroupFieldOptionalClock,
	MetricGroupFieldOptionalDay,
	MetricGroupFieldOptionalInstant,
	MetricGroupFieldOptionalLabel,
	MetricGroupFieldReference,
	MetricGroupFieldSmall,
	MetricGroupFieldState,
}

func (e MetricGroupField) IsValid() bool {
	switch e {
	case MetricGroupFieldAmount, MetricGroupFieldBig, MetricGroupFieldCategoryID, MetricGroupFieldClock, MetricGroupFieldDay, MetricGroupFieldDouble, MetricGroupFieldFlag, MetricGroupFieldFloat, MetricGroupFieldID, MetricGroupFieldInteger, MetricGroupFieldLabel, MetricGroupFieldOccurredAt, MetricGroupFieldOptionalAmount, MetricGroupFieldOptionalBig, MetricGroupFieldOptionalClock, MetricGroupFieldOptionalDay, MetricGroupFieldOptionalInstant, MetricGroupFieldOptionalLabel, MetricGroupFieldReference, MetricGroupFieldSmall, MetricGroupFieldState:
		return true
	}
	return false
}

func (e MetricGroupField) String() string {
	return string(e)
}

func (e *MetricGroupField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MetricGroupField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MetricGroupField", str)
	}
	return nil
}

func (e MetricGroupField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MetricScalarField string

const (
	MetricScalarFieldID              MetricScalarField = "id"
	MetricScalarFieldFlag            MetricScalarField = "flag"
	MetricScalarFieldSmall           MetricScalarField = "small"
	MetricScalarFieldInteger         MetricScalarField = "integer"
	MetricScalarFieldBig             MetricScalarField = "big"
	MetricScalarFieldFloat           MetricScalarField = "float"
	MetricScalarFieldDouble          MetricScalarField = "double"
	MetricScalarFieldAmount          MetricScalarField = "amount"
	MetricScalarFieldLabel           MetricScalarField = "label"
	MetricScalarFieldReference       MetricScalarField = "reference"
	MetricScalarFieldDay             MetricScalarField = "day"
	MetricScalarFieldClock           MetricScalarField = "clock"
	MetricScalarFieldOccurredAt      MetricScalarField = "occurredAt"
	MetricScalarFieldState           MetricScalarField = "state"
	MetricScalarFieldOptionalBig     MetricScalarField = "optionalBig"
	MetricScalarFieldOptionalAmount  MetricScalarField = "optionalAmount"
	MetricScalarFieldOptionalLabel   MetricScalarField = "optionalLabel"
	MetricScalarFieldOptionalDay     MetricScalarField = "optionalDay"
	MetricScalarFieldOptionalClock   MetricScalarField = "optionalClock"
	MetricScalarFieldOptionalInstant MetricScalarField = "optionalInstant"
	MetricScalarFieldCategoryID      MetricScalarField = "categoryID"
)

var AllMetricScalarField = []MetricScalarField{
	MetricScalarFieldID,
	MetricScalarFieldFlag,
	MetricScalarFieldSmall,
	MetricScalarFieldInteger,
	MetricScalarFieldBig,
	MetricScalarFieldFloat,
	MetricScalarFieldDouble,
	MetricScalarFieldAmount,
	MetricScalarFieldLabel,
	MetricScalarFieldReference,
	MetricScalarFieldDay,
	MetricScalarFieldClock,
	MetricScalarFieldOccurredAt,
	MetricScalarFieldState,
	MetricScalarFieldOptionalBig,
	MetricScalarFieldOptionalAmount,
	MetricScalarFieldOptionalLabel,
	MetricScalarFieldOptionalDay,
	MetricScalarFieldOptionalClock,
	MetricScalarFieldOptionalInstant,
	MetricScalarFieldCategoryID,
}

func (e MetricScalarField) IsValid() bool {
	switch e {
	case MetricScalarFieldID, MetricScalarFieldFlag, MetricScalarFieldSmall, MetricScalarFieldInteger, MetricScalarFieldBig, MetricScalarFieldFloat, MetricScalarFieldDouble, MetricScalarFieldAmount, MetricScalarFieldLabel, MetricScalarFieldReference, MetricScalarFieldDay, MetricScalarFieldClock, MetricScalarFieldOccurredAt, MetricScalarFieldState, MetricScalarFieldOptionalBig, MetricScalarFieldOptionalAmount, MetricScalarFieldOptionalLabel, MetricScalarFieldOptionalDay, MetricScalarFieldOptionalClock, MetricScalarFieldOptionalInstant, MetricScalarFieldCategoryID:
		return true
	}
	return false
}

func (e MetricScalarField) String() string {
	return string(e)
}

func (e *MetricScalarField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MetricScalarField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MetricScalarField", str)
	}
	return nil
}

func (e MetricScalarField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type QueryMode string

const (
	QueryModeSensitive   QueryMode = "sensitive"
	QueryModeInsensitive QueryMode = "insensitive"
)

var AllQueryMode = []QueryMode{
	QueryModeSensitive,
	QueryModeInsensitive,
}

func (e QueryMode) IsValid() bool {
	switch e {
	case QueryModeSensitive, QueryModeInsensitive:
		return true
	}
	return false
}

func (e QueryMode) String() string {
	return string(e)
}

func (e *QueryMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QueryMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QueryMode", str)
	}
	return nil
}

func (e QueryMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Status string

const (
	StatusStatusAlpha Status = "StatusAlpha"
	StatusStatusOmega Status = "StatusOmega"
)

var AllStatus = []Status{
	StatusStatusAlpha,
	StatusStatusOmega,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusStatusAlpha, StatusStatusOmega:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
